// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package dashboard

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.AWSAccountID, b.ko.Spec.AWSAccountID) {
		delta.Add("Spec.AWSAccountID", a.ko.Spec.AWSAccountID, b.ko.Spec.AWSAccountID)
	} else if a.ko.Spec.AWSAccountID != nil && b.ko.Spec.AWSAccountID != nil {
		if *a.ko.Spec.AWSAccountID != *b.ko.Spec.AWSAccountID {
			delta.Add("Spec.AWSAccountID", a.ko.Spec.AWSAccountID, b.ko.Spec.AWSAccountID)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.DashboardID, b.ko.Spec.DashboardID) {
		delta.Add("Spec.DashboardID", a.ko.Spec.DashboardID, b.ko.Spec.DashboardID)
	} else if a.ko.Spec.DashboardID != nil && b.ko.Spec.DashboardID != nil {
		if *a.ko.Spec.DashboardID != *b.ko.Spec.DashboardID {
			delta.Add("Spec.DashboardID", a.ko.Spec.DashboardID, b.ko.Spec.DashboardID)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.DashboardPublishOptions, b.ko.Spec.DashboardPublishOptions) {
		delta.Add("Spec.DashboardPublishOptions", a.ko.Spec.DashboardPublishOptions, b.ko.Spec.DashboardPublishOptions)
	} else if a.ko.Spec.DashboardPublishOptions != nil && b.ko.Spec.DashboardPublishOptions != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.DashboardPublishOptions.AdHocFilteringOption, b.ko.Spec.DashboardPublishOptions.AdHocFilteringOption) {
			delta.Add("Spec.DashboardPublishOptions.AdHocFilteringOption", a.ko.Spec.DashboardPublishOptions.AdHocFilteringOption, b.ko.Spec.DashboardPublishOptions.AdHocFilteringOption)
		} else if a.ko.Spec.DashboardPublishOptions.AdHocFilteringOption != nil && b.ko.Spec.DashboardPublishOptions.AdHocFilteringOption != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.DashboardPublishOptions.AdHocFilteringOption.AvailabilityStatus, b.ko.Spec.DashboardPublishOptions.AdHocFilteringOption.AvailabilityStatus) {
				delta.Add("Spec.DashboardPublishOptions.AdHocFilteringOption.AvailabilityStatus", a.ko.Spec.DashboardPublishOptions.AdHocFilteringOption.AvailabilityStatus, b.ko.Spec.DashboardPublishOptions.AdHocFilteringOption.AvailabilityStatus)
			} else if a.ko.Spec.DashboardPublishOptions.AdHocFilteringOption.AvailabilityStatus != nil && b.ko.Spec.DashboardPublishOptions.AdHocFilteringOption.AvailabilityStatus != nil {
				if *a.ko.Spec.DashboardPublishOptions.AdHocFilteringOption.AvailabilityStatus != *b.ko.Spec.DashboardPublishOptions.AdHocFilteringOption.AvailabilityStatus {
					delta.Add("Spec.DashboardPublishOptions.AdHocFilteringOption.AvailabilityStatus", a.ko.Spec.DashboardPublishOptions.AdHocFilteringOption.AvailabilityStatus, b.ko.Spec.DashboardPublishOptions.AdHocFilteringOption.AvailabilityStatus)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.DashboardPublishOptions.DataPointDrillUpDownOption, b.ko.Spec.DashboardPublishOptions.DataPointDrillUpDownOption) {
			delta.Add("Spec.DashboardPublishOptions.DataPointDrillUpDownOption", a.ko.Spec.DashboardPublishOptions.DataPointDrillUpDownOption, b.ko.Spec.DashboardPublishOptions.DataPointDrillUpDownOption)
		} else if a.ko.Spec.DashboardPublishOptions.DataPointDrillUpDownOption != nil && b.ko.Spec.DashboardPublishOptions.DataPointDrillUpDownOption != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.DashboardPublishOptions.DataPointDrillUpDownOption.AvailabilityStatus, b.ko.Spec.DashboardPublishOptions.DataPointDrillUpDownOption.AvailabilityStatus) {
				delta.Add("Spec.DashboardPublishOptions.DataPointDrillUpDownOption.AvailabilityStatus", a.ko.Spec.DashboardPublishOptions.DataPointDrillUpDownOption.AvailabilityStatus, b.ko.Spec.DashboardPublishOptions.DataPointDrillUpDownOption.AvailabilityStatus)
			} else if a.ko.Spec.DashboardPublishOptions.DataPointDrillUpDownOption.AvailabilityStatus != nil && b.ko.Spec.DashboardPublishOptions.DataPointDrillUpDownOption.AvailabilityStatus != nil {
				if *a.ko.Spec.DashboardPublishOptions.DataPointDrillUpDownOption.AvailabilityStatus != *b.ko.Spec.DashboardPublishOptions.DataPointDrillUpDownOption.AvailabilityStatus {
					delta.Add("Spec.DashboardPublishOptions.DataPointDrillUpDownOption.AvailabilityStatus", a.ko.Spec.DashboardPublishOptions.DataPointDrillUpDownOption.AvailabilityStatus, b.ko.Spec.DashboardPublishOptions.DataPointDrillUpDownOption.AvailabilityStatus)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.DashboardPublishOptions.DataPointMenuLabelOption, b.ko.Spec.DashboardPublishOptions.DataPointMenuLabelOption) {
			delta.Add("Spec.DashboardPublishOptions.DataPointMenuLabelOption", a.ko.Spec.DashboardPublishOptions.DataPointMenuLabelOption, b.ko.Spec.DashboardPublishOptions.DataPointMenuLabelOption)
		} else if a.ko.Spec.DashboardPublishOptions.DataPointMenuLabelOption != nil && b.ko.Spec.DashboardPublishOptions.DataPointMenuLabelOption != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.DashboardPublishOptions.DataPointMenuLabelOption.AvailabilityStatus, b.ko.Spec.DashboardPublishOptions.DataPointMenuLabelOption.AvailabilityStatus) {
				delta.Add("Spec.DashboardPublishOptions.DataPointMenuLabelOption.AvailabilityStatus", a.ko.Spec.DashboardPublishOptions.DataPointMenuLabelOption.AvailabilityStatus, b.ko.Spec.DashboardPublishOptions.DataPointMenuLabelOption.AvailabilityStatus)
			} else if a.ko.Spec.DashboardPublishOptions.DataPointMenuLabelOption.AvailabilityStatus != nil && b.ko.Spec.DashboardPublishOptions.DataPointMenuLabelOption.AvailabilityStatus != nil {
				if *a.ko.Spec.DashboardPublishOptions.DataPointMenuLabelOption.AvailabilityStatus != *b.ko.Spec.DashboardPublishOptions.DataPointMenuLabelOption.AvailabilityStatus {
					delta.Add("Spec.DashboardPublishOptions.DataPointMenuLabelOption.AvailabilityStatus", a.ko.Spec.DashboardPublishOptions.DataPointMenuLabelOption.AvailabilityStatus, b.ko.Spec.DashboardPublishOptions.DataPointMenuLabelOption.AvailabilityStatus)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.DashboardPublishOptions.DataPointTooltipOption, b.ko.Spec.DashboardPublishOptions.DataPointTooltipOption) {
			delta.Add("Spec.DashboardPublishOptions.DataPointTooltipOption", a.ko.Spec.DashboardPublishOptions.DataPointTooltipOption, b.ko.Spec.DashboardPublishOptions.DataPointTooltipOption)
		} else if a.ko.Spec.DashboardPublishOptions.DataPointTooltipOption != nil && b.ko.Spec.DashboardPublishOptions.DataPointTooltipOption != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.DashboardPublishOptions.DataPointTooltipOption.AvailabilityStatus, b.ko.Spec.DashboardPublishOptions.DataPointTooltipOption.AvailabilityStatus) {
				delta.Add("Spec.DashboardPublishOptions.DataPointTooltipOption.AvailabilityStatus", a.ko.Spec.DashboardPublishOptions.DataPointTooltipOption.AvailabilityStatus, b.ko.Spec.DashboardPublishOptions.DataPointTooltipOption.AvailabilityStatus)
			} else if a.ko.Spec.DashboardPublishOptions.DataPointTooltipOption.AvailabilityStatus != nil && b.ko.Spec.DashboardPublishOptions.DataPointTooltipOption.AvailabilityStatus != nil {
				if *a.ko.Spec.DashboardPublishOptions.DataPointTooltipOption.AvailabilityStatus != *b.ko.Spec.DashboardPublishOptions.DataPointTooltipOption.AvailabilityStatus {
					delta.Add("Spec.DashboardPublishOptions.DataPointTooltipOption.AvailabilityStatus", a.ko.Spec.DashboardPublishOptions.DataPointTooltipOption.AvailabilityStatus, b.ko.Spec.DashboardPublishOptions.DataPointTooltipOption.AvailabilityStatus)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.DashboardPublishOptions.ExportToCSVOption, b.ko.Spec.DashboardPublishOptions.ExportToCSVOption) {
			delta.Add("Spec.DashboardPublishOptions.ExportToCSVOption", a.ko.Spec.DashboardPublishOptions.ExportToCSVOption, b.ko.Spec.DashboardPublishOptions.ExportToCSVOption)
		} else if a.ko.Spec.DashboardPublishOptions.ExportToCSVOption != nil && b.ko.Spec.DashboardPublishOptions.ExportToCSVOption != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.DashboardPublishOptions.ExportToCSVOption.AvailabilityStatus, b.ko.Spec.DashboardPublishOptions.ExportToCSVOption.AvailabilityStatus) {
				delta.Add("Spec.DashboardPublishOptions.ExportToCSVOption.AvailabilityStatus", a.ko.Spec.DashboardPublishOptions.ExportToCSVOption.AvailabilityStatus, b.ko.Spec.DashboardPublishOptions.ExportToCSVOption.AvailabilityStatus)
			} else if a.ko.Spec.DashboardPublishOptions.ExportToCSVOption.AvailabilityStatus != nil && b.ko.Spec.DashboardPublishOptions.ExportToCSVOption.AvailabilityStatus != nil {
				if *a.ko.Spec.DashboardPublishOptions.ExportToCSVOption.AvailabilityStatus != *b.ko.Spec.DashboardPublishOptions.ExportToCSVOption.AvailabilityStatus {
					delta.Add("Spec.DashboardPublishOptions.ExportToCSVOption.AvailabilityStatus", a.ko.Spec.DashboardPublishOptions.ExportToCSVOption.AvailabilityStatus, b.ko.Spec.DashboardPublishOptions.ExportToCSVOption.AvailabilityStatus)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.DashboardPublishOptions.ExportWithHiddenFieldsOption, b.ko.Spec.DashboardPublishOptions.ExportWithHiddenFieldsOption) {
			delta.Add("Spec.DashboardPublishOptions.ExportWithHiddenFieldsOption", a.ko.Spec.DashboardPublishOptions.ExportWithHiddenFieldsOption, b.ko.Spec.DashboardPublishOptions.ExportWithHiddenFieldsOption)
		} else if a.ko.Spec.DashboardPublishOptions.ExportWithHiddenFieldsOption != nil && b.ko.Spec.DashboardPublishOptions.ExportWithHiddenFieldsOption != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.DashboardPublishOptions.ExportWithHiddenFieldsOption.AvailabilityStatus, b.ko.Spec.DashboardPublishOptions.ExportWithHiddenFieldsOption.AvailabilityStatus) {
				delta.Add("Spec.DashboardPublishOptions.ExportWithHiddenFieldsOption.AvailabilityStatus", a.ko.Spec.DashboardPublishOptions.ExportWithHiddenFieldsOption.AvailabilityStatus, b.ko.Spec.DashboardPublishOptions.ExportWithHiddenFieldsOption.AvailabilityStatus)
			} else if a.ko.Spec.DashboardPublishOptions.ExportWithHiddenFieldsOption.AvailabilityStatus != nil && b.ko.Spec.DashboardPublishOptions.ExportWithHiddenFieldsOption.AvailabilityStatus != nil {
				if *a.ko.Spec.DashboardPublishOptions.ExportWithHiddenFieldsOption.AvailabilityStatus != *b.ko.Spec.DashboardPublishOptions.ExportWithHiddenFieldsOption.AvailabilityStatus {
					delta.Add("Spec.DashboardPublishOptions.ExportWithHiddenFieldsOption.AvailabilityStatus", a.ko.Spec.DashboardPublishOptions.ExportWithHiddenFieldsOption.AvailabilityStatus, b.ko.Spec.DashboardPublishOptions.ExportWithHiddenFieldsOption.AvailabilityStatus)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.DashboardPublishOptions.SheetControlsOption, b.ko.Spec.DashboardPublishOptions.SheetControlsOption) {
			delta.Add("Spec.DashboardPublishOptions.SheetControlsOption", a.ko.Spec.DashboardPublishOptions.SheetControlsOption, b.ko.Spec.DashboardPublishOptions.SheetControlsOption)
		} else if a.ko.Spec.DashboardPublishOptions.SheetControlsOption != nil && b.ko.Spec.DashboardPublishOptions.SheetControlsOption != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.DashboardPublishOptions.SheetControlsOption.VisibilityState, b.ko.Spec.DashboardPublishOptions.SheetControlsOption.VisibilityState) {
				delta.Add("Spec.DashboardPublishOptions.SheetControlsOption.VisibilityState", a.ko.Spec.DashboardPublishOptions.SheetControlsOption.VisibilityState, b.ko.Spec.DashboardPublishOptions.SheetControlsOption.VisibilityState)
			} else if a.ko.Spec.DashboardPublishOptions.SheetControlsOption.VisibilityState != nil && b.ko.Spec.DashboardPublishOptions.SheetControlsOption.VisibilityState != nil {
				if *a.ko.Spec.DashboardPublishOptions.SheetControlsOption.VisibilityState != *b.ko.Spec.DashboardPublishOptions.SheetControlsOption.VisibilityState {
					delta.Add("Spec.DashboardPublishOptions.SheetControlsOption.VisibilityState", a.ko.Spec.DashboardPublishOptions.SheetControlsOption.VisibilityState, b.ko.Spec.DashboardPublishOptions.SheetControlsOption.VisibilityState)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.DashboardPublishOptions.SheetLayoutElementMaximizationOption, b.ko.Spec.DashboardPublishOptions.SheetLayoutElementMaximizationOption) {
			delta.Add("Spec.DashboardPublishOptions.SheetLayoutElementMaximizationOption", a.ko.Spec.DashboardPublishOptions.SheetLayoutElementMaximizationOption, b.ko.Spec.DashboardPublishOptions.SheetLayoutElementMaximizationOption)
		} else if a.ko.Spec.DashboardPublishOptions.SheetLayoutElementMaximizationOption != nil && b.ko.Spec.DashboardPublishOptions.SheetLayoutElementMaximizationOption != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.DashboardPublishOptions.SheetLayoutElementMaximizationOption.AvailabilityStatus, b.ko.Spec.DashboardPublishOptions.SheetLayoutElementMaximizationOption.AvailabilityStatus) {
				delta.Add("Spec.DashboardPublishOptions.SheetLayoutElementMaximizationOption.AvailabilityStatus", a.ko.Spec.DashboardPublishOptions.SheetLayoutElementMaximizationOption.AvailabilityStatus, b.ko.Spec.DashboardPublishOptions.SheetLayoutElementMaximizationOption.AvailabilityStatus)
			} else if a.ko.Spec.DashboardPublishOptions.SheetLayoutElementMaximizationOption.AvailabilityStatus != nil && b.ko.Spec.DashboardPublishOptions.SheetLayoutElementMaximizationOption.AvailabilityStatus != nil {
				if *a.ko.Spec.DashboardPublishOptions.SheetLayoutElementMaximizationOption.AvailabilityStatus != *b.ko.Spec.DashboardPublishOptions.SheetLayoutElementMaximizationOption.AvailabilityStatus {
					delta.Add("Spec.DashboardPublishOptions.SheetLayoutElementMaximizationOption.AvailabilityStatus", a.ko.Spec.DashboardPublishOptions.SheetLayoutElementMaximizationOption.AvailabilityStatus, b.ko.Spec.DashboardPublishOptions.SheetLayoutElementMaximizationOption.AvailabilityStatus)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.DashboardPublishOptions.VisualAxisSortOption, b.ko.Spec.DashboardPublishOptions.VisualAxisSortOption) {
			delta.Add("Spec.DashboardPublishOptions.VisualAxisSortOption", a.ko.Spec.DashboardPublishOptions.VisualAxisSortOption, b.ko.Spec.DashboardPublishOptions.VisualAxisSortOption)
		} else if a.ko.Spec.DashboardPublishOptions.VisualAxisSortOption != nil && b.ko.Spec.DashboardPublishOptions.VisualAxisSortOption != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.DashboardPublishOptions.VisualAxisSortOption.AvailabilityStatus, b.ko.Spec.DashboardPublishOptions.VisualAxisSortOption.AvailabilityStatus) {
				delta.Add("Spec.DashboardPublishOptions.VisualAxisSortOption.AvailabilityStatus", a.ko.Spec.DashboardPublishOptions.VisualAxisSortOption.AvailabilityStatus, b.ko.Spec.DashboardPublishOptions.VisualAxisSortOption.AvailabilityStatus)
			} else if a.ko.Spec.DashboardPublishOptions.VisualAxisSortOption.AvailabilityStatus != nil && b.ko.Spec.DashboardPublishOptions.VisualAxisSortOption.AvailabilityStatus != nil {
				if *a.ko.Spec.DashboardPublishOptions.VisualAxisSortOption.AvailabilityStatus != *b.ko.Spec.DashboardPublishOptions.VisualAxisSortOption.AvailabilityStatus {
					delta.Add("Spec.DashboardPublishOptions.VisualAxisSortOption.AvailabilityStatus", a.ko.Spec.DashboardPublishOptions.VisualAxisSortOption.AvailabilityStatus, b.ko.Spec.DashboardPublishOptions.VisualAxisSortOption.AvailabilityStatus)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.DashboardPublishOptions.VisualMenuOption, b.ko.Spec.DashboardPublishOptions.VisualMenuOption) {
			delta.Add("Spec.DashboardPublishOptions.VisualMenuOption", a.ko.Spec.DashboardPublishOptions.VisualMenuOption, b.ko.Spec.DashboardPublishOptions.VisualMenuOption)
		} else if a.ko.Spec.DashboardPublishOptions.VisualMenuOption != nil && b.ko.Spec.DashboardPublishOptions.VisualMenuOption != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.DashboardPublishOptions.VisualMenuOption.AvailabilityStatus, b.ko.Spec.DashboardPublishOptions.VisualMenuOption.AvailabilityStatus) {
				delta.Add("Spec.DashboardPublishOptions.VisualMenuOption.AvailabilityStatus", a.ko.Spec.DashboardPublishOptions.VisualMenuOption.AvailabilityStatus, b.ko.Spec.DashboardPublishOptions.VisualMenuOption.AvailabilityStatus)
			} else if a.ko.Spec.DashboardPublishOptions.VisualMenuOption.AvailabilityStatus != nil && b.ko.Spec.DashboardPublishOptions.VisualMenuOption.AvailabilityStatus != nil {
				if *a.ko.Spec.DashboardPublishOptions.VisualMenuOption.AvailabilityStatus != *b.ko.Spec.DashboardPublishOptions.VisualMenuOption.AvailabilityStatus {
					delta.Add("Spec.DashboardPublishOptions.VisualMenuOption.AvailabilityStatus", a.ko.Spec.DashboardPublishOptions.VisualMenuOption.AvailabilityStatus, b.ko.Spec.DashboardPublishOptions.VisualMenuOption.AvailabilityStatus)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.DashboardPublishOptions.VisualPublishOptions, b.ko.Spec.DashboardPublishOptions.VisualPublishOptions) {
			delta.Add("Spec.DashboardPublishOptions.VisualPublishOptions", a.ko.Spec.DashboardPublishOptions.VisualPublishOptions, b.ko.Spec.DashboardPublishOptions.VisualPublishOptions)
		} else if a.ko.Spec.DashboardPublishOptions.VisualPublishOptions != nil && b.ko.Spec.DashboardPublishOptions.VisualPublishOptions != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.DashboardPublishOptions.VisualPublishOptions.ExportHiddenFieldsOption, b.ko.Spec.DashboardPublishOptions.VisualPublishOptions.ExportHiddenFieldsOption) {
				delta.Add("Spec.DashboardPublishOptions.VisualPublishOptions.ExportHiddenFieldsOption", a.ko.Spec.DashboardPublishOptions.VisualPublishOptions.ExportHiddenFieldsOption, b.ko.Spec.DashboardPublishOptions.VisualPublishOptions.ExportHiddenFieldsOption)
			} else if a.ko.Spec.DashboardPublishOptions.VisualPublishOptions.ExportHiddenFieldsOption != nil && b.ko.Spec.DashboardPublishOptions.VisualPublishOptions.ExportHiddenFieldsOption != nil {
				if ackcompare.HasNilDifference(a.ko.Spec.DashboardPublishOptions.VisualPublishOptions.ExportHiddenFieldsOption.AvailabilityStatus, b.ko.Spec.DashboardPublishOptions.VisualPublishOptions.ExportHiddenFieldsOption.AvailabilityStatus) {
					delta.Add("Spec.DashboardPublishOptions.VisualPublishOptions.ExportHiddenFieldsOption.AvailabilityStatus", a.ko.Spec.DashboardPublishOptions.VisualPublishOptions.ExportHiddenFieldsOption.AvailabilityStatus, b.ko.Spec.DashboardPublishOptions.VisualPublishOptions.ExportHiddenFieldsOption.AvailabilityStatus)
				} else if a.ko.Spec.DashboardPublishOptions.VisualPublishOptions.ExportHiddenFieldsOption.AvailabilityStatus != nil && b.ko.Spec.DashboardPublishOptions.VisualPublishOptions.ExportHiddenFieldsOption.AvailabilityStatus != nil {
					if *a.ko.Spec.DashboardPublishOptions.VisualPublishOptions.ExportHiddenFieldsOption.AvailabilityStatus != *b.ko.Spec.DashboardPublishOptions.VisualPublishOptions.ExportHiddenFieldsOption.AvailabilityStatus {
						delta.Add("Spec.DashboardPublishOptions.VisualPublishOptions.ExportHiddenFieldsOption.AvailabilityStatus", a.ko.Spec.DashboardPublishOptions.VisualPublishOptions.ExportHiddenFieldsOption.AvailabilityStatus, b.ko.Spec.DashboardPublishOptions.VisualPublishOptions.ExportHiddenFieldsOption.AvailabilityStatus)
					}
				}
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Definition, b.ko.Spec.Definition) {
		delta.Add("Spec.Definition", a.ko.Spec.Definition, b.ko.Spec.Definition)
	} else if a.ko.Spec.Definition != nil && b.ko.Spec.Definition != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.Definition.AnalysisDefaults, b.ko.Spec.Definition.AnalysisDefaults) {
			delta.Add("Spec.Definition.AnalysisDefaults", a.ko.Spec.Definition.AnalysisDefaults, b.ko.Spec.Definition.AnalysisDefaults)
		} else if a.ko.Spec.Definition.AnalysisDefaults != nil && b.ko.Spec.Definition.AnalysisDefaults != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration) {
				delta.Add("Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration", a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration)
			} else if a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration != nil && b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration != nil {
				if ackcompare.HasNilDifference(a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration) {
					delta.Add("Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration", a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration)
				} else if a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration != nil && b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration != nil {
					if ackcompare.HasNilDifference(a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.FreeForm, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.FreeForm) {
						delta.Add("Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.FreeForm", a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.FreeForm, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.FreeForm)
					} else if a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.FreeForm != nil && b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.FreeForm != nil {
						if ackcompare.HasNilDifference(a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.FreeForm.CanvasSizeOptions, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.FreeForm.CanvasSizeOptions) {
							delta.Add("Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.FreeForm.CanvasSizeOptions", a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.FreeForm.CanvasSizeOptions, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.FreeForm.CanvasSizeOptions)
						} else if a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.FreeForm.CanvasSizeOptions != nil && b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.FreeForm.CanvasSizeOptions != nil {
							if ackcompare.HasNilDifference(a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.FreeForm.CanvasSizeOptions.ScreenCanvasSizeOptions, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.FreeForm.CanvasSizeOptions.ScreenCanvasSizeOptions) {
								delta.Add("Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.FreeForm.CanvasSizeOptions.ScreenCanvasSizeOptions", a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.FreeForm.CanvasSizeOptions.ScreenCanvasSizeOptions, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.FreeForm.CanvasSizeOptions.ScreenCanvasSizeOptions)
							} else if a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.FreeForm.CanvasSizeOptions.ScreenCanvasSizeOptions != nil && b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.FreeForm.CanvasSizeOptions.ScreenCanvasSizeOptions != nil {
								if ackcompare.HasNilDifference(a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.FreeForm.CanvasSizeOptions.ScreenCanvasSizeOptions.OptimizedViewPortWidth, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.FreeForm.CanvasSizeOptions.ScreenCanvasSizeOptions.OptimizedViewPortWidth) {
									delta.Add("Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.FreeForm.CanvasSizeOptions.ScreenCanvasSizeOptions.OptimizedViewPortWidth", a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.FreeForm.CanvasSizeOptions.ScreenCanvasSizeOptions.OptimizedViewPortWidth, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.FreeForm.CanvasSizeOptions.ScreenCanvasSizeOptions.OptimizedViewPortWidth)
								} else if a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.FreeForm.CanvasSizeOptions.ScreenCanvasSizeOptions.OptimizedViewPortWidth != nil && b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.FreeForm.CanvasSizeOptions.ScreenCanvasSizeOptions.OptimizedViewPortWidth != nil {
									if *a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.FreeForm.CanvasSizeOptions.ScreenCanvasSizeOptions.OptimizedViewPortWidth != *b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.FreeForm.CanvasSizeOptions.ScreenCanvasSizeOptions.OptimizedViewPortWidth {
										delta.Add("Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.FreeForm.CanvasSizeOptions.ScreenCanvasSizeOptions.OptimizedViewPortWidth", a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.FreeForm.CanvasSizeOptions.ScreenCanvasSizeOptions.OptimizedViewPortWidth, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.FreeForm.CanvasSizeOptions.ScreenCanvasSizeOptions.OptimizedViewPortWidth)
									}
								}
							}
						}
					}
					if ackcompare.HasNilDifference(a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid) {
						delta.Add("Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid", a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid)
					} else if a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid != nil && b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid != nil {
						if ackcompare.HasNilDifference(a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions) {
							delta.Add("Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions", a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions)
						} else if a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions != nil && b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions != nil {
							if ackcompare.HasNilDifference(a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions.ScreenCanvasSizeOptions, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions.ScreenCanvasSizeOptions) {
								delta.Add("Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions.ScreenCanvasSizeOptions", a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions.ScreenCanvasSizeOptions, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions.ScreenCanvasSizeOptions)
							} else if a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions.ScreenCanvasSizeOptions != nil && b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions.ScreenCanvasSizeOptions != nil {
								if ackcompare.HasNilDifference(a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions.ScreenCanvasSizeOptions.OptimizedViewPortWidth, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions.ScreenCanvasSizeOptions.OptimizedViewPortWidth) {
									delta.Add("Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions.ScreenCanvasSizeOptions.OptimizedViewPortWidth", a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions.ScreenCanvasSizeOptions.OptimizedViewPortWidth, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions.ScreenCanvasSizeOptions.OptimizedViewPortWidth)
								} else if a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions.ScreenCanvasSizeOptions.OptimizedViewPortWidth != nil && b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions.ScreenCanvasSizeOptions.OptimizedViewPortWidth != nil {
									if *a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions.ScreenCanvasSizeOptions.OptimizedViewPortWidth != *b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions.ScreenCanvasSizeOptions.OptimizedViewPortWidth {
										delta.Add("Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions.ScreenCanvasSizeOptions.OptimizedViewPortWidth", a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions.ScreenCanvasSizeOptions.OptimizedViewPortWidth, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions.ScreenCanvasSizeOptions.OptimizedViewPortWidth)
									}
								}
								if ackcompare.HasNilDifference(a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions.ScreenCanvasSizeOptions.ResizeOption, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions.ScreenCanvasSizeOptions.ResizeOption) {
									delta.Add("Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions.ScreenCanvasSizeOptions.ResizeOption", a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions.ScreenCanvasSizeOptions.ResizeOption, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions.ScreenCanvasSizeOptions.ResizeOption)
								} else if a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions.ScreenCanvasSizeOptions.ResizeOption != nil && b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions.ScreenCanvasSizeOptions.ResizeOption != nil {
									if *a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions.ScreenCanvasSizeOptions.ResizeOption != *b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions.ScreenCanvasSizeOptions.ResizeOption {
										delta.Add("Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions.ScreenCanvasSizeOptions.ResizeOption", a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions.ScreenCanvasSizeOptions.ResizeOption, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.InteractiveLayoutConfiguration.Grid.CanvasSizeOptions.ScreenCanvasSizeOptions.ResizeOption)
									}
								}
							}
						}
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration) {
					delta.Add("Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration", a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration)
				} else if a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration != nil && b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration != nil {
					if ackcompare.HasNilDifference(a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased) {
						delta.Add("Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased", a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased)
					} else if a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased != nil && b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased != nil {
						if ackcompare.HasNilDifference(a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions) {
							delta.Add("Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions", a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions)
						} else if a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions != nil && b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions != nil {
							if ackcompare.HasNilDifference(a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions) {
								delta.Add("Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions", a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions)
							} else if a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions != nil && b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions != nil {
								if ackcompare.HasNilDifference(a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin) {
									delta.Add("Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin", a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin)
								} else if a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin != nil && b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin != nil {
									if ackcompare.HasNilDifference(a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Bottom, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Bottom) {
										delta.Add("Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Bottom", a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Bottom, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Bottom)
									} else if a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Bottom != nil && b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Bottom != nil {
										if *a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Bottom != *b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Bottom {
											delta.Add("Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Bottom", a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Bottom, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Bottom)
										}
									}
									if ackcompare.HasNilDifference(a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Left, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Left) {
										delta.Add("Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Left", a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Left, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Left)
									} else if a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Left != nil && b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Left != nil {
										if *a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Left != *b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Left {
											delta.Add("Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Left", a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Left, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Left)
										}
									}
									if ackcompare.HasNilDifference(a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Right, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Right) {
										delta.Add("Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Right", a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Right, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Right)
									} else if a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Right != nil && b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Right != nil {
										if *a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Right != *b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Right {
											delta.Add("Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Right", a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Right, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Right)
										}
									}
									if ackcompare.HasNilDifference(a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Top, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Top) {
										delta.Add("Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Top", a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Top, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Top)
									} else if a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Top != nil && b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Top != nil {
										if *a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Top != *b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Top {
											delta.Add("Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Top", a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Top, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperMargin.Top)
										}
									}
								}
								if ackcompare.HasNilDifference(a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperOrientation, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperOrientation) {
									delta.Add("Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperOrientation", a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperOrientation, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperOrientation)
								} else if a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperOrientation != nil && b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperOrientation != nil {
									if *a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperOrientation != *b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperOrientation {
										delta.Add("Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperOrientation", a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperOrientation, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperOrientation)
									}
								}
								if ackcompare.HasNilDifference(a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperSize, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperSize) {
									delta.Add("Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperSize", a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperSize, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperSize)
								} else if a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperSize != nil && b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperSize != nil {
									if *a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperSize != *b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperSize {
										delta.Add("Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperSize", a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperSize, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.PaginatedLayoutConfiguration.SectionBased.CanvasSizeOptions.PaperCanvasSizeOptions.PaperSize)
									}
								}
							}
						}
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.SheetContentType, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.SheetContentType) {
					delta.Add("Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.SheetContentType", a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.SheetContentType, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.SheetContentType)
				} else if a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.SheetContentType != nil && b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.SheetContentType != nil {
					if *a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.SheetContentType != *b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.SheetContentType {
						delta.Add("Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.SheetContentType", a.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.SheetContentType, b.ko.Spec.Definition.AnalysisDefaults.DefaultNewSheetConfiguration.SheetContentType)
					}
				}
			}
		}
		if len(a.ko.Spec.Definition.CalculatedFields) != len(b.ko.Spec.Definition.CalculatedFields) {
			delta.Add("Spec.Definition.CalculatedFields", a.ko.Spec.Definition.CalculatedFields, b.ko.Spec.Definition.CalculatedFields)
		} else if len(a.ko.Spec.Definition.CalculatedFields) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Definition.CalculatedFields, b.ko.Spec.Definition.CalculatedFields) {
				delta.Add("Spec.Definition.CalculatedFields", a.ko.Spec.Definition.CalculatedFields, b.ko.Spec.Definition.CalculatedFields)
			}
		}
		if len(a.ko.Spec.Definition.ColumnConfigurations) != len(b.ko.Spec.Definition.ColumnConfigurations) {
			delta.Add("Spec.Definition.ColumnConfigurations", a.ko.Spec.Definition.ColumnConfigurations, b.ko.Spec.Definition.ColumnConfigurations)
		} else if len(a.ko.Spec.Definition.ColumnConfigurations) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Definition.ColumnConfigurations, b.ko.Spec.Definition.ColumnConfigurations) {
				delta.Add("Spec.Definition.ColumnConfigurations", a.ko.Spec.Definition.ColumnConfigurations, b.ko.Spec.Definition.ColumnConfigurations)
			}
		}
		if len(a.ko.Spec.Definition.DataSetIdentifierDeclarations) != len(b.ko.Spec.Definition.DataSetIdentifierDeclarations) {
			delta.Add("Spec.Definition.DataSetIdentifierDeclarations", a.ko.Spec.Definition.DataSetIdentifierDeclarations, b.ko.Spec.Definition.DataSetIdentifierDeclarations)
		} else if len(a.ko.Spec.Definition.DataSetIdentifierDeclarations) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Definition.DataSetIdentifierDeclarations, b.ko.Spec.Definition.DataSetIdentifierDeclarations) {
				delta.Add("Spec.Definition.DataSetIdentifierDeclarations", a.ko.Spec.Definition.DataSetIdentifierDeclarations, b.ko.Spec.Definition.DataSetIdentifierDeclarations)
			}
		}
		if len(a.ko.Spec.Definition.FilterGroups) != len(b.ko.Spec.Definition.FilterGroups) {
			delta.Add("Spec.Definition.FilterGroups", a.ko.Spec.Definition.FilterGroups, b.ko.Spec.Definition.FilterGroups)
		} else if len(a.ko.Spec.Definition.FilterGroups) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Definition.FilterGroups, b.ko.Spec.Definition.FilterGroups) {
				delta.Add("Spec.Definition.FilterGroups", a.ko.Spec.Definition.FilterGroups, b.ko.Spec.Definition.FilterGroups)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.Definition.Options, b.ko.Spec.Definition.Options) {
			delta.Add("Spec.Definition.Options", a.ko.Spec.Definition.Options, b.ko.Spec.Definition.Options)
		} else if a.ko.Spec.Definition.Options != nil && b.ko.Spec.Definition.Options != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.Definition.Options.Timezone, b.ko.Spec.Definition.Options.Timezone) {
				delta.Add("Spec.Definition.Options.Timezone", a.ko.Spec.Definition.Options.Timezone, b.ko.Spec.Definition.Options.Timezone)
			} else if a.ko.Spec.Definition.Options.Timezone != nil && b.ko.Spec.Definition.Options.Timezone != nil {
				if *a.ko.Spec.Definition.Options.Timezone != *b.ko.Spec.Definition.Options.Timezone {
					delta.Add("Spec.Definition.Options.Timezone", a.ko.Spec.Definition.Options.Timezone, b.ko.Spec.Definition.Options.Timezone)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.Definition.Options.WeekStart, b.ko.Spec.Definition.Options.WeekStart) {
				delta.Add("Spec.Definition.Options.WeekStart", a.ko.Spec.Definition.Options.WeekStart, b.ko.Spec.Definition.Options.WeekStart)
			} else if a.ko.Spec.Definition.Options.WeekStart != nil && b.ko.Spec.Definition.Options.WeekStart != nil {
				if *a.ko.Spec.Definition.Options.WeekStart != *b.ko.Spec.Definition.Options.WeekStart {
					delta.Add("Spec.Definition.Options.WeekStart", a.ko.Spec.Definition.Options.WeekStart, b.ko.Spec.Definition.Options.WeekStart)
				}
			}
		}
		if len(a.ko.Spec.Definition.ParameterDeclarations) != len(b.ko.Spec.Definition.ParameterDeclarations) {
			delta.Add("Spec.Definition.ParameterDeclarations", a.ko.Spec.Definition.ParameterDeclarations, b.ko.Spec.Definition.ParameterDeclarations)
		} else if len(a.ko.Spec.Definition.ParameterDeclarations) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Definition.ParameterDeclarations, b.ko.Spec.Definition.ParameterDeclarations) {
				delta.Add("Spec.Definition.ParameterDeclarations", a.ko.Spec.Definition.ParameterDeclarations, b.ko.Spec.Definition.ParameterDeclarations)
			}
		}
		if len(a.ko.Spec.Definition.Sheets) != len(b.ko.Spec.Definition.Sheets) {
			delta.Add("Spec.Definition.Sheets", a.ko.Spec.Definition.Sheets, b.ko.Spec.Definition.Sheets)
		} else if len(a.ko.Spec.Definition.Sheets) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Definition.Sheets, b.ko.Spec.Definition.Sheets) {
				delta.Add("Spec.Definition.Sheets", a.ko.Spec.Definition.Sheets, b.ko.Spec.Definition.Sheets)
			}
		}
		if len(a.ko.Spec.Definition.StaticFiles) != len(b.ko.Spec.Definition.StaticFiles) {
			delta.Add("Spec.Definition.StaticFiles", a.ko.Spec.Definition.StaticFiles, b.ko.Spec.Definition.StaticFiles)
		} else if len(a.ko.Spec.Definition.StaticFiles) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Definition.StaticFiles, b.ko.Spec.Definition.StaticFiles) {
				delta.Add("Spec.Definition.StaticFiles", a.ko.Spec.Definition.StaticFiles, b.ko.Spec.Definition.StaticFiles)
			}
		}
	}
	if len(a.ko.Spec.FolderARNs) != len(b.ko.Spec.FolderARNs) {
		delta.Add("Spec.FolderARNs", a.ko.Spec.FolderARNs, b.ko.Spec.FolderARNs)
	} else if len(a.ko.Spec.FolderARNs) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.FolderARNs, b.ko.Spec.FolderARNs) {
			delta.Add("Spec.FolderARNs", a.ko.Spec.FolderARNs, b.ko.Spec.FolderARNs)
		}
	}
	if len(a.ko.Spec.LinkEntities) != len(b.ko.Spec.LinkEntities) {
		delta.Add("Spec.LinkEntities", a.ko.Spec.LinkEntities, b.ko.Spec.LinkEntities)
	} else if len(a.ko.Spec.LinkEntities) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.LinkEntities, b.ko.Spec.LinkEntities) {
			delta.Add("Spec.LinkEntities", a.ko.Spec.LinkEntities, b.ko.Spec.LinkEntities)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.LinkSharingConfiguration, b.ko.Spec.LinkSharingConfiguration) {
		delta.Add("Spec.LinkSharingConfiguration", a.ko.Spec.LinkSharingConfiguration, b.ko.Spec.LinkSharingConfiguration)
	} else if a.ko.Spec.LinkSharingConfiguration != nil && b.ko.Spec.LinkSharingConfiguration != nil {
		if len(a.ko.Spec.LinkSharingConfiguration.Permissions) != len(b.ko.Spec.LinkSharingConfiguration.Permissions) {
			delta.Add("Spec.LinkSharingConfiguration.Permissions", a.ko.Spec.LinkSharingConfiguration.Permissions, b.ko.Spec.LinkSharingConfiguration.Permissions)
		} else if len(a.ko.Spec.LinkSharingConfiguration.Permissions) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.LinkSharingConfiguration.Permissions, b.ko.Spec.LinkSharingConfiguration.Permissions) {
				delta.Add("Spec.LinkSharingConfiguration.Permissions", a.ko.Spec.LinkSharingConfiguration.Permissions, b.ko.Spec.LinkSharingConfiguration.Permissions)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Parameters, b.ko.Spec.Parameters) {
		delta.Add("Spec.Parameters", a.ko.Spec.Parameters, b.ko.Spec.Parameters)
	} else if a.ko.Spec.Parameters != nil && b.ko.Spec.Parameters != nil {
		if len(a.ko.Spec.Parameters.DateTimeParameters) != len(b.ko.Spec.Parameters.DateTimeParameters) {
			delta.Add("Spec.Parameters.DateTimeParameters", a.ko.Spec.Parameters.DateTimeParameters, b.ko.Spec.Parameters.DateTimeParameters)
		} else if len(a.ko.Spec.Parameters.DateTimeParameters) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Parameters.DateTimeParameters, b.ko.Spec.Parameters.DateTimeParameters) {
				delta.Add("Spec.Parameters.DateTimeParameters", a.ko.Spec.Parameters.DateTimeParameters, b.ko.Spec.Parameters.DateTimeParameters)
			}
		}
		if len(a.ko.Spec.Parameters.DecimalParameters) != len(b.ko.Spec.Parameters.DecimalParameters) {
			delta.Add("Spec.Parameters.DecimalParameters", a.ko.Spec.Parameters.DecimalParameters, b.ko.Spec.Parameters.DecimalParameters)
		} else if len(a.ko.Spec.Parameters.DecimalParameters) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Parameters.DecimalParameters, b.ko.Spec.Parameters.DecimalParameters) {
				delta.Add("Spec.Parameters.DecimalParameters", a.ko.Spec.Parameters.DecimalParameters, b.ko.Spec.Parameters.DecimalParameters)
			}
		}
		if len(a.ko.Spec.Parameters.IntegerParameters) != len(b.ko.Spec.Parameters.IntegerParameters) {
			delta.Add("Spec.Parameters.IntegerParameters", a.ko.Spec.Parameters.IntegerParameters, b.ko.Spec.Parameters.IntegerParameters)
		} else if len(a.ko.Spec.Parameters.IntegerParameters) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Parameters.IntegerParameters, b.ko.Spec.Parameters.IntegerParameters) {
				delta.Add("Spec.Parameters.IntegerParameters", a.ko.Spec.Parameters.IntegerParameters, b.ko.Spec.Parameters.IntegerParameters)
			}
		}
		if len(a.ko.Spec.Parameters.StringParameters) != len(b.ko.Spec.Parameters.StringParameters) {
			delta.Add("Spec.Parameters.StringParameters", a.ko.Spec.Parameters.StringParameters, b.ko.Spec.Parameters.StringParameters)
		} else if len(a.ko.Spec.Parameters.StringParameters) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Parameters.StringParameters, b.ko.Spec.Parameters.StringParameters) {
				delta.Add("Spec.Parameters.StringParameters", a.ko.Spec.Parameters.StringParameters, b.ko.Spec.Parameters.StringParameters)
			}
		}
	}
	if len(a.ko.Spec.Permissions) != len(b.ko.Spec.Permissions) {
		delta.Add("Spec.Permissions", a.ko.Spec.Permissions, b.ko.Spec.Permissions)
	} else if len(a.ko.Spec.Permissions) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Permissions, b.ko.Spec.Permissions) {
			delta.Add("Spec.Permissions", a.ko.Spec.Permissions, b.ko.Spec.Permissions)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.SourceEntity, b.ko.Spec.SourceEntity) {
		delta.Add("Spec.SourceEntity", a.ko.Spec.SourceEntity, b.ko.Spec.SourceEntity)
	} else if a.ko.Spec.SourceEntity != nil && b.ko.Spec.SourceEntity != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.SourceEntity.SourceTemplate, b.ko.Spec.SourceEntity.SourceTemplate) {
			delta.Add("Spec.SourceEntity.SourceTemplate", a.ko.Spec.SourceEntity.SourceTemplate, b.ko.Spec.SourceEntity.SourceTemplate)
		} else if a.ko.Spec.SourceEntity.SourceTemplate != nil && b.ko.Spec.SourceEntity.SourceTemplate != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.SourceEntity.SourceTemplate.ARN, b.ko.Spec.SourceEntity.SourceTemplate.ARN) {
				delta.Add("Spec.SourceEntity.SourceTemplate.ARN", a.ko.Spec.SourceEntity.SourceTemplate.ARN, b.ko.Spec.SourceEntity.SourceTemplate.ARN)
			} else if a.ko.Spec.SourceEntity.SourceTemplate.ARN != nil && b.ko.Spec.SourceEntity.SourceTemplate.ARN != nil {
				if *a.ko.Spec.SourceEntity.SourceTemplate.ARN != *b.ko.Spec.SourceEntity.SourceTemplate.ARN {
					delta.Add("Spec.SourceEntity.SourceTemplate.ARN", a.ko.Spec.SourceEntity.SourceTemplate.ARN, b.ko.Spec.SourceEntity.SourceTemplate.ARN)
				}
			}
			if len(a.ko.Spec.SourceEntity.SourceTemplate.DataSetReferences) != len(b.ko.Spec.SourceEntity.SourceTemplate.DataSetReferences) {
				delta.Add("Spec.SourceEntity.SourceTemplate.DataSetReferences", a.ko.Spec.SourceEntity.SourceTemplate.DataSetReferences, b.ko.Spec.SourceEntity.SourceTemplate.DataSetReferences)
			} else if len(a.ko.Spec.SourceEntity.SourceTemplate.DataSetReferences) > 0 {
				if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.SourceEntity.SourceTemplate.DataSetReferences, b.ko.Spec.SourceEntity.SourceTemplate.DataSetReferences) {
					delta.Add("Spec.SourceEntity.SourceTemplate.DataSetReferences", a.ko.Spec.SourceEntity.SourceTemplate.DataSetReferences, b.ko.Spec.SourceEntity.SourceTemplate.DataSetReferences)
				}
			}
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ThemeARN, b.ko.Spec.ThemeARN) {
		delta.Add("Spec.ThemeARN", a.ko.Spec.ThemeARN, b.ko.Spec.ThemeARN)
	} else if a.ko.Spec.ThemeARN != nil && b.ko.Spec.ThemeARN != nil {
		if *a.ko.Spec.ThemeARN != *b.ko.Spec.ThemeARN {
			delta.Add("Spec.ThemeARN", a.ko.Spec.ThemeARN, b.ko.Spec.ThemeARN)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ValidationStrategy, b.ko.Spec.ValidationStrategy) {
		delta.Add("Spec.ValidationStrategy", a.ko.Spec.ValidationStrategy, b.ko.Spec.ValidationStrategy)
	} else if a.ko.Spec.ValidationStrategy != nil && b.ko.Spec.ValidationStrategy != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.ValidationStrategy.Mode, b.ko.Spec.ValidationStrategy.Mode) {
			delta.Add("Spec.ValidationStrategy.Mode", a.ko.Spec.ValidationStrategy.Mode, b.ko.Spec.ValidationStrategy.Mode)
		} else if a.ko.Spec.ValidationStrategy.Mode != nil && b.ko.Spec.ValidationStrategy.Mode != nil {
			if *a.ko.Spec.ValidationStrategy.Mode != *b.ko.Spec.ValidationStrategy.Mode {
				delta.Add("Spec.ValidationStrategy.Mode", a.ko.Spec.ValidationStrategy.Mode, b.ko.Spec.ValidationStrategy.Mode)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.VersionDescription, b.ko.Spec.VersionDescription) {
		delta.Add("Spec.VersionDescription", a.ko.Spec.VersionDescription, b.ko.Spec.VersionDescription)
	} else if a.ko.Spec.VersionDescription != nil && b.ko.Spec.VersionDescription != nil {
		if *a.ko.Spec.VersionDescription != *b.ko.Spec.VersionDescription {
			delta.Add("Spec.VersionDescription", a.ko.Spec.VersionDescription, b.ko.Spec.VersionDescription)
		}
	}

	return delta
}
