// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package action_connector

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.ActionConnectorID, b.ko.Spec.ActionConnectorID) {
		delta.Add("Spec.ActionConnectorID", a.ko.Spec.ActionConnectorID, b.ko.Spec.ActionConnectorID)
	} else if a.ko.Spec.ActionConnectorID != nil && b.ko.Spec.ActionConnectorID != nil {
		if *a.ko.Spec.ActionConnectorID != *b.ko.Spec.ActionConnectorID {
			delta.Add("Spec.ActionConnectorID", a.ko.Spec.ActionConnectorID, b.ko.Spec.ActionConnectorID)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.AuthenticationConfig, b.ko.Spec.AuthenticationConfig) {
		delta.Add("Spec.AuthenticationConfig", a.ko.Spec.AuthenticationConfig, b.ko.Spec.AuthenticationConfig)
	} else if a.ko.Spec.AuthenticationConfig != nil && b.ko.Spec.AuthenticationConfig != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.AuthenticationConfig.AuthenticationMetadata, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata) {
			delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata)
		} else if a.ko.Spec.AuthenticationConfig.AuthenticationMetadata != nil && b.ko.Spec.AuthenticationConfig.AuthenticationMetadata != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata) {
				delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata)
			} else if a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata != nil && b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata != nil {
				if ackcompare.HasNilDifference(a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.APIKey, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.APIKey) {
					delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.APIKey", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.APIKey, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.APIKey)
				} else if a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.APIKey != nil && b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.APIKey != nil {
					if *a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.APIKey != *b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.APIKey {
						delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.APIKey", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.APIKey, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.APIKey)
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.BaseEndpoint, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.BaseEndpoint) {
					delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.BaseEndpoint", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.BaseEndpoint, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.BaseEndpoint)
				} else if a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.BaseEndpoint != nil && b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.BaseEndpoint != nil {
					if *a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.BaseEndpoint != *b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.BaseEndpoint {
						delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.BaseEndpoint", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.BaseEndpoint, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.BaseEndpoint)
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.Email, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.Email) {
					delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.Email", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.Email, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.Email)
				} else if a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.Email != nil && b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.Email != nil {
					if *a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.Email != *b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.Email {
						delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.Email", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.Email, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.Email)
					}
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata) {
				delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata)
			} else if a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata != nil && b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata != nil {
				if ackcompare.HasNilDifference(a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails) {
					delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails)
				} else if a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails != nil && b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails != nil {
					if ackcompare.HasNilDifference(a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails) {
						delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails)
					} else if a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails != nil && b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails != nil {
						if ackcompare.HasNilDifference(a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.AuthorizationEndpoint, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.AuthorizationEndpoint) {
							delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.AuthorizationEndpoint", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.AuthorizationEndpoint, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.AuthorizationEndpoint)
						} else if a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.AuthorizationEndpoint != nil && b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.AuthorizationEndpoint != nil {
							if *a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.AuthorizationEndpoint != *b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.AuthorizationEndpoint {
								delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.AuthorizationEndpoint", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.AuthorizationEndpoint, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.AuthorizationEndpoint)
							}
						}
						if ackcompare.HasNilDifference(a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.ClientID, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.ClientID) {
							delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.ClientID", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.ClientID, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.ClientID)
						} else if a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.ClientID != nil && b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.ClientID != nil {
							if *a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.ClientID != *b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.ClientID {
								delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.ClientID", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.ClientID, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.ClientID)
							}
						}
						if ackcompare.HasNilDifference(a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.ClientSecret, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.ClientSecret) {
							delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.ClientSecret", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.ClientSecret, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.ClientSecret)
						} else if a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.ClientSecret != nil && b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.ClientSecret != nil {
							if *a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.ClientSecret != *b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.ClientSecret {
								delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.ClientSecret", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.ClientSecret, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.ClientSecret)
							}
						}
						if ackcompare.HasNilDifference(a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.TokenEndpoint, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.TokenEndpoint) {
							delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.TokenEndpoint", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.TokenEndpoint, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.TokenEndpoint)
						} else if a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.TokenEndpoint != nil && b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.TokenEndpoint != nil {
							if *a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.TokenEndpoint != *b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.TokenEndpoint {
								delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.TokenEndpoint", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.TokenEndpoint, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.TokenEndpoint)
							}
						}
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsSource, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsSource) {
					delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsSource", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsSource, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsSource)
				} else if a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsSource != nil && b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsSource != nil {
					if *a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsSource != *b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsSource {
						delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsSource", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsSource, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsSource)
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.BaseEndpoint, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.BaseEndpoint) {
					delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.BaseEndpoint", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.BaseEndpoint, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.BaseEndpoint)
				} else if a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.BaseEndpoint != nil && b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.BaseEndpoint != nil {
					if *a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.BaseEndpoint != *b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.BaseEndpoint {
						delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.BaseEndpoint", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.BaseEndpoint, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.BaseEndpoint)
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.RedirectURL, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.RedirectURL) {
					delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.RedirectURL", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.RedirectURL, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.RedirectURL)
				} else if a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.RedirectURL != nil && b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.RedirectURL != nil {
					if *a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.RedirectURL != *b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.RedirectURL {
						delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.RedirectURL", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.RedirectURL, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.RedirectURL)
					}
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata) {
				delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata)
			} else if a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata != nil && b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata != nil {
				if ackcompare.HasNilDifference(a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.BaseEndpoint, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.BaseEndpoint) {
					delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.BaseEndpoint", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.BaseEndpoint, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.BaseEndpoint)
				} else if a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.BaseEndpoint != nil && b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.BaseEndpoint != nil {
					if *a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.BaseEndpoint != *b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.BaseEndpoint {
						delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.BaseEndpoint", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.BaseEndpoint, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.BaseEndpoint)
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.Password, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.Password) {
					delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.Password", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.Password, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.Password)
				} else if a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.Password != nil && b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.Password != nil {
					if *a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.Password != *b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.Password {
						delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.Password", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.Password, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.Password)
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.Username, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.Username) {
					delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.Username", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.Username, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.Username)
				} else if a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.Username != nil && b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.Username != nil {
					if *a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.Username != *b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.Username {
						delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.Username", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.Username, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.Username)
					}
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata) {
				delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata)
			} else if a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata != nil && b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata != nil {
				if ackcompare.HasNilDifference(a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.BaseEndpoint, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.BaseEndpoint) {
					delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.BaseEndpoint", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.BaseEndpoint, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.BaseEndpoint)
				} else if a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.BaseEndpoint != nil && b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.BaseEndpoint != nil {
					if *a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.BaseEndpoint != *b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.BaseEndpoint {
						delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.BaseEndpoint", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.BaseEndpoint, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.BaseEndpoint)
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails) {
					delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails)
				} else if a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails != nil && b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails != nil {
					if ackcompare.HasNilDifference(a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails) {
						delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails)
					} else if a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails != nil && b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails != nil {
						if ackcompare.HasNilDifference(a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.ClientID, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.ClientID) {
							delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.ClientID", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.ClientID, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.ClientID)
						} else if a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.ClientID != nil && b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.ClientID != nil {
							if *a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.ClientID != *b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.ClientID {
								delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.ClientID", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.ClientID, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.ClientID)
							}
						}
						if ackcompare.HasNilDifference(a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.ClientSecret, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.ClientSecret) {
							delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.ClientSecret", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.ClientSecret, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.ClientSecret)
						} else if a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.ClientSecret != nil && b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.ClientSecret != nil {
							if *a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.ClientSecret != *b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.ClientSecret {
								delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.ClientSecret", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.ClientSecret, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.ClientSecret)
							}
						}
						if ackcompare.HasNilDifference(a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.TokenEndpoint, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.TokenEndpoint) {
							delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.TokenEndpoint", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.TokenEndpoint, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.TokenEndpoint)
						} else if a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.TokenEndpoint != nil && b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.TokenEndpoint != nil {
							if *a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.TokenEndpoint != *b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.TokenEndpoint {
								delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.TokenEndpoint", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.TokenEndpoint, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.TokenEndpoint)
							}
						}
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsSource, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsSource) {
					delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsSource", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsSource, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsSource)
				} else if a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsSource != nil && b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsSource != nil {
					if *a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsSource != *b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsSource {
						delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsSource", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsSource, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsSource)
					}
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.IAMConnectionMetadata, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.IAMConnectionMetadata) {
				delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.IAMConnectionMetadata", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.IAMConnectionMetadata, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.IAMConnectionMetadata)
			} else if a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.IAMConnectionMetadata != nil && b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.IAMConnectionMetadata != nil {
				if ackcompare.HasNilDifference(a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.IAMConnectionMetadata.RoleARN, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.IAMConnectionMetadata.RoleARN) {
					delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.IAMConnectionMetadata.RoleARN", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.IAMConnectionMetadata.RoleARN, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.IAMConnectionMetadata.RoleARN)
				} else if a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.IAMConnectionMetadata.RoleARN != nil && b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.IAMConnectionMetadata.RoleARN != nil {
					if *a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.IAMConnectionMetadata.RoleARN != *b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.IAMConnectionMetadata.RoleARN {
						delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.IAMConnectionMetadata.RoleARN", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.IAMConnectionMetadata.RoleARN, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.IAMConnectionMetadata.RoleARN)
					}
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.NoneConnectionMetadata, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.NoneConnectionMetadata) {
				delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.NoneConnectionMetadata", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.NoneConnectionMetadata, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.NoneConnectionMetadata)
			} else if a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.NoneConnectionMetadata != nil && b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.NoneConnectionMetadata != nil {
				if ackcompare.HasNilDifference(a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.NoneConnectionMetadata.BaseEndpoint, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.NoneConnectionMetadata.BaseEndpoint) {
					delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.NoneConnectionMetadata.BaseEndpoint", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.NoneConnectionMetadata.BaseEndpoint, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.NoneConnectionMetadata.BaseEndpoint)
				} else if a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.NoneConnectionMetadata.BaseEndpoint != nil && b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.NoneConnectionMetadata.BaseEndpoint != nil {
					if *a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.NoneConnectionMetadata.BaseEndpoint != *b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.NoneConnectionMetadata.BaseEndpoint {
						delta.Add("Spec.AuthenticationConfig.AuthenticationMetadata.NoneConnectionMetadata.BaseEndpoint", a.ko.Spec.AuthenticationConfig.AuthenticationMetadata.NoneConnectionMetadata.BaseEndpoint, b.ko.Spec.AuthenticationConfig.AuthenticationMetadata.NoneConnectionMetadata.BaseEndpoint)
					}
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.AuthenticationConfig.AuthenticationType, b.ko.Spec.AuthenticationConfig.AuthenticationType) {
			delta.Add("Spec.AuthenticationConfig.AuthenticationType", a.ko.Spec.AuthenticationConfig.AuthenticationType, b.ko.Spec.AuthenticationConfig.AuthenticationType)
		} else if a.ko.Spec.AuthenticationConfig.AuthenticationType != nil && b.ko.Spec.AuthenticationConfig.AuthenticationType != nil {
			if *a.ko.Spec.AuthenticationConfig.AuthenticationType != *b.ko.Spec.AuthenticationConfig.AuthenticationType {
				delta.Add("Spec.AuthenticationConfig.AuthenticationType", a.ko.Spec.AuthenticationConfig.AuthenticationType, b.ko.Spec.AuthenticationConfig.AuthenticationType)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.AWSAccountID, b.ko.Spec.AWSAccountID) {
		delta.Add("Spec.AWSAccountID", a.ko.Spec.AWSAccountID, b.ko.Spec.AWSAccountID)
	} else if a.ko.Spec.AWSAccountID != nil && b.ko.Spec.AWSAccountID != nil {
		if *a.ko.Spec.AWSAccountID != *b.ko.Spec.AWSAccountID {
			delta.Add("Spec.AWSAccountID", a.ko.Spec.AWSAccountID, b.ko.Spec.AWSAccountID)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Description, b.ko.Spec.Description) {
		delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
	} else if a.ko.Spec.Description != nil && b.ko.Spec.Description != nil {
		if *a.ko.Spec.Description != *b.ko.Spec.Description {
			delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if len(a.ko.Spec.Permissions) != len(b.ko.Spec.Permissions) {
		delta.Add("Spec.Permissions", a.ko.Spec.Permissions, b.ko.Spec.Permissions)
	} else if len(a.ko.Spec.Permissions) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Permissions, b.ko.Spec.Permissions) {
			delta.Add("Spec.Permissions", a.ko.Spec.Permissions, b.ko.Spec.Permissions)
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Type, b.ko.Spec.Type) {
		delta.Add("Spec.Type", a.ko.Spec.Type, b.ko.Spec.Type)
	} else if a.ko.Spec.Type != nil && b.ko.Spec.Type != nil {
		if *a.ko.Spec.Type != *b.ko.Spec.Type {
			delta.Add("Spec.Type", a.ko.Spec.Type, b.ko.Spec.Type)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.VPCConnectionARN, b.ko.Spec.VPCConnectionARN) {
		delta.Add("Spec.VPCConnectionARN", a.ko.Spec.VPCConnectionARN, b.ko.Spec.VPCConnectionARN)
	} else if a.ko.Spec.VPCConnectionARN != nil && b.ko.Spec.VPCConnectionARN != nil {
		if *a.ko.Spec.VPCConnectionARN != *b.ko.Spec.VPCConnectionARN {
			delta.Add("Spec.VPCConnectionARN", a.ko.Spec.VPCConnectionARN, b.ko.Spec.VPCConnectionARN)
		}
	}

	return delta
}
