// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package action_connector

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/quicksight"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/quicksight/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/quicksight-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.ActionConnector{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.DescribeActionConnectorOutput
	resp, err = rm.sdkapi.DescribeActionConnector(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "DescribeActionConnector", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.RequestId != nil {
		ko.Status.RequestID = resp.RequestId
	} else {
		ko.Status.RequestID = nil
	}
	statusCopy := int64(resp.Status)
	ko.Status.Status = &statusCopy

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Spec.ActionConnectorID == nil || r.ko.Spec.AWSAccountID == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.DescribeActionConnectorInput, error) {
	res := &svcsdk.DescribeActionConnectorInput{}

	if r.ko.Spec.ActionConnectorID != nil {
		res.ActionConnectorId = r.ko.Spec.ActionConnectorID
	}
	if r.ko.Spec.AWSAccountID != nil {
		res.AwsAccountId = r.ko.Spec.AWSAccountID
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateActionConnectorOutput
	_ = resp
	resp, err = rm.sdkapi.CreateActionConnector(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateActionConnector", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.ActionConnectorId != nil {
		ko.Spec.ActionConnectorID = resp.ActionConnectorId
	} else {
		ko.Spec.ActionConnectorID = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.Arn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.Arn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.CreationStatus != "" {
		ko.Status.CreationStatus = aws.String(string(resp.CreationStatus))
	} else {
		ko.Status.CreationStatus = nil
	}
	if resp.RequestId != nil {
		ko.Status.RequestID = resp.RequestId
	} else {
		ko.Status.RequestID = nil
	}
	statusCopy := int64(resp.Status)
	ko.Status.Status = &statusCopy

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateActionConnectorInput, error) {
	res := &svcsdk.CreateActionConnectorInput{}

	if r.ko.Spec.ActionConnectorID != nil {
		res.ActionConnectorId = r.ko.Spec.ActionConnectorID
	}
	if r.ko.Spec.AuthenticationConfig != nil {
		f1 := &svcsdktypes.AuthConfig{}
		if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata != nil {
			var f1f0 svcsdktypes.AuthenticationMetadata
			isInterfaceSet := false
			if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata != nil {
				if isInterfaceSet {
					return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for ApiKeyConnectionMetadata"))
				}
				f1f0f0Parent := &svcsdktypes.AuthenticationMetadataMemberApiKeyConnectionMetadata{}
				f1f0f0 := &svcsdktypes.APIKeyConnectionMetadata{}
				if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.APIKey != nil {
					f1f0f0.ApiKey = r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.APIKey
				}
				if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.BaseEndpoint != nil {
					f1f0f0.BaseEndpoint = r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.BaseEndpoint
				}
				if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.Email != nil {
					f1f0f0.Email = r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.Email
				}
				f1f0f0Parent.Value = *f1f0f0
				f1f0 = f1f0f0Parent
				isInterfaceSet = true
			}
			if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata != nil {
				if isInterfaceSet {
					return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for AuthorizationCodeGrantMetadata"))
				}
				f1f0f1Parent := &svcsdktypes.AuthenticationMetadataMemberAuthorizationCodeGrantMetadata{}
				f1f0f1 := &svcsdktypes.AuthorizationCodeGrantMetadata{}
				if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails != nil {
					var f1f0f1f0 svcsdktypes.AuthorizationCodeGrantCredentialsDetails
					isInterfaceSet := false
					if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails != nil {
						if isInterfaceSet {
							return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for AuthorizationCodeGrantDetails"))
						}
						f1f0f1f0f0Parent := &svcsdktypes.AuthorizationCodeGrantCredentialsDetailsMemberAuthorizationCodeGrantDetails{}
						f1f0f1f0f0 := &svcsdktypes.AuthorizationCodeGrantDetails{}
						if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.AuthorizationEndpoint != nil {
							f1f0f1f0f0.AuthorizationEndpoint = r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.AuthorizationEndpoint
						}
						if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.ClientID != nil {
							f1f0f1f0f0.ClientId = r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.ClientID
						}
						if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.ClientSecret != nil {
							f1f0f1f0f0.ClientSecret = r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.ClientSecret
						}
						if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.TokenEndpoint != nil {
							f1f0f1f0f0.TokenEndpoint = r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.TokenEndpoint
						}
						f1f0f1f0f0Parent.Value = *f1f0f1f0f0
						f1f0f1f0 = f1f0f1f0f0Parent
						isInterfaceSet = true
					}
					f1f0f1.AuthorizationCodeGrantCredentialsDetails = f1f0f1f0
				}
				if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsSource != nil {
					f1f0f1.AuthorizationCodeGrantCredentialsSource = svcsdktypes.AuthorizationCodeGrantCredentialsSource(*r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsSource)
				}
				if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.BaseEndpoint != nil {
					f1f0f1.BaseEndpoint = r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.BaseEndpoint
				}
				if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.RedirectURL != nil {
					f1f0f1.RedirectUrl = r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.RedirectURL
				}
				f1f0f1Parent.Value = *f1f0f1
				f1f0 = f1f0f1Parent
				isInterfaceSet = true
			}
			if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata != nil {
				if isInterfaceSet {
					return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for BasicAuthConnectionMetadata"))
				}
				f1f0f2Parent := &svcsdktypes.AuthenticationMetadataMemberBasicAuthConnectionMetadata{}
				f1f0f2 := &svcsdktypes.BasicAuthConnectionMetadata{}
				if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.BaseEndpoint != nil {
					f1f0f2.BaseEndpoint = r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.BaseEndpoint
				}
				if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.Password != nil {
					f1f0f2.Password = r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.Password
				}
				if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.Username != nil {
					f1f0f2.Username = r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.Username
				}
				f1f0f2Parent.Value = *f1f0f2
				f1f0 = f1f0f2Parent
				isInterfaceSet = true
			}
			if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata != nil {
				if isInterfaceSet {
					return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for ClientCredentialsGrantMetadata"))
				}
				f1f0f3Parent := &svcsdktypes.AuthenticationMetadataMemberClientCredentialsGrantMetadata{}
				f1f0f3 := &svcsdktypes.ClientCredentialsGrantMetadata{}
				if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.BaseEndpoint != nil {
					f1f0f3.BaseEndpoint = r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.BaseEndpoint
				}
				if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails != nil {
					var f1f0f3f1 svcsdktypes.ClientCredentialsDetails
					isInterfaceSet := false
					if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails != nil {
						if isInterfaceSet {
							return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for ClientCredentialsGrantDetails"))
						}
						f1f0f3f1f0Parent := &svcsdktypes.ClientCredentialsDetailsMemberClientCredentialsGrantDetails{}
						f1f0f3f1f0 := &svcsdktypes.ClientCredentialsGrantDetails{}
						if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.ClientID != nil {
							f1f0f3f1f0.ClientId = r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.ClientID
						}
						if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.ClientSecret != nil {
							f1f0f3f1f0.ClientSecret = r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.ClientSecret
						}
						if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.TokenEndpoint != nil {
							f1f0f3f1f0.TokenEndpoint = r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.TokenEndpoint
						}
						f1f0f3f1f0Parent.Value = *f1f0f3f1f0
						f1f0f3f1 = f1f0f3f1f0Parent
						isInterfaceSet = true
					}
					f1f0f3.ClientCredentialsDetails = f1f0f3f1
				}
				if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsSource != nil {
					f1f0f3.ClientCredentialsSource = svcsdktypes.ClientCredentialsSource(*r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsSource)
				}
				f1f0f3Parent.Value = *f1f0f3
				f1f0 = f1f0f3Parent
				isInterfaceSet = true
			}
			if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.IAMConnectionMetadata != nil {
				if isInterfaceSet {
					return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for IamConnectionMetadata"))
				}
				f1f0f4Parent := &svcsdktypes.AuthenticationMetadataMemberIamConnectionMetadata{}
				f1f0f4 := &svcsdktypes.IAMConnectionMetadata{}
				if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.IAMConnectionMetadata.RoleARN != nil {
					f1f0f4.RoleArn = r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.IAMConnectionMetadata.RoleARN
				}
				f1f0f4Parent.Value = *f1f0f4
				f1f0 = f1f0f4Parent
				isInterfaceSet = true
			}
			if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.NoneConnectionMetadata != nil {
				if isInterfaceSet {
					return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for NoneConnectionMetadata"))
				}
				f1f0f5Parent := &svcsdktypes.AuthenticationMetadataMemberNoneConnectionMetadata{}
				f1f0f5 := &svcsdktypes.NoneConnectionMetadata{}
				if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.NoneConnectionMetadata.BaseEndpoint != nil {
					f1f0f5.BaseEndpoint = r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.NoneConnectionMetadata.BaseEndpoint
				}
				f1f0f5Parent.Value = *f1f0f5
				f1f0 = f1f0f5Parent
				isInterfaceSet = true
			}
			f1.AuthenticationMetadata = f1f0
		}
		if r.ko.Spec.AuthenticationConfig.AuthenticationType != nil {
			f1.AuthenticationType = svcsdktypes.ConnectionAuthType(*r.ko.Spec.AuthenticationConfig.AuthenticationType)
		}
		res.AuthenticationConfig = f1
	}
	if r.ko.Spec.AWSAccountID != nil {
		res.AwsAccountId = r.ko.Spec.AWSAccountID
	}
	if r.ko.Spec.Description != nil {
		res.Description = r.ko.Spec.Description
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}
	if r.ko.Spec.Permissions != nil {
		f5 := []svcsdktypes.ResourcePermission{}
		for _, f5iter := range r.ko.Spec.Permissions {
			f5elem := &svcsdktypes.ResourcePermission{}
			if f5iter.Actions != nil {
				f5elem.Actions = aws.ToStringSlice(f5iter.Actions)
			}
			if f5iter.Principal != nil {
				f5elem.Principal = f5iter.Principal
			}
			f5 = append(f5, *f5elem)
		}
		res.Permissions = f5
	}
	if r.ko.Spec.Tags != nil {
		f6 := []svcsdktypes.Tag{}
		for _, f6iter := range r.ko.Spec.Tags {
			f6elem := &svcsdktypes.Tag{}
			if f6iter.Key != nil {
				f6elem.Key = f6iter.Key
			}
			if f6iter.Value != nil {
				f6elem.Value = f6iter.Value
			}
			f6 = append(f6, *f6elem)
		}
		res.Tags = f6
	}
	if r.ko.Spec.Type != nil {
		res.Type = svcsdktypes.ActionConnectorType(*r.ko.Spec.Type)
	}
	if r.ko.Spec.VPCConnectionARN != nil {
		res.VpcConnectionArn = r.ko.Spec.VPCConnectionARN
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.UpdateActionConnectorOutput
	_ = resp
	resp, err = rm.sdkapi.UpdateActionConnector(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "UpdateActionConnector", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.ActionConnectorId != nil {
		ko.Spec.ActionConnectorID = resp.ActionConnectorId
	} else {
		ko.Spec.ActionConnectorID = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.Arn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.Arn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.RequestId != nil {
		ko.Status.RequestID = resp.RequestId
	} else {
		ko.Status.RequestID = nil
	}
	statusCopy := int64(resp.Status)
	ko.Status.Status = &statusCopy

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.UpdateActionConnectorInput, error) {
	res := &svcsdk.UpdateActionConnectorInput{}

	if r.ko.Spec.ActionConnectorID != nil {
		res.ActionConnectorId = r.ko.Spec.ActionConnectorID
	}
	if r.ko.Spec.AuthenticationConfig != nil {
		f1 := &svcsdktypes.AuthConfig{}
		if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata != nil {
			var f1f0 svcsdktypes.AuthenticationMetadata
			isInterfaceSet := false
			if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata != nil {
				if isInterfaceSet {
					return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for ApiKeyConnectionMetadata"))
				}
				f1f0f0Parent := &svcsdktypes.AuthenticationMetadataMemberApiKeyConnectionMetadata{}
				f1f0f0 := &svcsdktypes.APIKeyConnectionMetadata{}
				if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.APIKey != nil {
					f1f0f0.ApiKey = r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.APIKey
				}
				if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.BaseEndpoint != nil {
					f1f0f0.BaseEndpoint = r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.BaseEndpoint
				}
				if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.Email != nil {
					f1f0f0.Email = r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.APIKeyConnectionMetadata.Email
				}
				f1f0f0Parent.Value = *f1f0f0
				f1f0 = f1f0f0Parent
				isInterfaceSet = true
			}
			if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata != nil {
				if isInterfaceSet {
					return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for AuthorizationCodeGrantMetadata"))
				}
				f1f0f1Parent := &svcsdktypes.AuthenticationMetadataMemberAuthorizationCodeGrantMetadata{}
				f1f0f1 := &svcsdktypes.AuthorizationCodeGrantMetadata{}
				if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails != nil {
					var f1f0f1f0 svcsdktypes.AuthorizationCodeGrantCredentialsDetails
					isInterfaceSet := false
					if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails != nil {
						if isInterfaceSet {
							return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for AuthorizationCodeGrantDetails"))
						}
						f1f0f1f0f0Parent := &svcsdktypes.AuthorizationCodeGrantCredentialsDetailsMemberAuthorizationCodeGrantDetails{}
						f1f0f1f0f0 := &svcsdktypes.AuthorizationCodeGrantDetails{}
						if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.AuthorizationEndpoint != nil {
							f1f0f1f0f0.AuthorizationEndpoint = r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.AuthorizationEndpoint
						}
						if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.ClientID != nil {
							f1f0f1f0f0.ClientId = r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.ClientID
						}
						if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.ClientSecret != nil {
							f1f0f1f0f0.ClientSecret = r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.ClientSecret
						}
						if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.TokenEndpoint != nil {
							f1f0f1f0f0.TokenEndpoint = r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsDetails.AuthorizationCodeGrantDetails.TokenEndpoint
						}
						f1f0f1f0f0Parent.Value = *f1f0f1f0f0
						f1f0f1f0 = f1f0f1f0f0Parent
						isInterfaceSet = true
					}
					f1f0f1.AuthorizationCodeGrantCredentialsDetails = f1f0f1f0
				}
				if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsSource != nil {
					f1f0f1.AuthorizationCodeGrantCredentialsSource = svcsdktypes.AuthorizationCodeGrantCredentialsSource(*r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.AuthorizationCodeGrantCredentialsSource)
				}
				if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.BaseEndpoint != nil {
					f1f0f1.BaseEndpoint = r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.BaseEndpoint
				}
				if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.RedirectURL != nil {
					f1f0f1.RedirectUrl = r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.AuthorizationCodeGrantMetadata.RedirectURL
				}
				f1f0f1Parent.Value = *f1f0f1
				f1f0 = f1f0f1Parent
				isInterfaceSet = true
			}
			if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata != nil {
				if isInterfaceSet {
					return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for BasicAuthConnectionMetadata"))
				}
				f1f0f2Parent := &svcsdktypes.AuthenticationMetadataMemberBasicAuthConnectionMetadata{}
				f1f0f2 := &svcsdktypes.BasicAuthConnectionMetadata{}
				if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.BaseEndpoint != nil {
					f1f0f2.BaseEndpoint = r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.BaseEndpoint
				}
				if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.Password != nil {
					f1f0f2.Password = r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.Password
				}
				if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.Username != nil {
					f1f0f2.Username = r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.BasicAuthConnectionMetadata.Username
				}
				f1f0f2Parent.Value = *f1f0f2
				f1f0 = f1f0f2Parent
				isInterfaceSet = true
			}
			if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata != nil {
				if isInterfaceSet {
					return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for ClientCredentialsGrantMetadata"))
				}
				f1f0f3Parent := &svcsdktypes.AuthenticationMetadataMemberClientCredentialsGrantMetadata{}
				f1f0f3 := &svcsdktypes.ClientCredentialsGrantMetadata{}
				if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.BaseEndpoint != nil {
					f1f0f3.BaseEndpoint = r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.BaseEndpoint
				}
				if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails != nil {
					var f1f0f3f1 svcsdktypes.ClientCredentialsDetails
					isInterfaceSet := false
					if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails != nil {
						if isInterfaceSet {
							return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for ClientCredentialsGrantDetails"))
						}
						f1f0f3f1f0Parent := &svcsdktypes.ClientCredentialsDetailsMemberClientCredentialsGrantDetails{}
						f1f0f3f1f0 := &svcsdktypes.ClientCredentialsGrantDetails{}
						if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.ClientID != nil {
							f1f0f3f1f0.ClientId = r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.ClientID
						}
						if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.ClientSecret != nil {
							f1f0f3f1f0.ClientSecret = r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.ClientSecret
						}
						if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.TokenEndpoint != nil {
							f1f0f3f1f0.TokenEndpoint = r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsDetails.ClientCredentialsGrantDetails.TokenEndpoint
						}
						f1f0f3f1f0Parent.Value = *f1f0f3f1f0
						f1f0f3f1 = f1f0f3f1f0Parent
						isInterfaceSet = true
					}
					f1f0f3.ClientCredentialsDetails = f1f0f3f1
				}
				if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsSource != nil {
					f1f0f3.ClientCredentialsSource = svcsdktypes.ClientCredentialsSource(*r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.ClientCredentialsGrantMetadata.ClientCredentialsSource)
				}
				f1f0f3Parent.Value = *f1f0f3
				f1f0 = f1f0f3Parent
				isInterfaceSet = true
			}
			if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.IAMConnectionMetadata != nil {
				if isInterfaceSet {
					return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for IamConnectionMetadata"))
				}
				f1f0f4Parent := &svcsdktypes.AuthenticationMetadataMemberIamConnectionMetadata{}
				f1f0f4 := &svcsdktypes.IAMConnectionMetadata{}
				if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.IAMConnectionMetadata.RoleARN != nil {
					f1f0f4.RoleArn = r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.IAMConnectionMetadata.RoleARN
				}
				f1f0f4Parent.Value = *f1f0f4
				f1f0 = f1f0f4Parent
				isInterfaceSet = true
			}
			if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.NoneConnectionMetadata != nil {
				if isInterfaceSet {
					return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for NoneConnectionMetadata"))
				}
				f1f0f5Parent := &svcsdktypes.AuthenticationMetadataMemberNoneConnectionMetadata{}
				f1f0f5 := &svcsdktypes.NoneConnectionMetadata{}
				if r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.NoneConnectionMetadata.BaseEndpoint != nil {
					f1f0f5.BaseEndpoint = r.ko.Spec.AuthenticationConfig.AuthenticationMetadata.NoneConnectionMetadata.BaseEndpoint
				}
				f1f0f5Parent.Value = *f1f0f5
				f1f0 = f1f0f5Parent
				isInterfaceSet = true
			}
			f1.AuthenticationMetadata = f1f0
		}
		if r.ko.Spec.AuthenticationConfig.AuthenticationType != nil {
			f1.AuthenticationType = svcsdktypes.ConnectionAuthType(*r.ko.Spec.AuthenticationConfig.AuthenticationType)
		}
		res.AuthenticationConfig = f1
	}
	if r.ko.Spec.AWSAccountID != nil {
		res.AwsAccountId = r.ko.Spec.AWSAccountID
	}
	if r.ko.Spec.Description != nil {
		res.Description = r.ko.Spec.Description
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}
	if r.ko.Spec.VPCConnectionARN != nil {
		res.VpcConnectionArn = r.ko.Spec.VPCConnectionARN
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteActionConnectorOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteActionConnector(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteActionConnector", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteActionConnectorInput, error) {
	res := &svcsdk.DeleteActionConnectorInput{}

	if r.ko.Spec.ActionConnectorID != nil {
		res.ActionConnectorId = r.ko.Spec.ActionConnectorID
	}
	if r.ko.Spec.AWSAccountID != nil {
		res.AwsAccountId = r.ko.Spec.AWSAccountID
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.ActionConnector,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	// No terminal_errors specified for this resource in generator config
	return false
}
