// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package brand

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.AWSAccountID, b.ko.Spec.AWSAccountID) {
		delta.Add("Spec.AWSAccountID", a.ko.Spec.AWSAccountID, b.ko.Spec.AWSAccountID)
	} else if a.ko.Spec.AWSAccountID != nil && b.ko.Spec.AWSAccountID != nil {
		if *a.ko.Spec.AWSAccountID != *b.ko.Spec.AWSAccountID {
			delta.Add("Spec.AWSAccountID", a.ko.Spec.AWSAccountID, b.ko.Spec.AWSAccountID)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition, b.ko.Spec.BrandDefinition) {
		delta.Add("Spec.BrandDefinition", a.ko.Spec.BrandDefinition, b.ko.Spec.BrandDefinition)
	} else if a.ko.Spec.BrandDefinition != nil && b.ko.Spec.BrandDefinition != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme, b.ko.Spec.BrandDefinition.ApplicationTheme) {
			delta.Add("Spec.BrandDefinition.ApplicationTheme", a.ko.Spec.BrandDefinition.ApplicationTheme, b.ko.Spec.BrandDefinition.ApplicationTheme)
		} else if a.ko.Spec.BrandDefinition.ApplicationTheme != nil && b.ko.Spec.BrandDefinition.ApplicationTheme != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette) {
				delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette)
			} else if a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette != nil {
				if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Accent, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Accent) {
					delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Accent", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Accent, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Accent)
				} else if a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Accent != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Accent != nil {
					if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Accent.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Accent.Background) {
						delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Accent.Background", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Accent.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Accent.Background)
					} else if a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Accent.Background != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Accent.Background != nil {
						if *a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Accent.Background != *b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Accent.Background {
							delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Accent.Background", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Accent.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Accent.Background)
						}
					}
					if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Accent.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Accent.Foreground) {
						delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Accent.Foreground", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Accent.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Accent.Foreground)
					} else if a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Accent.Foreground != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Accent.Foreground != nil {
						if *a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Accent.Foreground != *b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Accent.Foreground {
							delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Accent.Foreground", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Accent.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Accent.Foreground)
						}
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Danger, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Danger) {
					delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Danger", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Danger, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Danger)
				} else if a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Danger != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Danger != nil {
					if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Danger.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Danger.Background) {
						delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Danger.Background", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Danger.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Danger.Background)
					} else if a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Danger.Background != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Danger.Background != nil {
						if *a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Danger.Background != *b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Danger.Background {
							delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Danger.Background", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Danger.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Danger.Background)
						}
					}
					if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Danger.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Danger.Foreground) {
						delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Danger.Foreground", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Danger.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Danger.Foreground)
					} else if a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Danger.Foreground != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Danger.Foreground != nil {
						if *a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Danger.Foreground != *b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Danger.Foreground {
							delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Danger.Foreground", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Danger.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Danger.Foreground)
						}
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Dimension, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Dimension) {
					delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Dimension", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Dimension, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Dimension)
				} else if a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Dimension != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Dimension != nil {
					if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Dimension.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Dimension.Background) {
						delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Dimension.Background", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Dimension.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Dimension.Background)
					} else if a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Dimension.Background != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Dimension.Background != nil {
						if *a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Dimension.Background != *b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Dimension.Background {
							delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Dimension.Background", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Dimension.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Dimension.Background)
						}
					}
					if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Dimension.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Dimension.Foreground) {
						delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Dimension.Foreground", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Dimension.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Dimension.Foreground)
					} else if a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Dimension.Foreground != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Dimension.Foreground != nil {
						if *a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Dimension.Foreground != *b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Dimension.Foreground {
							delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Dimension.Foreground", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Dimension.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Dimension.Foreground)
						}
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Info, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Info) {
					delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Info", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Info, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Info)
				} else if a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Info != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Info != nil {
					if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Info.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Info.Background) {
						delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Info.Background", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Info.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Info.Background)
					} else if a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Info.Background != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Info.Background != nil {
						if *a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Info.Background != *b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Info.Background {
							delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Info.Background", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Info.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Info.Background)
						}
					}
					if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Info.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Info.Foreground) {
						delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Info.Foreground", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Info.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Info.Foreground)
					} else if a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Info.Foreground != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Info.Foreground != nil {
						if *a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Info.Foreground != *b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Info.Foreground {
							delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Info.Foreground", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Info.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Info.Foreground)
						}
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Measure, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Measure) {
					delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Measure", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Measure, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Measure)
				} else if a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Measure != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Measure != nil {
					if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Measure.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Measure.Background) {
						delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Measure.Background", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Measure.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Measure.Background)
					} else if a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Measure.Background != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Measure.Background != nil {
						if *a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Measure.Background != *b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Measure.Background {
							delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Measure.Background", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Measure.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Measure.Background)
						}
					}
					if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Measure.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Measure.Foreground) {
						delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Measure.Foreground", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Measure.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Measure.Foreground)
					} else if a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Measure.Foreground != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Measure.Foreground != nil {
						if *a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Measure.Foreground != *b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Measure.Foreground {
							delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Measure.Foreground", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Measure.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Measure.Foreground)
						}
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Primary, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Primary) {
					delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Primary", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Primary, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Primary)
				} else if a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Primary != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Primary != nil {
					if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Primary.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Primary.Background) {
						delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Primary.Background", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Primary.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Primary.Background)
					} else if a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Primary.Background != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Primary.Background != nil {
						if *a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Primary.Background != *b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Primary.Background {
							delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Primary.Background", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Primary.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Primary.Background)
						}
					}
					if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Primary.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Primary.Foreground) {
						delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Primary.Foreground", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Primary.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Primary.Foreground)
					} else if a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Primary.Foreground != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Primary.Foreground != nil {
						if *a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Primary.Foreground != *b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Primary.Foreground {
							delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Primary.Foreground", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Primary.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Primary.Foreground)
						}
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Secondary, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Secondary) {
					delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Secondary", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Secondary, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Secondary)
				} else if a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Secondary != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Secondary != nil {
					if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Secondary.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Secondary.Background) {
						delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Secondary.Background", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Secondary.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Secondary.Background)
					} else if a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Secondary.Background != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Secondary.Background != nil {
						if *a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Secondary.Background != *b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Secondary.Background {
							delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Secondary.Background", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Secondary.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Secondary.Background)
						}
					}
					if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Secondary.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Secondary.Foreground) {
						delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Secondary.Foreground", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Secondary.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Secondary.Foreground)
					} else if a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Secondary.Foreground != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Secondary.Foreground != nil {
						if *a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Secondary.Foreground != *b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Secondary.Foreground {
							delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Secondary.Foreground", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Secondary.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Secondary.Foreground)
						}
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Success, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Success) {
					delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Success", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Success, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Success)
				} else if a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Success != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Success != nil {
					if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Success.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Success.Background) {
						delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Success.Background", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Success.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Success.Background)
					} else if a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Success.Background != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Success.Background != nil {
						if *a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Success.Background != *b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Success.Background {
							delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Success.Background", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Success.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Success.Background)
						}
					}
					if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Success.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Success.Foreground) {
						delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Success.Foreground", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Success.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Success.Foreground)
					} else if a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Success.Foreground != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Success.Foreground != nil {
						if *a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Success.Foreground != *b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Success.Foreground {
							delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Success.Foreground", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Success.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Success.Foreground)
						}
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Warning, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Warning) {
					delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Warning", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Warning, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Warning)
				} else if a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Warning != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Warning != nil {
					if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Warning.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Warning.Background) {
						delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Warning.Background", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Warning.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Warning.Background)
					} else if a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Warning.Background != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Warning.Background != nil {
						if *a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Warning.Background != *b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Warning.Background {
							delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Warning.Background", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Warning.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Warning.Background)
						}
					}
					if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Warning.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Warning.Foreground) {
						delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Warning.Foreground", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Warning.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Warning.Foreground)
					} else if a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Warning.Foreground != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Warning.Foreground != nil {
						if *a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Warning.Foreground != *b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Warning.Foreground {
							delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Warning.Foreground", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Warning.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandColorPalette.Warning.Foreground)
						}
					}
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle) {
				delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandElementStyle", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle)
			} else if a.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle != nil {
				if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle) {
					delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle)
				} else if a.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle != nil {
					if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.ContextualNavbar, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.ContextualNavbar) {
						delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.ContextualNavbar", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.ContextualNavbar, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.ContextualNavbar)
					} else if a.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.ContextualNavbar != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.ContextualNavbar != nil {
						if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.ContextualNavbar.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.ContextualNavbar.Background) {
							delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.ContextualNavbar.Background", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.ContextualNavbar.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.ContextualNavbar.Background)
						} else if a.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.ContextualNavbar.Background != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.ContextualNavbar.Background != nil {
							if *a.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.ContextualNavbar.Background != *b.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.ContextualNavbar.Background {
								delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.ContextualNavbar.Background", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.ContextualNavbar.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.ContextualNavbar.Background)
							}
						}
						if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.ContextualNavbar.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.ContextualNavbar.Foreground) {
							delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.ContextualNavbar.Foreground", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.ContextualNavbar.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.ContextualNavbar.Foreground)
						} else if a.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.ContextualNavbar.Foreground != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.ContextualNavbar.Foreground != nil {
							if *a.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.ContextualNavbar.Foreground != *b.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.ContextualNavbar.Foreground {
								delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.ContextualNavbar.Foreground", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.ContextualNavbar.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.ContextualNavbar.Foreground)
							}
						}
					}
					if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.GlobalNavbar, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.GlobalNavbar) {
						delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.GlobalNavbar", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.GlobalNavbar, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.GlobalNavbar)
					} else if a.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.GlobalNavbar != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.GlobalNavbar != nil {
						if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.GlobalNavbar.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.GlobalNavbar.Background) {
							delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.GlobalNavbar.Background", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.GlobalNavbar.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.GlobalNavbar.Background)
						} else if a.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.GlobalNavbar.Background != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.GlobalNavbar.Background != nil {
							if *a.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.GlobalNavbar.Background != *b.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.GlobalNavbar.Background {
								delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.GlobalNavbar.Background", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.GlobalNavbar.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.GlobalNavbar.Background)
							}
						}
						if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.GlobalNavbar.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.GlobalNavbar.Foreground) {
							delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.GlobalNavbar.Foreground", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.GlobalNavbar.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.GlobalNavbar.Foreground)
						} else if a.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.GlobalNavbar.Foreground != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.GlobalNavbar.Foreground != nil {
							if *a.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.GlobalNavbar.Foreground != *b.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.GlobalNavbar.Foreground {
								delta.Add("Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.GlobalNavbar.Foreground", a.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.GlobalNavbar.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.BrandElementStyle.NavbarStyle.GlobalNavbar.Foreground)
							}
						}
					}
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette, b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette) {
				delta.Add("Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette", a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette, b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette)
			} else if a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette != nil {
				if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Automation, b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Automation) {
					delta.Add("Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Automation", a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Automation, b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Automation)
				} else if a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Automation != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Automation != nil {
					if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Automation.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Automation.Background) {
						delta.Add("Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Automation.Background", a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Automation.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Automation.Background)
					} else if a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Automation.Background != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Automation.Background != nil {
						if *a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Automation.Background != *b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Automation.Background {
							delta.Add("Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Automation.Background", a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Automation.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Automation.Background)
						}
					}
					if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Automation.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Automation.Foreground) {
						delta.Add("Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Automation.Foreground", a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Automation.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Automation.Foreground)
					} else if a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Automation.Foreground != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Automation.Foreground != nil {
						if *a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Automation.Foreground != *b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Automation.Foreground {
							delta.Add("Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Automation.Foreground", a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Automation.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Automation.Foreground)
						}
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Connection, b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Connection) {
					delta.Add("Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Connection", a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Connection, b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Connection)
				} else if a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Connection != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Connection != nil {
					if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Connection.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Connection.Background) {
						delta.Add("Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Connection.Background", a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Connection.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Connection.Background)
					} else if a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Connection.Background != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Connection.Background != nil {
						if *a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Connection.Background != *b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Connection.Background {
							delta.Add("Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Connection.Background", a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Connection.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Connection.Background)
						}
					}
					if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Connection.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Connection.Foreground) {
						delta.Add("Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Connection.Foreground", a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Connection.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Connection.Foreground)
					} else if a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Connection.Foreground != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Connection.Foreground != nil {
						if *a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Connection.Foreground != *b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Connection.Foreground {
							delta.Add("Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Connection.Foreground", a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Connection.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Connection.Foreground)
						}
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Insight, b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Insight) {
					delta.Add("Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Insight", a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Insight, b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Insight)
				} else if a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Insight != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Insight != nil {
					if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Insight.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Insight.Background) {
						delta.Add("Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Insight.Background", a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Insight.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Insight.Background)
					} else if a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Insight.Background != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Insight.Background != nil {
						if *a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Insight.Background != *b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Insight.Background {
							delta.Add("Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Insight.Background", a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Insight.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Insight.Background)
						}
					}
					if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Insight.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Insight.Foreground) {
						delta.Add("Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Insight.Foreground", a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Insight.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Insight.Foreground)
					} else if a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Insight.Foreground != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Insight.Foreground != nil {
						if *a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Insight.Foreground != *b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Insight.Foreground {
							delta.Add("Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Insight.Foreground", a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Insight.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Insight.Foreground)
						}
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Visualization, b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Visualization) {
					delta.Add("Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Visualization", a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Visualization, b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Visualization)
				} else if a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Visualization != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Visualization != nil {
					if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Visualization.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Visualization.Background) {
						delta.Add("Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Visualization.Background", a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Visualization.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Visualization.Background)
					} else if a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Visualization.Background != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Visualization.Background != nil {
						if *a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Visualization.Background != *b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Visualization.Background {
							delta.Add("Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Visualization.Background", a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Visualization.Background, b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Visualization.Background)
						}
					}
					if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Visualization.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Visualization.Foreground) {
						delta.Add("Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Visualization.Foreground", a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Visualization.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Visualization.Foreground)
					} else if a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Visualization.Foreground != nil && b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Visualization.Foreground != nil {
						if *a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Visualization.Foreground != *b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Visualization.Foreground {
							delta.Add("Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Visualization.Foreground", a.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Visualization.Foreground, b.ko.Spec.BrandDefinition.ApplicationTheme.ContextualAccentPalette.Visualization.Foreground)
						}
					}
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.BrandName, b.ko.Spec.BrandDefinition.BrandName) {
			delta.Add("Spec.BrandDefinition.BrandName", a.ko.Spec.BrandDefinition.BrandName, b.ko.Spec.BrandDefinition.BrandName)
		} else if a.ko.Spec.BrandDefinition.BrandName != nil && b.ko.Spec.BrandDefinition.BrandName != nil {
			if *a.ko.Spec.BrandDefinition.BrandName != *b.ko.Spec.BrandDefinition.BrandName {
				delta.Add("Spec.BrandDefinition.BrandName", a.ko.Spec.BrandDefinition.BrandName, b.ko.Spec.BrandDefinition.BrandName)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.Description, b.ko.Spec.BrandDefinition.Description) {
			delta.Add("Spec.BrandDefinition.Description", a.ko.Spec.BrandDefinition.Description, b.ko.Spec.BrandDefinition.Description)
		} else if a.ko.Spec.BrandDefinition.Description != nil && b.ko.Spec.BrandDefinition.Description != nil {
			if *a.ko.Spec.BrandDefinition.Description != *b.ko.Spec.BrandDefinition.Description {
				delta.Add("Spec.BrandDefinition.Description", a.ko.Spec.BrandDefinition.Description, b.ko.Spec.BrandDefinition.Description)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.LogoConfiguration, b.ko.Spec.BrandDefinition.LogoConfiguration) {
			delta.Add("Spec.BrandDefinition.LogoConfiguration", a.ko.Spec.BrandDefinition.LogoConfiguration, b.ko.Spec.BrandDefinition.LogoConfiguration)
		} else if a.ko.Spec.BrandDefinition.LogoConfiguration != nil && b.ko.Spec.BrandDefinition.LogoConfiguration != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.LogoConfiguration.AltText, b.ko.Spec.BrandDefinition.LogoConfiguration.AltText) {
				delta.Add("Spec.BrandDefinition.LogoConfiguration.AltText", a.ko.Spec.BrandDefinition.LogoConfiguration.AltText, b.ko.Spec.BrandDefinition.LogoConfiguration.AltText)
			} else if a.ko.Spec.BrandDefinition.LogoConfiguration.AltText != nil && b.ko.Spec.BrandDefinition.LogoConfiguration.AltText != nil {
				if *a.ko.Spec.BrandDefinition.LogoConfiguration.AltText != *b.ko.Spec.BrandDefinition.LogoConfiguration.AltText {
					delta.Add("Spec.BrandDefinition.LogoConfiguration.AltText", a.ko.Spec.BrandDefinition.LogoConfiguration.AltText, b.ko.Spec.BrandDefinition.LogoConfiguration.AltText)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet, b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet) {
				delta.Add("Spec.BrandDefinition.LogoConfiguration.LogoSet", a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet, b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet)
			} else if a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet != nil && b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet != nil {
				if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon, b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon) {
					delta.Add("Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon", a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon, b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon)
				} else if a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon != nil && b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon != nil {
					if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original, b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original) {
						delta.Add("Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original", a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original, b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original)
					} else if a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original != nil && b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original != nil {
						if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original.Source, b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original.Source) {
							delta.Add("Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original.Source", a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original.Source, b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original.Source)
						} else if a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original.Source != nil && b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original.Source != nil {
							if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original.Source.PublicURL, b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original.Source.PublicURL) {
								delta.Add("Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original.Source.PublicURL", a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original.Source.PublicURL, b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original.Source.PublicURL)
							} else if a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original.Source.PublicURL != nil && b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original.Source.PublicURL != nil {
								if *a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original.Source.PublicURL != *b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original.Source.PublicURL {
									delta.Add("Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original.Source.PublicURL", a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original.Source.PublicURL, b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original.Source.PublicURL)
								}
							}
							if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original.Source.S3URI, b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original.Source.S3URI) {
								delta.Add("Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original.Source.S3URI", a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original.Source.S3URI, b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original.Source.S3URI)
							} else if a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original.Source.S3URI != nil && b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original.Source.S3URI != nil {
								if *a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original.Source.S3URI != *b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original.Source.S3URI {
									delta.Add("Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original.Source.S3URI", a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original.Source.S3URI, b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Favicon.Original.Source.S3URI)
								}
							}
						}
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary, b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary) {
					delta.Add("Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary", a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary, b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary)
				} else if a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary != nil && b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary != nil {
					if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original, b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original) {
						delta.Add("Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original", a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original, b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original)
					} else if a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original != nil && b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original != nil {
						if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original.Source, b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original.Source) {
							delta.Add("Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original.Source", a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original.Source, b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original.Source)
						} else if a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original.Source != nil && b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original.Source != nil {
							if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original.Source.PublicURL, b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original.Source.PublicURL) {
								delta.Add("Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original.Source.PublicURL", a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original.Source.PublicURL, b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original.Source.PublicURL)
							} else if a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original.Source.PublicURL != nil && b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original.Source.PublicURL != nil {
								if *a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original.Source.PublicURL != *b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original.Source.PublicURL {
									delta.Add("Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original.Source.PublicURL", a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original.Source.PublicURL, b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original.Source.PublicURL)
								}
							}
							if ackcompare.HasNilDifference(a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original.Source.S3URI, b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original.Source.S3URI) {
								delta.Add("Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original.Source.S3URI", a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original.Source.S3URI, b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original.Source.S3URI)
							} else if a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original.Source.S3URI != nil && b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original.Source.S3URI != nil {
								if *a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original.Source.S3URI != *b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original.Source.S3URI {
									delta.Add("Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original.Source.S3URI", a.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original.Source.S3URI, b.ko.Spec.BrandDefinition.LogoConfiguration.LogoSet.Primary.Original.Source.S3URI)
								}
							}
						}
					}
				}
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.BrandID, b.ko.Spec.BrandID) {
		delta.Add("Spec.BrandID", a.ko.Spec.BrandID, b.ko.Spec.BrandID)
	} else if a.ko.Spec.BrandID != nil && b.ko.Spec.BrandID != nil {
		if *a.ko.Spec.BrandID != *b.ko.Spec.BrandID {
			delta.Add("Spec.BrandID", a.ko.Spec.BrandID, b.ko.Spec.BrandID)
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}

	return delta
}
