// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ActionConnectorSpec defines the desired state of ActionConnector.
//
// Contains detailed information about an action connector, including its configuration,
// status, and enabled actions.
type ActionConnectorSpec struct {

	// A unique identifier for the action connector. This ID must be unique within
	// the Amazon Web Services account. The ActionConnectorId must not start with
	// the prefix quicksuite-
	//
	// Regex Pattern: `^[\w\-]+$`
	// +kubebuilder:validation:Required
	ActionConnectorID *string `json:"actionConnectorID"`
	// The authentication configuration for connecting to the external service.
	// This includes the authentication type, base URL, and authentication metadata
	// such as client credentials or API keys.
	// +kubebuilder:validation:Required
	AuthenticationConfig *AuthConfig `json:"authenticationConfig"`
	// The Amazon Web Services account ID associated with the action connector.
	//
	// Regex Pattern: `^[0-9]{12}$`
	// +kubebuilder:validation:Required
	AWSAccountID *string `json:"awsAccountID"`
	// An optional description of the action connector.
	//
	// Regex Pattern: `^[A-Za-z0-9 _.,!?-]*$`
	Description *string `json:"description,omitempty"`
	// A descriptive name for the action connector.
	//
	// Regex Pattern: `^[A-Za-z0-9](?:[\w- ]*[A-Za-z0-9])?$`
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// The permissions configuration that defines which users, groups, or namespaces
	// can access this action connector and what operations they can perform.
	Permissions []*ResourcePermission `json:"permissions,omitempty"`
	// A list of tags to apply to the action connector for resource management and
	// organization.
	Tags []*Tag `json:"tags,omitempty"`
	// The type of action connector.
	// +kubebuilder:validation:Required
	Type *string `json:"type_"`
	// The ARN of the VPC connection to use for secure connectivity to the external
	// service.
	VPCConnectionARN *string `json:"vpcConnectionARN,omitempty"`
}

// ActionConnectorStatus defines the observed state of ActionConnector
type ActionConnectorStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The creation status of the action connector.
	// +kubebuilder:validation:Optional
	CreationStatus *string `json:"creationStatus,omitempty"`
	// The Amazon Web Services request ID for this operation.
	// +kubebuilder:validation:Optional
	RequestID *string `json:"requestID,omitempty"`
	// The HTTP status code of the request.
	// +kubebuilder:validation:Optional
	Status *int64 `json:"status,omitempty"`
}

// ActionConnector is the Schema for the ActionConnectors API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type ActionConnector struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ActionConnectorSpec   `json:"spec,omitempty"`
	Status            ActionConnectorStatus `json:"status,omitempty"`
}

// ActionConnectorList contains a list of ActionConnector
// +kubebuilder:object:root=true
type ActionConnectorList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ActionConnector `json:"items"`
}

func init() {
	SchemeBuilder.Register(&ActionConnector{}, &ActionConnectorList{})
}
