// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AnalysisSpec defines the desired state of Analysis.
//
// Metadata structure for an analysis in Amazon QuickSight
type AnalysisSpec struct {

	// The ID for the analysis that you're creating. This ID displays in the URL
	// of the analysis.
	//
	// Regex Pattern: `^[\w\-]+$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	AnalysisID *string `json:"analysisID"`
	// The ID of the Amazon Web Services account where you are creating an analysis.
	//
	// Regex Pattern: `^[0-9]{12}$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	AWSAccountID *string `json:"awsAccountID"`
	// The definition of an analysis.
	//
	// A definition is the data model of all features in a Dashboard, Template,
	// or Analysis.
	//
	// Either a SourceEntity or a Definition must be provided in order for the request
	// to be valid.
	Definition *AnalysisDefinition `json:"definition,omitempty"`
	// When you create the analysis, Amazon QuickSight adds the analysis to these
	// folders.
	FolderARNs []*string `json:"folderARNs,omitempty"`
	// A descriptive name for the analysis that you're creating. This name displays
	// for the analysis in the Amazon QuickSight console.
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// The parameter names and override values that you want to use. An analysis
	// can have any parameter type, and some parameters might accept multiple values.
	Parameters *Parameters `json:"parameters,omitempty"`
	// A structure that describes the principals and the resource-level permissions
	// on an analysis. You can use the Permissions structure to grant permissions
	// by providing a list of Identity and Access Management (IAM) action information
	// for each principal listed by Amazon Resource Name (ARN).
	//
	// To specify no permissions, omit Permissions.
	Permissions []*ResourcePermission `json:"permissions,omitempty"`
	// A source entity to use for the analysis that you're creating. This metadata
	// structure contains details that describe a source template and one or more
	// datasets.
	//
	// Either a SourceEntity or a Definition must be provided in order for the request
	// to be valid.
	SourceEntity *AnalysisSourceEntity `json:"sourceEntity,omitempty"`
	// Contains a map of the key-value pairs for the resource tag or tags assigned
	// to the analysis.
	Tags []*Tag `json:"tags,omitempty"`
	// The ARN for the theme to apply to the analysis that you're creating. To see
	// the theme in the Amazon QuickSight console, make sure that you have access
	// to it.
	ThemeARN *string                                  `json:"themeARN,omitempty"`
	ThemeRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"themeRef,omitempty"`
	// The option to relax the validation needed to create an analysis with definition
	// objects. This skips the validation step for specific errors.
	ValidationStrategy *ValidationStrategy `json:"validationStrategy,omitempty"`
}

// AnalysisStatus defines the observed state of Analysis
type AnalysisStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The status of the creation of the analysis.
	// +kubebuilder:validation:Optional
	CreationStatus *string `json:"creationStatus,omitempty"`
	// The Amazon Web Services request ID for this operation.
	// +kubebuilder:validation:Optional
	RequestID *string `json:"requestID,omitempty"`
	// The HTTP status of the request.
	// +kubebuilder:validation:Optional
	Status *int64 `json:"status,omitempty"`
}

// Analysis is the Schema for the Analyses API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type Analysis struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              AnalysisSpec   `json:"spec,omitempty"`
	Status            AnalysisStatus `json:"status,omitempty"`
}

// AnalysisList contains a list of Analysis
// +kubebuilder:object:root=true
type AnalysisList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Analysis `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Analysis{}, &AnalysisList{})
}
