// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// BrandSpec defines the desired state of Brand.
type BrandSpec struct {

	// The ID of the Amazon Web Services account that owns the brand.
	//
	// Regex Pattern: `^[0-9]{12}$`
	// +kubebuilder:validation:Required
	AWSAccountID *string `json:"awsAccountID"`
	// The definition of the brand.
	BrandDefinition *BrandDefinition `json:"brandDefinition,omitempty"`
	// The ID of the Quick Suite brand.
	//
	// Regex Pattern: `^[\w\-]+$`
	// +kubebuilder:validation:Required
	BrandID *string `json:"brandID"`
	// A map of the key-value pairs that are assigned to the brand.
	Tags []*Tag `json:"tags,omitempty"`
}

// BrandStatus defines the observed state of Brand
type BrandStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The details of the brand.
	// +kubebuilder:validation:Optional
	BrandDetail *BrandDetail `json:"brandDetail,omitempty"`
	// The Amazon Web Services request ID for this operation.
	// +kubebuilder:validation:Optional
	RequestID *string `json:"requestID,omitempty"`
}

// Brand is the Schema for the Brands API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type Brand struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              BrandSpec   `json:"spec,omitempty"`
	Status            BrandStatus `json:"status,omitempty"`
}

// BrandList contains a list of Brand
// +kubebuilder:object:root=true
type BrandList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Brand `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Brand{}, &BrandList{})
}
