// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DashboardSpec defines the desired state of Dashboard.
//
// Dashboard.
type DashboardSpec struct {

	// The ID of the Amazon Web Services account where you want to create the dashboard.
	//
	// Regex Pattern: `^[0-9]{12}$`
	// +kubebuilder:validation:Required
	AWSAccountID *string `json:"awsAccountID"`
	// The ID for the dashboard, also added to the IAM policy.
	//
	// Regex Pattern: `^[\w\-]+$`
	// +kubebuilder:validation:Required
	DashboardID *string `json:"dashboardID"`
	// Options for publishing the dashboard when you create it:
	//
	//   - AvailabilityStatus for AdHocFilteringOption - This status can be either
	//     ENABLED or DISABLED. When this is set to DISABLED, Amazon QuickSight disables
	//     the left filter pane on the published dashboard, which can be used for
	//     ad hoc (one-time) filtering. This option is ENABLED by default.
	//
	//   - AvailabilityStatus for ExportToCSVOption - This status can be either
	//     ENABLED or DISABLED. The visual option to export data to .CSV format isn't
	//     enabled when this is set to DISABLED. This option is ENABLED by default.
	//
	//   - VisibilityState for SheetControlsOption - This visibility state can
	//     be either COLLAPSED or EXPANDED. This option is COLLAPSED by default.
	DashboardPublishOptions *DashboardPublishOptions `json:"dashboardPublishOptions,omitempty"`
	// The definition of a dashboard.
	//
	// A definition is the data model of all features in a Dashboard, Template,
	// or Analysis.
	//
	// Either a SourceEntity or a Definition must be provided in order for the request
	// to be valid.
	Definition *DashboardVersionDefinition `json:"definition,omitempty"`
	// When you create the dashboard, Amazon QuickSight adds the dashboard to these
	// folders.
	FolderARNs []*string `json:"folderARNs,omitempty"`
	// A list of analysis Amazon Resource Names (ARNs) to be linked to the dashboard.
	LinkEntities []*string `json:"linkEntities,omitempty"`
	// A structure that contains the permissions of a shareable link to the dashboard.
	LinkSharingConfiguration *LinkSharingConfiguration `json:"linkSharingConfiguration,omitempty"`
	// The display name of the dashboard.
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// The parameters for the creation of the dashboard, which you want to use to
	// override the default settings. A dashboard can have any type of parameters,
	// and some parameters might accept multiple values.
	Parameters *Parameters `json:"parameters,omitempty"`
	// A structure that contains the permissions of the dashboard. You can use this
	// structure for granting permissions by providing a list of IAM action information
	// for each principal ARN.
	//
	// To specify no permissions, omit the permissions list.
	Permissions []*ResourcePermission `json:"permissions,omitempty"`
	// The entity that you are using as a source when you create the dashboard.
	// In SourceEntity, you specify the type of object you're using as source. You
	// can only create a dashboard from a template, so you use a SourceTemplate
	// entity. If you need to create a dashboard from an analysis, first convert
	// the analysis to a template by using the CreateTemplate (https://docs.aws.amazon.com/quicksight/latest/APIReference/API_CreateTemplate.html)
	// API operation. For SourceTemplate, specify the Amazon Resource Name (ARN)
	// of the source template. The SourceTemplateARN can contain any Amazon Web
	// Services account and any Amazon QuickSight-supported Amazon Web Services
	// Region.
	//
	// Use the DataSetReferences entity within SourceTemplate to list the replacement
	// datasets for the placeholders listed in the original. The schema in each
	// dataset must match its placeholder.
	//
	// Either a SourceEntity or a Definition must be provided in order for the request
	// to be valid.
	SourceEntity *DashboardSourceEntity `json:"sourceEntity,omitempty"`
	// Contains a map of the key-value pairs for the resource tag or tags assigned
	// to the dashboard.
	Tags []*Tag `json:"tags,omitempty"`
	// The Amazon Resource Name (ARN) of the theme that is being used for this dashboard.
	// If you add a value for this field, it overrides the value that is used in
	// the source entity. The theme ARN must exist in the same Amazon Web Services
	// account where you create the dashboard.
	ThemeARN *string `json:"themeARN,omitempty"`
	// The option to relax the validation needed to create a dashboard with definition
	// objects. This option skips the validation step for specific errors.
	ValidationStrategy *ValidationStrategy `json:"validationStrategy,omitempty"`
	// A description for the first version of the dashboard being created.
	VersionDescription *string `json:"versionDescription,omitempty"`
}

// DashboardStatus defines the observed state of Dashboard
type DashboardStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The status of the dashboard creation request.
	// +kubebuilder:validation:Optional
	CreationStatus *string `json:"creationStatus,omitempty"`
	// The Amazon Web Services request ID for this operation.
	// +kubebuilder:validation:Optional
	RequestID *string `json:"requestID,omitempty"`
	// The HTTP status of the request.
	// +kubebuilder:validation:Optional
	Status *int64 `json:"status,omitempty"`
	// The ARN of the dashboard, including the version number of the first version
	// that is created.
	// +kubebuilder:validation:Optional
	VersionARN *string `json:"versionARN,omitempty"`
}

// Dashboard is the Schema for the Dashboards API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type Dashboard struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              DashboardSpec   `json:"spec,omitempty"`
	Status            DashboardStatus `json:"status,omitempty"`
}

// DashboardList contains a list of Dashboard
// +kubebuilder:object:root=true
type DashboardList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Dashboard `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Dashboard{}, &DashboardList{})
}
