// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DataSetSpec defines the desired state of DataSet.
//
// Dataset.
type DataSetSpec struct {

	// The Amazon Web Services account ID.
	//
	// Regex Pattern: `^[0-9]{12}$`
	// +kubebuilder:validation:Required
	AWSAccountID *string `json:"awsAccountID"`
	// Groupings of columns that work together in certain Amazon Quick Sight features.
	// Currently, only geospatial hierarchy is supported.
	ColumnGroups []*ColumnGroup `json:"columnGroups,omitempty"`
	// A set of one or more definitions of a ColumnLevelPermissionRule (https://docs.aws.amazon.com/quicksight/latest/APIReference/API_ColumnLevelPermissionRule.html) .
	ColumnLevelPermissionRules []*ColumnLevelPermissionRule `json:"columnLevelPermissionRules,omitempty"`
	// The data preparation configuration for the dataset. This configuration defines
	// the source tables, transformation steps, and destination tables used to prepare
	// the data. Required when using the new data preparation experience.
	DataPrepConfiguration *DataPrepConfiguration `json:"dataPrepConfiguration,omitempty"`
	// The folder that contains fields and nested subfolders for your dataset.
	FieldFolders map[string]*FieldFolder `json:"fieldFolders,omitempty"`
	// When you create the dataset, Amazon Quick Sight adds the dataset to these
	// folders.
	FolderARNs []*string `json:"folderARNs,omitempty"`
	// An ID for the dataset that you want to create. This ID is unique per Amazon
	// Web Services Region for each Amazon Web Services account.
	// +kubebuilder:validation:Required
	ID *string `json:"id"`
	// Indicates whether you want to import the data into SPICE.
	// +kubebuilder:validation:Required
	ImportMode *string `json:"importMode"`
	// Configures the combination and transformation of the data from the physical
	// tables. This parameter is used with the legacy data preparation experience.
	LogicalTableMap map[string]*LogicalTable `json:"logicalTableMap,omitempty"`
	// The display name for the dataset.
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// The parameter declarations of the dataset.
	Parameters []*DatasetParameter `json:"parameters,omitempty"`
	// The configuration for the performance optimization of the dataset that contains
	// a UniqueKey configuration.
	PerformanceConfiguration *PerformanceConfiguration `json:"performanceConfiguration,omitempty"`
	// A list of resource permissions on the dataset.
	Permissions []*ResourcePermission `json:"permissions,omitempty"`
	// Declares the physical tables that are available in the underlying data sources.
	// +kubebuilder:validation:Required
	PhysicalTableMap map[string]*PhysicalTable `json:"physicalTableMap"`
	// The row-level security configuration for the data that you want to create.
	// This parameter is used with the legacy data preparation experience.
	RowLevelPermissionDataSet *RowLevelPermissionDataSet `json:"rowLevelPermissionDataSet,omitempty"`
	// The configuration of tags on a dataset to set row-level security. Row-level
	// security tags are currently supported for anonymous embedding only. This
	// parameter is used with the legacy data preparation experience.
	RowLevelPermissionTagConfiguration *RowLevelPermissionTagConfiguration `json:"rowLevelPermissionTagConfiguration,omitempty"`
	// The semantic model configuration for the dataset. This configuration defines
	// how the prepared data is structured for an analysis, including table mappings
	// and row-level security configurations. Required when using the new data preparation
	// experience.
	SemanticModelConfiguration *SemanticModelConfiguration `json:"semanticModelConfiguration,omitempty"`
	// Contains a map of the key-value pairs for the resource tag or tags assigned
	// to the dataset.
	Tags               []*Tag                     `json:"tags,omitempty"`
	UsageConfiguration *DataSetUsageConfiguration `json:"usageConfiguration,omitempty"`
	// The usage of the dataset. RLS_RULES must be specified for RLS permission
	// datasets.
	UseAs *string `json:"useAs,omitempty"`
}

// DataSetStatus defines the observed state of DataSet
type DataSetStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The amount of SPICE capacity used by this dataset. This is 0 if the dataset
	// isn't imported into SPICE.
	// +kubebuilder:validation:Optional
	ConsumedSpiceCapacityInBytes *int64 `json:"consumedSpiceCapacityInBytes,omitempty"`
	// The time that this dataset was created.
	// +kubebuilder:validation:Optional
	CreatedTime *metav1.Time `json:"createdTime,omitempty"`
	// The ARN for the ingestion, which is triggered as a result of dataset creation
	// if the import mode is SPICE.
	// +kubebuilder:validation:Optional
	IngestionARN *string `json:"ingestionARN,omitempty"`
	// The ID of the ingestion, which is triggered as a result of dataset creation
	// if the import mode is SPICE.
	// +kubebuilder:validation:Optional
	IngestionID *string `json:"ingestionID,omitempty"`
	// The last time that this dataset was updated.
	// +kubebuilder:validation:Optional
	LastUpdatedTime *metav1.Time `json:"lastUpdatedTime,omitempty"`
	// The list of columns after all transforms. These columns are available in
	// templates, analyses, and dashboards.
	// +kubebuilder:validation:Optional
	OutputColumns []*OutputColumn `json:"outputColumns,omitempty"`
}

// DataSet is the Schema for the DataSets API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type DataSet struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              DataSetSpec   `json:"spec,omitempty"`
	Status            DataSetStatus `json:"status,omitempty"`
}

// DataSetList contains a list of DataSet
// +kubebuilder:object:root=true
type DataSetList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DataSet `json:"items"`
}

func init() {
	SchemeBuilder.Register(&DataSet{}, &DataSetList{})
}
