// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DataSetSpec defines the desired state of DataSet.
//
// Dataset.
type DataSetSpec struct {

// The Amazon Web Services account ID.
//
// Regex Pattern: `^[0-9]{12}$`
// +kubebuilder:validation:Required
AWSAccountID *string `json:"awsAccountID"`
// Groupings of columns that work together in certain Amazon QuickSight features.
// Currently, only geospatial hierarchy is supported.
ColumnGroups []*ColumnGroup `json:"columnGroups,omitempty"`
// A set of one or more definitions of a ColumnLevelPermissionRule (https://docs.aws.amazon.com/quicksight/latest/APIReference/API_ColumnLevelPermissionRule.html) .
ColumnLevelPermissionRules []*ColumnLevelPermissionRule `json:"columnLevelPermissionRules,omitempty"`
// An ID for the dataset that you want to create. This ID is unique per Amazon
// Web Services Region for each Amazon Web Services account.
// +kubebuilder:validation:Required
DataSetID *string `json:"dataSetID"`
DataSetUsageConfiguration *DataSetUsageConfiguration `json:"dataSetUsageConfiguration,omitempty"`
// The parameter declarations of the dataset.
DatasetParameters []*DatasetParameter `json:"datasetParameters,omitempty"`
// The folder that contains fields and nested subfolders for your dataset.
FieldFolders map[string]*FieldFolder `json:"fieldFolders,omitempty"`
// When you create the dataset, Amazon QuickSight adds the dataset to these
// folders.
FolderARNs []*string `json:"folderARNs,omitempty"`
// Indicates whether you want to import the data into SPICE.
// +kubebuilder:validation:Required
ImportMode *string `json:"importMode"`
// Configures the combination and transformation of the data from the physical
// tables.
LogicalTableMap map[string]*LogicalTable `json:"logicalTableMap,omitempty"`
// The display name for the dataset.
// +kubebuilder:validation:Required
Name *string `json:"name"`
// A list of resource permissions on the dataset.
Permissions []*ResourcePermission `json:"permissions,omitempty"`
// Declares the physical tables that are available in the underlying data sources.
// +kubebuilder:validation:Required
PhysicalTableMap map[string]*PhysicalTable `json:"physicalTableMap"`
// The row-level security configuration for the data that you want to create.
RowLevelPermissionDataSet *RowLevelPermissionDataSet `json:"rowLevelPermissionDataSet,omitempty"`
// The configuration of tags on a dataset to set row-level security. Row-level
// security tags are currently supported for anonymous embedding only.
RowLevelPermissionTagConfiguration *RowLevelPermissionTagConfiguration `json:"rowLevelPermissionTagConfiguration,omitempty"`
// Contains a map of the key-value pairs for the resource tag or tags assigned
// to the dataset.
Tags []*Tag `json:"tags,omitempty"`
}

// DataSetStatus defines the observed state of DataSet
type DataSetStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The ARN for the ingestion, which is triggered as a result of dataset creation
// if the import mode is SPICE.
	// +kubebuilder:validation:Optional
	IngestionARN *string `json:"ingestionARN,omitempty"`
	// The ID of the ingestion, which is triggered as a result of dataset creation
// if the import mode is SPICE.
	// +kubebuilder:validation:Optional
	IngestionID *string `json:"ingestionID,omitempty"`
	// The Amazon Web Services request ID for this operation.
	// +kubebuilder:validation:Optional
	RequestID *string `json:"requestID,omitempty"`
	// The HTTP status of the request.
	// +kubebuilder:validation:Optional
	Status *int64 `json:"status,omitempty"`
}

// DataSet is the Schema for the DataSets API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type DataSet struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec   DataSetSpec   `json:"spec,omitempty"`
	Status DataSetStatus `json:"status,omitempty"`
}

// DataSetList contains a list of DataSet
// +kubebuilder:object:root=true
type DataSetList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items []DataSet `json:"items"`
}

func init() {
	SchemeBuilder.Register(&DataSet{}, &DataSetList{})
}