// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	"github.com/aws/aws-sdk-go/aws"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = &aws.JSONValue{}
	_ = ackv1alpha1.AWSAccountID("")
)

// Configuration for API key-based authentication to external services.
type APIKeyConnectionMetadata struct {
	APIKey       *string `json:"apiKey,omitempty"`
	BaseEndpoint *string `json:"baseEndpoint,omitempty"`
	Email        *string `json:"email,omitempty"`
}

// The Quick Sight customizations associated with your Amazon Web Services account
// or a Quick Sight namespace in a specific Amazon Web Services Region.
type AccountCustomization struct {
	DefaultEmailCustomizationTemplate *string `json:"defaultEmailCustomizationTemplate,omitempty"`
	DefaultTheme                      *string `json:"defaultTheme,omitempty"`
}

// A structure that contains the following account information elements:
//
//   - Your Quick Sight account name.
//
//   - The edition of Quick Sight that your account is using.
//
//   - The notification email address that is associated with the Quick Sight
//     account.
//
//   - The authentication type of the Quick Sight account.
//
//   - The status of the Quick Sight account's subscription.
type AccountInfo struct {
	AccountName                  *string `json:"accountName,omitempty"`
	AccountSubscriptionStatus    *string `json:"accountSubscriptionStatus,omitempty"`
	AuthenticationType           *string `json:"authenticationType,omitempty"`
	IAMIdentityCenterInstanceARN *string `json:"iamIdentityCenterInstanceARN,omitempty"`
	NotificationEmail            *string `json:"notificationEmail,omitempty"`
}

// The Quick Sight settings associated with your Amazon Web Services account.
type AccountSettings struct {
	AccountName       *string `json:"accountName,omitempty"`
	NotificationEmail *string `json:"notificationEmail,omitempty"`
}

// Contains error information for an action connector that is in an error state.
type ActionConnectorError struct {
	Message *string `json:"message,omitempty"`
	Type    *string `json:"type_,omitempty"`
}

// A filter used to search for action connectors based on specific criteria.
type ActionConnectorSearchFilter struct {
	Value *string `json:"value,omitempty"`
}

// Contains summary information about an action connector, used in list and
// search operations.
type ActionConnectorSummary struct {
	ActionConnectorID *string      `json:"actionConnectorID,omitempty"`
	ARN               *string      `json:"arn,omitempty"`
	CreatedTime       *metav1.Time `json:"createdTime,omitempty"`
	// Contains error information for an action connector that is in an error state.
	Error           *ActionConnectorError `json:"error,omitempty"`
	LastUpdatedTime *metav1.Time          `json:"lastUpdatedTime,omitempty"`
	Name            *string               `json:"name,omitempty"`
	Status          *string               `json:"status,omitempty"`
	Type            *string               `json:"type_,omitempty"`
}

// Contains detailed information about an action connector, including its configuration,
// status, and enabled actions.
type ActionConnector_SDK struct {
	ActionConnectorID *string `json:"actionConnectorID,omitempty"`
	ARN               *string `json:"arn,omitempty"`
	// Read-only authentication configuration containing non-sensitive authentication
	// details for action connectors.
	AuthenticationConfig *ReadAuthConfig `json:"authenticationConfig,omitempty"`
	CreatedTime          *metav1.Time    `json:"createdTime,omitempty"`
	Description          *string         `json:"description,omitempty"`
	EnabledActions       []*string       `json:"enabledActions,omitempty"`
	// Contains error information for an action connector that is in an error state.
	Error            *ActionConnectorError `json:"error,omitempty"`
	LastUpdatedTime  *metav1.Time          `json:"lastUpdatedTime,omitempty"`
	Name             *string               `json:"name,omitempty"`
	Status           *string               `json:"status,omitempty"`
	Type             *string               `json:"type_,omitempty"`
	VPCConnectionARN *string               `json:"vpcConnectionARN,omitempty"`
}

// The active Identity and Access Management (IAM) policy assignment.
type ActiveIAMPolicyAssignment struct {
	PolicyARN *string `json:"policyARN,omitempty"`
}

// Metadata structure for an analysis in Quick Sight
type Analysis struct {
	AnalysisID      *string      `json:"analysisID,omitempty"`
	ARN             *string      `json:"arn,omitempty"`
	CreatedTime     *metav1.Time `json:"createdTime,omitempty"`
	LastUpdatedTime *metav1.Time `json:"lastUpdatedTime,omitempty"`
	Status          *string      `json:"status,omitempty"`
	ThemeARN        *string      `json:"themeARN,omitempty"`
}

// A filter that you apply when searching for one or more analyses.
type AnalysisSearchFilter struct {
	Value *string `json:"value,omitempty"`
}

// The source template of an analysis.
type AnalysisSourceTemplate struct {
	ARN *string `json:"arn,omitempty"`
}

// The summary metadata that describes an analysis.
type AnalysisSummary struct {
	AnalysisID      *string      `json:"analysisID,omitempty"`
	ARN             *string      `json:"arn,omitempty"`
	CreatedTime     *metav1.Time `json:"createdTime,omitempty"`
	LastUpdatedTime *metav1.Time `json:"lastUpdatedTime,omitempty"`
	Status          *string      `json:"status,omitempty"`
}

// Information about the dashboard that you want to embed.
type AnonymousUserDashboardEmbeddingConfiguration struct {
	InitialDashboardID *string `json:"initialDashboardID,omitempty"`
}

// The application theme.
type ApplicationTheme struct {
	// The color palette.
	BrandColorPalette *BrandColorPalette `json:"brandColorPalette,omitempty"`
	// The element style.
	BrandElementStyle *BrandElementStyle `json:"brandElementStyle,omitempty"`
	// The contextual accent palette.
	ContextualAccentPalette *ContextualAccentPalette `json:"contextualAccentPalette,omitempty"`
}

// Controls how a specific Analysis resource is parameterized in the returned
// CloudFormation template.
type AssetBundleExportJobAnalysisOverrideProperties struct {
	ARN *string `json:"arn,omitempty"`
}

// Controls how a specific Dashboard resource is parameterized in the returned
// CloudFormation template.
type AssetBundleExportJobDashboardOverrideProperties struct {
	ARN *string `json:"arn,omitempty"`
}

// Controls how a specific DataSet resource is parameterized in the returned
// CloudFormation template.
type AssetBundleExportJobDataSetOverrideProperties struct {
	ARN *string `json:"arn,omitempty"`
}

// Controls how a specific DataSource resource is parameterized in the returned
// CloudFormation template.
type AssetBundleExportJobDataSourceOverrideProperties struct {
	ARN *string `json:"arn,omitempty"`
}

// Describes an error that occurred during an Asset Bundle export job.
type AssetBundleExportJobError struct {
	ARN *string `json:"arn,omitempty"`
}

// Controls how a specific Folder resource is parameterized in the returned
// CloudFormation template.
type AssetBundleExportJobFolderOverrideProperties struct {
	ARN *string `json:"arn,omitempty"`
}

// Controls how a specific RefreshSchedule resource is parameterized in the
// returned CloudFormation template.
type AssetBundleExportJobRefreshScheduleOverrideProperties struct {
	ARN *string `json:"arn,omitempty"`
}

// A summary of the export job that includes details of the job's configuration
// and its current status.
type AssetBundleExportJobSummary struct {
	ARN                    *string      `json:"arn,omitempty"`
	AssetBundleExportJobID *string      `json:"assetBundleExportJobID,omitempty"`
	CreatedTime            *metav1.Time `json:"createdTime,omitempty"`
}

// Controls how a specific Theme resource is parameterized in the returned CloudFormation
// template.
type AssetBundleExportJobThemeOverrideProperties struct {
	ARN *string `json:"arn,omitempty"`
}

// Controls how a specific VPCConnection resource is parameterized in the outputted
// CloudFormation template.
type AssetBundleExportJobVPCConnectionOverrideProperties struct {
	ARN *string `json:"arn,omitempty"`
}

// Describes a warning that occurred during an Asset Bundle export job.
type AssetBundleExportJobWarning struct {
	ARN *string `json:"arn,omitempty"`
}

// An object that contains a list of tags to be assigned to a list of analysis
// IDs.
type AssetBundleImportJobAnalysisOverrideTags struct {
	Tags []*Tag `json:"tags,omitempty"`
}

// An object that contains a list of tags to be assigned to a list of dashboard
// IDs.
type AssetBundleImportJobDashboardOverrideTags struct {
	Tags []*Tag `json:"tags,omitempty"`
}

// An object that contains a list of tags to be assigned to a list of dataset
// IDs.
type AssetBundleImportJobDataSetOverrideTags struct {
	Tags []*Tag `json:"tags,omitempty"`
}

// An object that contains a list of tags to be assigned to a list of data source
// IDs.
type AssetBundleImportJobDataSourceOverrideTags struct {
	Tags []*Tag `json:"tags,omitempty"`
}

// Describes an error that occurred within an Asset Bundle import execution.
type AssetBundleImportJobError struct {
	ARN *string `json:"arn,omitempty"`
}

// The override parameters for a single folder that is being imported.
type AssetBundleImportJobFolderOverrideParameters struct {
	ParentFolderARN *string `json:"parentFolderARN,omitempty"`
}

// An object that contains a list of tags to be assigned to a list of folder
// IDs.
type AssetBundleImportJobFolderOverrideTags struct {
	Tags []*Tag `json:"tags,omitempty"`
}

// A list of overrides for a specific RefreshsSchedule resource that is present
// in the asset bundle that is imported.
type AssetBundleImportJobRefreshScheduleOverrideParameters struct {
	ScheduleID         *string      `json:"scheduleID,omitempty"`
	StartAfterDateTime *metav1.Time `json:"startAfterDateTime,omitempty"`
}

// An optional structure that configures resource ID overrides for the import
// job.
type AssetBundleImportJobResourceIDOverrideConfiguration struct {
	PrefixForAllResources *string `json:"prefixForAllResources,omitempty"`
}

// A summary of the import job that includes details of the requested job's
// configuration and its current status.
type AssetBundleImportJobSummary struct {
	ARN                    *string      `json:"arn,omitempty"`
	AssetBundleImportJobID *string      `json:"assetBundleImportJobID,omitempty"`
	CreatedTime            *metav1.Time `json:"createdTime,omitempty"`
}

// An object that contains a list of tags to be assigned to a list of theme
// IDs.
type AssetBundleImportJobThemeOverrideTags struct {
	Tags []*Tag `json:"tags,omitempty"`
}

// The override parameters for a single VPC connection that is imported.
type AssetBundleImportJobVPCConnectionOverrideParameters struct {
	RoleARN *string `json:"roleARN,omitempty"`
}

// An object that contains a list of tags to be assigned to a list of VPC connection
// IDs.
type AssetBundleImportJobVPCConnectionOverrideTags struct {
	Tags []*Tag `json:"tags,omitempty"`
}

// Describes a warning that occurred during an Asset Bundle import job.
type AssetBundleImportJobWarning struct {
	ARN *string `json:"arn,omitempty"`
}

// A structure that contains the permissions for the resource that you want
// to override in an asset bundle import job.
type AssetBundleResourcePermissions struct {
	Actions []*string `json:"actions,omitempty"`
}

// An array of analysis level configurations.
type AssetOptions struct {
	Timezone *string `json:"timezone,omitempty"`
}

// Parameters for Amazon Athena.
type AthenaParameters struct {
	RoleARN *string `json:"roleARN,omitempty"`
}

// Aggregation for attributes.
type AttributeAggregationFunction struct {
	ValueForMultipleValues *string `json:"valueForMultipleValues,omitempty"`
}

// Authentication configuration for connecting to external services.
type AuthConfig struct {
	// Union type containing authentication metadata for different authentication
	// methods.
	AuthenticationMetadata *AuthenticationMetadata `json:"authenticationMetadata,omitempty"`
	AuthenticationType     *string                 `json:"authenticationType,omitempty"`
}

// Union type containing authentication metadata for different authentication
// methods.
type AuthenticationMetadata struct {
	// Configuration for API key-based authentication to external services.
	APIKeyConnectionMetadata *APIKeyConnectionMetadata `json:"apiKeyConnectionMetadata,omitempty"`
	// Metadata for OAuth 2.0 authorization code grant authentication.
	AuthorizationCodeGrantMetadata *AuthorizationCodeGrantMetadata `json:"authorizationCodeGrantMetadata,omitempty"`
	// Metadata for basic authentication using username and password.
	BasicAuthConnectionMetadata *BasicAuthConnectionMetadata `json:"basicAuthConnectionMetadata,omitempty"`
	// Configuration for OAuth 2.0 client credentials grant authentication, including
	// client ID, client secret, token endpoint, and optional scopes.
	ClientCredentialsGrantMetadata *ClientCredentialsGrantMetadata `json:"clientCredentialsGrantMetadata,omitempty"`
	// Authentication metadata for IAM-based connections, used for first-party Amazon
	// Web Services service integrations.
	IAMConnectionMetadata *IAMConnectionMetadata `json:"iamConnectionMetadata,omitempty"`
	// Authentication metadata for connections that do not require authentication
	// credentials.
	NoneConnectionMetadata *NoneConnectionMetadata `json:"noneConnectionMetadata,omitempty"`
}

// Details for OAuth 2.0 authorization code grant credentials.
type AuthorizationCodeGrantCredentialsDetails struct {
	// Configuration details for OAuth 2.0 authorization code grant flow.
	AuthorizationCodeGrantDetails *AuthorizationCodeGrantDetails `json:"authorizationCodeGrantDetails,omitempty"`
}

// Configuration details for OAuth 2.0 authorization code grant flow.
type AuthorizationCodeGrantDetails struct {
	AuthorizationEndpoint *string `json:"authorizationEndpoint,omitempty"`
	ClientID              *string `json:"clientID,omitempty"`
	ClientSecret          *string `json:"clientSecret,omitempty"`
	TokenEndpoint         *string `json:"tokenEndpoint,omitempty"`
}

// Metadata for OAuth 2.0 authorization code grant authentication.
type AuthorizationCodeGrantMetadata struct {
	// Details for OAuth 2.0 authorization code grant credentials.
	AuthorizationCodeGrantCredentialsDetails *AuthorizationCodeGrantCredentialsDetails `json:"authorizationCodeGrantCredentialsDetails,omitempty"`
	AuthorizationCodeGrantCredentialsSource  *string                                   `json:"authorizationCodeGrantCredentialsSource,omitempty"`
	BaseEndpoint                             *string                                   `json:"baseEndpoint,omitempty"`
	RedirectURL                              *string                                   `json:"redirectURL,omitempty"`
}

// The label options for a chart axis. You must specify the field that the label
// is targeted to.
type AxisLabelOptions struct {
	CustomLabel *string `json:"customLabel,omitempty"`
}

// A bar chart.
//
// The BarChartVisual structure describes a visual that is a member of the bar
// chart family. The following charts can be described using this structure:
//
//   - Horizontal bar chart
//
//   - Vertical bar chart
//
//   - Horizontal stacked bar chart
//
//   - Vertical stacked bar chart
//
//   - Horizontal stacked 100% bar chart
//
//   - Vertical stacked 100% bar chart
//
// For more information, see Using bar charts (https://docs.aws.amazon.com/quicksight/latest/user/bar-charts.html)
// in the Amazon Quick Suite User Guide.
type BarChartVisual struct {
	VisualID *string `json:"visualID,omitempty"`
}

// Metadata for basic authentication using username and password.
type BasicAuthConnectionMetadata struct {
	BaseEndpoint *string `json:"baseEndpoint,omitempty"`
	Password     *string `json:"password,omitempty"`
	Username     *string `json:"username,omitempty"`
}

// The configuration of a body section.
type BodySectionConfiguration struct {
	SectionID *string `json:"sectionID,omitempty"`
}

// A box plot.
//
// For more information, see Using box plots (https://docs.aws.amazon.com/quicksight/latest/user/box-plots.html)
// in the Amazon Quick Suite User Guide.
type BoxPlotVisual struct {
	VisualID *string `json:"visualID,omitempty"`
}

// The color palette.
type BrandColorPalette struct {
	// The color palette.
	Accent *Palette `json:"accent,omitempty"`
	// The color palette.
	Danger *Palette `json:"danger,omitempty"`
	// The color palette.
	Dimension *Palette `json:"dimension,omitempty"`
	// The color palette.
	Info *Palette `json:"info,omitempty"`
	// The color palette.
	Measure *Palette `json:"measure,omitempty"`
	// The color palette.
	Primary *Palette `json:"primary,omitempty"`
	// The color palette.
	Secondary *Palette `json:"secondary,omitempty"`
	// The color palette.
	Success *Palette `json:"success,omitempty"`
	// The color palette.
	Warning *Palette `json:"warning,omitempty"`
}

// The definition of the brand.
type BrandDefinition struct {
	// The application theme.
	ApplicationTheme *ApplicationTheme `json:"applicationTheme,omitempty"`
	BrandName        *string           `json:"brandName,omitempty"`
	Description      *string           `json:"description,omitempty"`
	// The logo configuration.
	LogoConfiguration *LogoConfiguration `json:"logoConfiguration,omitempty"`
}

// The details of the brand.
type BrandDetail struct {
	ARN             *string      `json:"arn,omitempty"`
	BrandID         *string      `json:"brandID,omitempty"`
	BrandStatus     *string      `json:"brandStatus,omitempty"`
	CreatedTime     *metav1.Time `json:"createdTime,omitempty"`
	Errors          []*string    `json:"errors,omitempty"`
	LastUpdatedTime *metav1.Time `json:"lastUpdatedTime,omitempty"`
	// The logo configuration.
	Logo          *Logo   `json:"logo,omitempty"`
	VersionID     *string `json:"versionID,omitempty"`
	VersionStatus *string `json:"versionStatus,omitempty"`
}

// The element style.
type BrandElementStyle struct {
	// The navigation bar style.
	NavbarStyle *NavbarStyle `json:"navbarStyle,omitempty"`
}

// A summary of the brand.
type BrandSummary struct {
	ARN             *string      `json:"arn,omitempty"`
	BrandID         *string      `json:"brandID,omitempty"`
	BrandName       *string      `json:"brandName,omitempty"`
	BrandStatus     *string      `json:"brandStatus,omitempty"`
	CreatedTime     *metav1.Time `json:"createdTime,omitempty"`
	Description     *string      `json:"description,omitempty"`
	LastUpdatedTime *metav1.Time `json:"lastUpdatedTime,omitempty"`
}

// The source controls that are used in a CascadingControlConfiguration.
type CascadingControlSource struct {
	SourceSheetControlID *string `json:"sourceSheetControlID,omitempty"`
}

// A CategoryFilter filters text values.
//
// For more information, see Adding text filters (https://docs.aws.amazon.com/quicksight/latest/user/add-a-text-filter-data-prep.html)
// in the Amazon Quick Suite User Guide.
type CategoryFilter struct {
	FilterID *string `json:"filterID,omitempty"`
}

// Details for OAuth 2.0 client credentials grant authentication.
type ClientCredentialsDetails struct {
	// Configuration details for OAuth2 client credentials grant flow, including
	// client ID, client secret, token endpoint, and optional scopes.
	ClientCredentialsGrantDetails *ClientCredentialsGrantDetails `json:"clientCredentialsGrantDetails,omitempty"`
}

// Configuration details for OAuth2 client credentials grant flow, including
// client ID, client secret, token endpoint, and optional scopes.
type ClientCredentialsGrantDetails struct {
	ClientID      *string `json:"clientID,omitempty"`
	ClientSecret  *string `json:"clientSecret,omitempty"`
	TokenEndpoint *string `json:"tokenEndpoint,omitempty"`
}

// Configuration for OAuth 2.0 client credentials grant authentication, including
// client ID, client secret, token endpoint, and optional scopes.
type ClientCredentialsGrantMetadata struct {
	BaseEndpoint *string `json:"baseEndpoint,omitempty"`
	// Details for OAuth 2.0 client credentials grant authentication.
	ClientCredentialsDetails *ClientCredentialsDetails `json:"clientCredentialsDetails,omitempty"`
	ClientCredentialsSource  *string                   `json:"clientCredentialsSource,omitempty"`
}

// A structure describing the name, data type, and geographic role of the columns.
type ColumnGroupColumnSchema struct {
	Name *string `json:"name,omitempty"`
}

// The column group schema.
type ColumnGroupSchema struct {
	Name *string `json:"name,omitempty"`
}

// The column schema.
type ColumnSchema struct {
	DataType       *string `json:"dataType,omitempty"`
	GeographicRole *string `json:"geographicRole,omitempty"`
	Name           *string `json:"name,omitempty"`
}

// The tooltip item for the columns that are not part of a field well.
type ColumnTooltipItem struct {
	Label *string `json:"label,omitempty"`
}

// A combo chart.
//
// The ComboChartVisual includes stacked bar combo charts and clustered bar
// combo charts
//
// For more information, see Using combo charts (https://docs.aws.amazon.com/quicksight/latest/user/combo-charts.html)
// in the Amazon Quick Suite User Guide.
type ComboChartVisual struct {
	VisualID *string `json:"visualID,omitempty"`
}

// Determines the custom condition for an icon set.
type ConditionalFormattingCustomIconCondition struct {
	Color *string `json:"color,omitempty"`
}

// Formatting configuration for solid color.
type ConditionalFormattingSolidColor struct {
	Color *string `json:"color,omitempty"`
}

// The contextual accent palette.
type ContextualAccentPalette struct {
	// The color palette.
	Automation *Palette `json:"automation,omitempty"`
	// The color palette.
	Connection *Palette `json:"connection,omitempty"`
	// The color palette.
	Insight *Palette `json:"insight,omitempty"`
	// The color palette.
	Visualization *Palette `json:"visualization,omitempty"`
}

// The definition for a CreateTopicReviewedAnswer.
type CreateTopicReviewedAnswer struct {
	DatasetARN *string `json:"datasetARN,omitempty"`
}

// Determines the color that's applied to a particular data value in a column.
type CustomColor struct {
	Color *string `json:"color,omitempty"`
}

// The parameters that are required to connect to a custom connection data source.
type CustomConnectionParameters struct {
	ConnectionType *string `json:"connectionType,omitempty"`
}

// A visual that contains custom content.
//
// For more information, see Using custom visual content (https://docs.aws.amazon.com/quicksight/latest/user/custom-visual-content.html)
// in the Amazon Quick Suite User Guide.
type CustomContentVisual struct {
	VisualID *string `json:"visualID,omitempty"`
}

// The custom permissions profile.
type CustomPermissions struct {
	ARN *string `json:"arn,omitempty"`
}

// A physical table type built from the results of the custom SQL query.
type CustomSQL struct {
	DataSourceARN *string `json:"dataSourceARN,omitempty"`
}

// Dashboard.
type Dashboard struct {
	ARN               *string      `json:"arn,omitempty"`
	CreatedTime       *metav1.Time `json:"createdTime,omitempty"`
	DashboardID       *string      `json:"dashboardID,omitempty"`
	LastPublishedTime *metav1.Time `json:"lastPublishedTime,omitempty"`
	LastUpdatedTime   *metav1.Time `json:"lastUpdatedTime,omitempty"`
}

// A filter that you apply when searching for dashboards.
type DashboardSearchFilter struct {
	Value *string `json:"value,omitempty"`
}

// Dashboard source template.
type DashboardSourceTemplate struct {
	ARN *string `json:"arn,omitempty"`
}

// Dashboard summary.
type DashboardSummary struct {
	ARN               *string      `json:"arn,omitempty"`
	CreatedTime       *metav1.Time `json:"createdTime,omitempty"`
	DashboardID       *string      `json:"dashboardID,omitempty"`
	LastPublishedTime *metav1.Time `json:"lastPublishedTime,omitempty"`
	LastUpdatedTime   *metav1.Time `json:"lastUpdatedTime,omitempty"`
}

// Dashboard version.
type DashboardVersion struct {
	ARN             *string      `json:"arn,omitempty"`
	CreatedTime     *metav1.Time `json:"createdTime,omitempty"`
	SourceEntityARN *string      `json:"sourceEntityARN,omitempty"`
	Status          *string      `json:"status,omitempty"`
	ThemeARN        *string      `json:"themeARN,omitempty"`
}

// Dashboard version summary.
type DashboardVersionSummary struct {
	ARN             *string      `json:"arn,omitempty"`
	CreatedTime     *metav1.Time `json:"createdTime,omitempty"`
	SourceEntityARN *string      `json:"sourceEntityARN,omitempty"`
	Status          *string      `json:"status,omitempty"`
}

// A structure that contains the following elements:
//
//   - The DashboardId of the dashboard that has the visual that you want to
//     embed.
//
//   - The SheetId of the sheet that has the visual that you want to embed.
//
//   - The VisualId of the visual that you want to embed.
//
// The DashboardId, SheetId, and VisualId can be found in the IDs for developers
// section of the Embed visual pane of the visual's on-visual menu of the Amazon
// Quick Sight console. You can also get the DashboardId with a ListDashboards
// API operation.
type DashboardVisualID struct {
	DashboardID *string `json:"dashboardID,omitempty"`
	SheetID     *string `json:"sheetID,omitempty"`
	VisualID    *string `json:"visualID,omitempty"`
}

// The QA result that is made from dashboard visual.
type DashboardVisualResult struct {
	DashboardID *string `json:"dashboardID,omitempty"`
	SheetID     *string `json:"sheetID,omitempty"`
	VisualID    *string `json:"visualID,omitempty"`
}

// The options for data bars.
type DataBarsOptions struct {
	NegativeColor *string `json:"negativeColor,omitempty"`
	PositiveColor *string `json:"positiveColor,omitempty"`
}

// Determines the color that is applied to a particular data value.
type DataColor struct {
	Color *string `json:"color,omitempty"`
}

// The theme colors that are used for data colors in charts. The colors description
// is a hexadecimal color code that consists of six alphanumerical characters,
// prefixed with #, for example #37BFF5.
type DataColorPalette struct {
	EmptyFillColor *string `json:"emptyFillColor,omitempty"`
}

// The options that determine the presentation of the data labels.
type DataLabelOptions struct {
	LabelColor *string `json:"labelColor,omitempty"`
}

// The color map that determines the color options for a particular element.
type DataPathColor struct {
	Color *string `json:"color,omitempty"`
}

// Dataset.
type DataSet struct {
	ARN             *string      `json:"arn,omitempty"`
	CreatedTime     *metav1.Time `json:"createdTime,omitempty"`
	LastUpdatedTime *metav1.Time `json:"lastUpdatedTime,omitempty"`
}

// Dataset configuration.
type DataSetConfiguration struct {
	Placeholder *string `json:"placeholder,omitempty"`
}

// A data set.
type DataSetIdentifierDeclaration struct {
	DataSetARN *string `json:"dataSetARN,omitempty"`
}

// Dataset reference.
type DataSetReference struct {
	DataSetARN *string `json:"dataSetARN,omitempty"`
}

// A filter that you apply when searching for datasets.
type DataSetSearchFilter struct {
	Value *string `json:"value,omitempty"`
}

// Dataset summary.
type DataSetSummary struct {
	ARN             *string      `json:"arn,omitempty"`
	CreatedTime     *metav1.Time `json:"createdTime,omitempty"`
	LastUpdatedTime *metav1.Time `json:"lastUpdatedTime,omitempty"`
}

// The structure of a data source.
type DataSource struct {
	ARN             *string      `json:"arn,omitempty"`
	CreatedTime     *metav1.Time `json:"createdTime,omitempty"`
	LastUpdatedTime *metav1.Time `json:"lastUpdatedTime,omitempty"`
	Status          *string      `json:"status,omitempty"`
}

// Error information for the data source creation or update.
type DataSourceErrorInfo struct {
	Message *string `json:"message,omitempty"`
}

// A filter that you apply when searching for data sources.
type DataSourceSearchFilter struct {
	Value *string `json:"value,omitempty"`
}

// A DataSourceSummary object that returns a summary of a data source.
type DataSourceSummary struct {
	ARN             *string      `json:"arn,omitempty"`
	CreatedTime     *metav1.Time `json:"createdTime,omitempty"`
	LastUpdatedTime *metav1.Time `json:"lastUpdatedTime,omitempty"`
}

// A structure that represents a dataset.
type DatasetMetadata struct {
	DatasetARN *string `json:"datasetARN,omitempty"`
}

// The configuration of destination parameter values.
//
// This is a union type structure. For this structure to be valid, only one
// of the attributes can be defined.
type DestinationParameterValueConfiguration struct {
	SourceParameterName *string `json:"sourceParameterName,omitempty"`
}

// An empty visual.
//
// Empty visuals are used in layouts but have not been configured to show any
// data. A new visual created in the Quick Sight console is considered an EmptyVisual
// until a visual type is selected.
type EmptyVisual struct {
	VisualID *string `json:"visualID,omitempty"`
}

// Error information for the SPICE ingestion of a dataset.
type ErrorInfo struct {
	Message *string `json:"message,omitempty"`
}

// An entry that appears when a KeyRegistration update to Quick Sight fails.
type FailedKeyRegistrationEntry struct {
	KeyARN     *string `json:"keyARN,omitempty"`
	StatusCode *int64  `json:"statusCode,omitempty"`
}

// The tooltip item for the fields.
type FieldTooltipItem struct {
	Label *string `json:"label,omitempty"`
}

// A filled map.
//
// For more information, see Creating filled maps (https://docs.aws.amazon.com/quicksight/latest/user/filled-maps.html)
// in the Amazon Quick Suite User Guide.
type FilledMapVisual struct {
	VisualID *string `json:"visualID,omitempty"`
}

// A control from a filter that is scoped across more than one sheet. This represents
// your filter control on a sheet
type FilterCrossSheetControl struct {
	FilterControlID *string `json:"filterControlID,omitempty"`
	SourceFilterID  *string `json:"sourceFilterID,omitempty"`
}

// A control from a date filter that is used to specify date and time.
type FilterDateTimePickerControl struct {
	FilterControlID *string `json:"filterControlID,omitempty"`
	SourceFilterID  *string `json:"sourceFilterID,omitempty"`
}

// A control to display a dropdown list with buttons that are used to select
// a single value.
type FilterDropDownControl struct {
	FilterControlID *string `json:"filterControlID,omitempty"`
	SourceFilterID  *string `json:"sourceFilterID,omitempty"`
}

// A grouping of individual filters. Filter groups are applied to the same group
// of visuals.
//
// For more information, see Adding filter conditions (group filters) with AND
// and OR operators (https://docs.aws.amazon.com/quicksight/latest/user/add-a-compound-filter.html)
// in the Amazon Quick Suite User Guide.
type FilterGroup struct {
	FilterGroupID *string `json:"filterGroupID,omitempty"`
}

// A control to display a list of buttons or boxes. This is used to select either
// a single value or multiple values.
type FilterListControl struct {
	FilterControlID *string `json:"filterControlID,omitempty"`
	SourceFilterID  *string `json:"sourceFilterID,omitempty"`
}

// A control from a date filter that is used to specify the relative date.
type FilterRelativeDateTimeControl struct {
	FilterControlID *string `json:"filterControlID,omitempty"`
	SourceFilterID  *string `json:"sourceFilterID,omitempty"`
}

// A control to display a horizontal toggle bar. This is used to change a value
// by sliding the toggle.
type FilterSliderControl struct {
	FilterControlID *string `json:"filterControlID,omitempty"`
	SourceFilterID  *string `json:"sourceFilterID,omitempty"`
}

// A control to display a text box that is used to enter multiple entries.
type FilterTextAreaControl struct {
	FilterControlID *string `json:"filterControlID,omitempty"`
	SourceFilterID  *string `json:"sourceFilterID,omitempty"`
}

// A control to display a text box that is used to enter a single entry.
type FilterTextFieldControl struct {
	FilterControlID *string `json:"filterControlID,omitempty"`
	SourceFilterID  *string `json:"sourceFilterID,omitempty"`
}

// The basic information of the flow exluding its definition specifying the
// steps.
type FlowSummary struct {
	ARN             *string      `json:"arn,omitempty"`
	CreatedBy       *string      `json:"createdBy,omitempty"`
	CreatedTime     *metav1.Time `json:"createdTime,omitempty"`
	LastPublishedAt *metav1.Time `json:"lastPublishedAt,omitempty"`
	LastPublishedBy *string      `json:"lastPublishedBy,omitempty"`
	LastUpdatedBy   *string      `json:"lastUpdatedBy,omitempty"`
	LastUpdatedTime *metav1.Time `json:"lastUpdatedTime,omitempty"`
}

// A folder in Quick Sight.
type Folder struct {
	ARN             *string      `json:"arn,omitempty"`
	CreatedTime     *metav1.Time `json:"createdTime,omitempty"`
	LastUpdatedTime *metav1.Time `json:"lastUpdatedTime,omitempty"`
}

// A filter to use to search an Quick Sight folder.
type FolderSearchFilter struct {
	Value *string `json:"value,omitempty"`
}

// A summary of information about an existing Quick Sight folder.
type FolderSummary struct {
	ARN             *string      `json:"arn,omitempty"`
	CreatedTime     *metav1.Time `json:"createdTime,omitempty"`
	LastUpdatedTime *metav1.Time `json:"lastUpdatedTime,omitempty"`
}

// Determines the font settings.
type Font struct {
	FontFamily *string `json:"fontFamily,omitempty"`
}

// Configures the display properties of the given text.
type FontConfiguration struct {
	FontColor  *string `json:"fontColor,omitempty"`
	FontFamily *string `json:"fontFamily,omitempty"`
}

// The forecast computation configuration.
type ForecastComputation struct {
	ComputationID *string `json:"computationID,omitempty"`
	Name          *string `json:"name,omitempty"`
}

// An element within a free-form layout.
type FreeFormLayoutElement struct {
	ElementID *string `json:"elementID,omitempty"`
}

// The options that determine the presentation of the data labels.
type FunnelChartDataLabelOptions struct {
	LabelColor *string `json:"labelColor,omitempty"`
}

// A funnel chart.
//
// For more information, see Using funnel charts (https://docs.aws.amazon.com/quicksight/latest/user/funnel-visual-content.html)
// in the Amazon Quick Suite User Guide.
type FunnelChartVisual struct {
	VisualID *string `json:"visualID,omitempty"`
}

// The color configuration of a GaugeChartVisual.
type GaugeChartColorConfiguration struct {
	BackgroundColor *string `json:"backgroundColor,omitempty"`
	ForegroundColor *string `json:"foregroundColor,omitempty"`
}

// A gauge chart.
//
// For more information, see Using gauge charts (https://docs.aws.amazon.com/quicksight/latest/user/gauge-chart.html)
// in the Amazon Quick Suite User Guide.
type GaugeChartVisual struct {
	VisualID *string `json:"visualID,omitempty"`
}

// The categorical data color for a single category.
type GeospatialCategoricalDataColor struct {
	DataValue *string `json:"dataValue,omitempty"`
}

// The color to be used in the heatmap point style.
type GeospatialHeatmapDataColor struct {
	Color *string `json:"color,omitempty"`
}

// The properties for a single geospatial layer.
type GeospatialLayerItem struct {
	Label   *string `json:"label,omitempty"`
	LayerID *string `json:"layerID,omitempty"`
}

// The custom actions for a layer.
type GeospatialLayerJoinDefinition struct {
	ShapeKeyField *string `json:"shapeKeyField,omitempty"`
}

// A geospatial map or a points on map visual.
//
// For more information, see Creating point maps (https://docs.aws.amazon.com/quicksight/latest/user/point-maps.html)
// in the Amazon Quick Suite User Guide.
type GeospatialMapVisual struct {
	VisualID *string `json:"visualID,omitempty"`
}

// The source properties for a geospatial static file.
type GeospatialStaticFileSource struct {
	StaticFileID *string `json:"staticFileID,omitempty"`
}

// Determines the gradient stop configuration.
type GradientStop struct {
	Color *string `json:"color,omitempty"`
}

// An element within a grid layout.
type GridLayoutElement struct {
	ElementID *string `json:"elementID,omitempty"`
}

// A group in Quick Sight consists of a set of users. You can use groups to
// make it easier to manage access and security.
type Group struct {
	ARN         *string `json:"arn,omitempty"`
	PrincipalID *string `json:"principalID,omitempty"`
}

// A member of an Quick Sight group. Currently, group members must be users.
// Groups can't be members of another group. .
type GroupMember struct {
	ARN *string `json:"arn,omitempty"`
}

// A GroupSearchFilter object that you want to apply to your search.
type GroupSearchFilter struct {
	Value *string `json:"value,omitempty"`
}

// The growth rate computation configuration.
type GrowthRateComputation struct {
	ComputationID *string `json:"computationID,omitempty"`
	Name          *string `json:"name,omitempty"`
}

// The configuration of a header or footer section.
type HeaderFooterSectionConfiguration struct {
	SectionID *string `json:"sectionID,omitempty"`
}

// A heat map.
//
// For more information, see Using heat maps (https://docs.aws.amazon.com/quicksight/latest/user/heat-map.html)
// in the Amazon Quick Suite User Guide.
type HeatMapVisual struct {
	VisualID *string `json:"visualID,omitempty"`
}

// A histogram.
//
// For more information, see Using histograms (https://docs.aws.amazon.com/quicksight/latest/user/histogram-charts.html)
// in the Amazon Quick Suite User Guide.
type HistogramVisual struct {
	VisualID *string `json:"visualID,omitempty"`
}

// Authentication metadata for IAM-based connections, used for first-party Amazon
// Web Services service integrations.
type IAMConnectionMetadata struct {
	RoleARN *string `json:"roleARN,omitempty"`
}

// An Identity and Access Management (IAM) policy assignment.
type IAMPolicyAssignment struct {
	AssignmentID *string `json:"assignmentID,omitempty"`
	AWSAccountID *string `json:"awsAccountID,omitempty"`
	PolicyARN    *string `json:"policyARN,omitempty"`
}

// The logo image.
type Image struct {
	GeneratedImageURL *string `json:"generatedImageURL,omitempty"`
	// The source of the image.
	Source *ImageSource `json:"source,omitempty"`
}

// The logo image configuration.
type ImageConfiguration struct {
	// The source of the image.
	Source *ImageSource `json:"source,omitempty"`
}

// A custom action defined on an image.
type ImageCustomAction struct {
	CustomActionID *string `json:"customActionID,omitempty"`
}

// The image set.
type ImageSet struct {
	// The logo image.
	Height32 *Image `json:"height32,omitempty"`
	// The logo image.
	Height64 *Image `json:"height64,omitempty"`
	// The logo image.
	Original *Image `json:"original,omitempty"`
}

// The image set configuration.
type ImageSetConfiguration struct {
	// The logo image configuration.
	Original *ImageConfiguration `json:"original,omitempty"`
}

// The source of the image.
type ImageSource struct {
	PublicURL *string `json:"publicURL,omitempty"`
	S3URI     *string `json:"s3URI,omitempty"`
}

// A static file that contains an image.
type ImageStaticFile struct {
	StaticFileID *string `json:"staticFileID,omitempty"`
}

// Information about the SPICE ingestion for a dataset.
type Ingestion struct {
	ARN         *string      `json:"arn,omitempty"`
	CreatedTime *metav1.Time `json:"createdTime,omitempty"`
}

// An insight visual.
//
// For more information, see Working with insights (https://docs.aws.amazon.com/quicksight/latest/user/computational-insights.html)
// in the Amazon Quick Suite User Guide.
type InsightVisual struct {
	VisualID *string `json:"visualID,omitempty"`
}

// The options that determine the visibility, color, type, and tooltip visibility
// of the sparkline of a KPI visual.
type KPISparklineOptions struct {
	Color *string `json:"color,omitempty"`
}

// A key performance indicator (KPI).
//
// For more information, see Using KPIs (https://docs.aws.amazon.com/quicksight/latest/user/kpi.html)
// in the Amazon Quick Suite User Guide.
type KPIVisual struct {
	VisualID *string `json:"visualID,omitempty"`
}

// The share label options for the labels.
type LabelOptions struct {
	CustomLabel *string `json:"customLabel,omitempty"`
}

// A layer custom action.
type LayerCustomAction struct {
	CustomActionID *string `json:"customActionID,omitempty"`
}

// A layer map visual.
type LayerMapVisual struct {
	VisualID *string `json:"visualID,omitempty"`
}

// Marker styles options for a line series in LineChartVisual.
type LineChartMarkerStyleSettings struct {
	MarkerColor *string `json:"markerColor,omitempty"`
}

// A line chart.
//
// For more information, see Using line charts (https://docs.aws.amazon.com/quicksight/latest/user/line-charts.html)
// in the Amazon Quick Suite User Guide.
type LineChartVisual struct {
	VisualID *string `json:"visualID,omitempty"`
}

// A structure that contains the configuration of a shareable link to the dashboard.
type LinkSharingConfiguration struct {
	Permissions []*ResourcePermission `json:"permissions,omitempty"`
}

// The navigation configuration for CustomActionNavigationOperation.
type LocalNavigationConfiguration struct {
	TargetSheetID *string `json:"targetSheetID,omitempty"`
}

// Information about the source of a logical table. This is a variant type structure.
// For this structure to be valid, only one of the attributes can be non-null.
type LogicalTableSource struct {
	DataSetARN *string `json:"dataSetARN,omitempty"`
}

// The logo configuration.
type Logo struct {
	AltText *string `json:"altText,omitempty"`
	// A set of logos.
	LogoSet *LogoSet `json:"logoSet,omitempty"`
}

// The logo configuration.
type LogoConfiguration struct {
	AltText *string `json:"altText,omitempty"`
	// The logo set configuration.
	LogoSet *LogoSetConfiguration `json:"logoSet,omitempty"`
}

// A set of logos.
type LogoSet struct {
	// The image set.
	Favicon *ImageSet `json:"favicon,omitempty"`
	// The image set.
	Primary *ImageSet `json:"primary,omitempty"`
}

// The logo set configuration.
type LogoSetConfiguration struct {
	// The image set configuration.
	Favicon *ImageSetConfiguration `json:"favicon,omitempty"`
	// The image set configuration.
	Primary *ImageSetConfiguration `json:"primary,omitempty"`
}

// The lookback window setup of an incremental refresh configuration.
type LookbackWindow struct {
	ColumnName *string `json:"columnName,omitempty"`
}

// The maximum and minimum computation configuration.
type MaximumMinimumComputation struct {
	ComputationID *string `json:"computationID,omitempty"`
	Name          *string `json:"name,omitempty"`
}

// An object that consists of a member Amazon Resource Name (ARN) and a member
// ID.
type MemberIDARNPair struct {
	MemberARN *string `json:"memberARN,omitempty"`
}

// The metric comparison computation configuration.
type MetricComparisonComputation struct {
	ComputationID *string `json:"computationID,omitempty"`
	Name          *string `json:"name,omitempty"`
}

// Errors that occur during namespace creation.
type NamespaceError struct {
	Message *string `json:"message,omitempty"`
}

// The error type.
type NamespaceInfoV2 struct {
	ARN                             *string `json:"arn,omitempty"`
	CapacityRegion                  *string `json:"capacityRegion,omitempty"`
	IAMIdentityCenterApplicationARN *string `json:"iamIdentityCenterApplicationARN,omitempty"`
	IAMIdentityCenterInstanceARN    *string `json:"iamIdentityCenterInstanceARN,omitempty"`
}

// The navigation bar style.
type NavbarStyle struct {
	// The color palette.
	ContextualNavbar *Palette `json:"contextualNavbar,omitempty"`
	// The color palette.
	GlobalNavbar *Palette `json:"globalNavbar,omitempty"`
}

// A NestedFilter filters data with a subset of data that is defined by the
// nested inner filter.
type NestedFilter struct {
	FilterID *string `json:"filterID,omitempty"`
}

// The structure that contains information about a network interface.
type NetworkInterface struct {
	AvailabilityZone *string `json:"availabilityZone,omitempty"`
	ErrorMessage     *string `json:"errorMessage,omitempty"`
}

// Authentication metadata for connections that do not require authentication
// credentials.
type NoneConnectionMetadata struct {
	BaseEndpoint *string `json:"baseEndpoint,omitempty"`
}

// A NumericEqualityFilter filters values that are equal to the specified value.
type NumericEqualityFilter struct {
	FilterID *string `json:"filterID,omitempty"`
}

// A NumericRangeFilter filters values that are within the value range.
type NumericRangeFilter struct {
	FilterID *string `json:"filterID,omitempty"`
}

// The color palette.
type Palette struct {
	Background *string `json:"background,omitempty"`
	Foreground *string `json:"foreground,omitempty"`
}

// A control from a date parameter that specifies date and time.
type ParameterDateTimePickerControl struct {
	ParameterControlID *string `json:"parameterControlID,omitempty"`
}

// A control to display a dropdown list with buttons that are used to select
// a single value.
type ParameterDropDownControl struct {
	ParameterControlID *string `json:"parameterControlID,omitempty"`
}

// A control to display a list with buttons or boxes that are used to select
// either a single value or multiple values.
type ParameterListControl struct {
	ParameterControlID *string `json:"parameterControlID,omitempty"`
}

// A control to display a horizontal toggle bar. This is used to change a value
// by sliding the toggle.
type ParameterSliderControl struct {
	ParameterControlID *string `json:"parameterControlID,omitempty"`
}

// A control to display a text box that is used to enter multiple entries.
type ParameterTextAreaControl struct {
	ParameterControlID *string `json:"parameterControlID,omitempty"`
}

// A control to display a text box that is used to enter a single entry.
type ParameterTextFieldControl struct {
	ParameterControlID *string `json:"parameterControlID,omitempty"`
}

// References a parent dataset that serves as a data source, including its columns
// and metadata.
type ParentDataSet struct {
	DataSetARN *string `json:"dataSetARN,omitempty"`
}

// The period over period computation configuration.
type PeriodOverPeriodComputation struct {
	ComputationID *string `json:"computationID,omitempty"`
	Name          *string `json:"name,omitempty"`
}

// The period to date computation configuration.
type PeriodToDateComputation struct {
	ComputationID *string `json:"computationID,omitempty"`
	Name          *string `json:"name,omitempty"`
}

// A pie or donut chart.
//
// The PieChartVisual structure describes a visual that is a member of the pie
// chart family.
//
// The following charts can be described by using this structure:
//
//   - Pie charts
//
//   - Donut charts
//
// For more information, see Using pie charts (https://docs.aws.amazon.com/quicksight/latest/user/pie-chart.html)
// in the Amazon Quick Suite User Guide.
//
// For more information, see Using donut charts (https://docs.aws.amazon.com/quicksight/latest/user/donut-chart.html)
// in the Amazon Quick Suite User Guide.
type PieChartVisual struct {
	VisualID *string `json:"visualID,omitempty"`
}

// The target of a pivot table field collapse state.
type PivotTableFieldCollapseStateTarget struct {
	FieldID *string `json:"fieldID,omitempty"`
}

// A pivot table.
//
// For more information, see Using pivot tables (https://docs.aws.amazon.com/quicksight/latest/user/pivot-table.html)
// in the Amazon Quick Suite User Guide.
type PivotTableVisual struct {
	VisualID *string `json:"visualID,omitempty"`
}

// The optional configuration of totals cells in a PivotTableVisual.
type PivotTotalOptions struct {
	CustomLabel *string `json:"customLabel,omitempty"`
}

// A flexible visualization type that allows engineers to create new custom
// charts in Quick Sight.
type PluginVisual struct {
	PluginARN *string `json:"pluginARN,omitempty"`
	VisualID  *string `json:"visualID,omitempty"`
}

// The key value pair of the persisted property.
type PluginVisualProperty struct {
	Name  *string `json:"name,omitempty"`
	Value *string `json:"value,omitempty"`
}

// A structure that contains information about the QDataKey.
type QDataKey struct {
	QDataKeyARN *string `json:"qDataKeyARN,omitempty"`
}

// Information about a queued dataset SPICE ingestion.
type QueueInfo struct {
	QueuedIngestion    *string `json:"queuedIngestion,omitempty"`
	WaitingOnIngestion *string `json:"waitingOnIngestion,omitempty"`
}

// The configuration of a RadarChartVisual.
type RadarChartConfiguration struct {
	AlternateBandEvenColor *string `json:"alternateBandEvenColor,omitempty"`
	AlternateBandOddColor  *string `json:"alternateBandOddColor,omitempty"`
}

// A radar chart visual.
type RadarChartVisual struct {
	VisualID *string `json:"visualID,omitempty"`
}

// Read-only authentication metadata for API key-based connections, containing
// non-sensitive configuration details.
type ReadAPIKeyConnectionMetadata struct {
	BaseEndpoint *string `json:"baseEndpoint,omitempty"`
	Email        *string `json:"email,omitempty"`
}

// Read-only authentication configuration containing non-sensitive authentication
// details for action connectors.
type ReadAuthConfig struct {
	// Read-only authentication metadata union containing non-sensitive configuration
	// details for different authentication types.
	AuthenticationMetadata *ReadAuthenticationMetadata `json:"authenticationMetadata,omitempty"`
	AuthenticationType     *string                     `json:"authenticationType,omitempty"`
}

// Read-only authentication metadata union containing non-sensitive configuration
// details for different authentication types.
type ReadAuthenticationMetadata struct {
	// Read-only authentication metadata for API key-based connections, containing
	// non-sensitive configuration details.
	APIKeyConnectionMetadata *ReadAPIKeyConnectionMetadata `json:"apiKeyConnectionMetadata,omitempty"`
	// Read-only metadata for OAuth2 authorization code grant authentication configuration.
	AuthorizationCodeGrantMetadata *ReadAuthorizationCodeGrantMetadata `json:"authorizationCodeGrantMetadata,omitempty"`
	// Read-only metadata for basic authentication connections, containing non-sensitive
	// configuration details.
	BasicAuthConnectionMetadata *ReadBasicAuthConnectionMetadata `json:"basicAuthConnectionMetadata,omitempty"`
	// Read-only metadata for OAuth2 client credentials grant authentication configuration.
	ClientCredentialsGrantMetadata *ReadClientCredentialsGrantMetadata `json:"clientCredentialsGrantMetadata,omitempty"`
	// Read-only metadata for IAM-based connections, containing role and source
	// ARN information.
	IAMConnectionMetadata *ReadIAMConnectionMetadata `json:"iamConnectionMetadata,omitempty"`
	// Read-only metadata for connections that do not require authentication credentials.
	NoneConnectionMetadata *ReadNoneConnectionMetadata `json:"noneConnectionMetadata,omitempty"`
}

// Read-only credentials details for OAuth2 authorization code grant flow, containing
// non-sensitive configuration information.
type ReadAuthorizationCodeGrantCredentialsDetails struct {
	// Read-only configuration details for OAuth2 authorization code grant flow,
	// including endpoints and client information.
	ReadAuthorizationCodeGrantDetails *ReadAuthorizationCodeGrantDetails `json:"readAuthorizationCodeGrantDetails,omitempty"`
}

// Read-only configuration details for OAuth2 authorization code grant flow,
// including endpoints and client information.
type ReadAuthorizationCodeGrantDetails struct {
	AuthorizationEndpoint *string `json:"authorizationEndpoint,omitempty"`
	ClientID              *string `json:"clientID,omitempty"`
	TokenEndpoint         *string `json:"tokenEndpoint,omitempty"`
}

// Read-only metadata for OAuth2 authorization code grant authentication configuration.
type ReadAuthorizationCodeGrantMetadata struct {
	AuthorizationCodeGrantCredentialsSource *string `json:"authorizationCodeGrantCredentialsSource,omitempty"`
	BaseEndpoint                            *string `json:"baseEndpoint,omitempty"`
	// Read-only credentials details for OAuth2 authorization code grant flow, containing
	// non-sensitive configuration information.
	ReadAuthorizationCodeGrantCredentialsDetails *ReadAuthorizationCodeGrantCredentialsDetails `json:"readAuthorizationCodeGrantCredentialsDetails,omitempty"`
	RedirectURL                                  *string                                       `json:"redirectURL,omitempty"`
}

// Read-only metadata for basic authentication connections, containing non-sensitive
// configuration details.
type ReadBasicAuthConnectionMetadata struct {
	BaseEndpoint *string `json:"baseEndpoint,omitempty"`
	Username     *string `json:"username,omitempty"`
}

// Read-only details for OAuth2 client credentials, containing non-sensitive
// configuration information.
type ReadClientCredentialsDetails struct {
	// Read-only configuration details for OAuth2 client credentials grant flow,
	// including client ID and token endpoint.
	ReadClientCredentialsGrantDetails *ReadClientCredentialsGrantDetails `json:"readClientCredentialsGrantDetails,omitempty"`
}

// Read-only configuration details for OAuth2 client credentials grant flow,
// including client ID and token endpoint.
type ReadClientCredentialsGrantDetails struct {
	ClientID      *string `json:"clientID,omitempty"`
	TokenEndpoint *string `json:"tokenEndpoint,omitempty"`
}

// Read-only metadata for OAuth2 client credentials grant authentication configuration.
type ReadClientCredentialsGrantMetadata struct {
	BaseEndpoint            *string `json:"baseEndpoint,omitempty"`
	ClientCredentialsSource *string `json:"clientCredentialsSource,omitempty"`
	// Read-only details for OAuth2 client credentials, containing non-sensitive
	// configuration information.
	ReadClientCredentialsDetails *ReadClientCredentialsDetails `json:"readClientCredentialsDetails,omitempty"`
}

// Read-only metadata for IAM-based connections, containing role and source
// ARN information.
type ReadIAMConnectionMetadata struct {
	RoleARN   *string `json:"roleARN,omitempty"`
	SourceARN *string `json:"sourceARN,omitempty"`
}

// Read-only metadata for connections that do not require authentication credentials.
type ReadNoneConnectionMetadata struct {
	BaseEndpoint *string `json:"baseEndpoint,omitempty"`
}

// A structure that grants Quick Sight access to your cluster and make a call
// to the redshift:GetClusterCredentials API. For more information on the redshift:GetClusterCredentials
// API, see GetClusterCredentials (https://docs.aws.amazon.com/redshift/latest/APIReference/API_GetClusterCredentials.html).
type RedshiftIAMParameters struct {
	RoleARN *string `json:"roleARN,omitempty"`
}

// The label configuration of a reference line.
type ReferenceLineLabelConfiguration struct {
	FontColor *string `json:"fontColor,omitempty"`
}

// The style configuration of the reference line.
type ReferenceLineStyleConfiguration struct {
	Color *string `json:"color,omitempty"`
}

// Specifies the interval between each scheduled refresh of a dataset.
type RefreshFrequency struct {
	TimeOfTheDay *string `json:"timeOfTheDay,omitempty"`
	Timezone     *string `json:"timezone,omitempty"`
}

// The refresh schedule of a dataset.
type RefreshSchedule struct {
	ARN                *string      `json:"arn,omitempty"`
	ScheduleID         *string      `json:"scheduleID,omitempty"`
	StartAfterDateTime *metav1.Time `json:"startAfterDateTime,omitempty"`
}

// A customer managed key structure that contains the information listed below:
//
//   - KeyArn - The ARN of a KMS key that is registered to a Quick Sight account
//     for encryption and decryption use.
//
//   - DefaultKey - Indicates whether the current key is set as the default
//     key for encryption and decryption use.
type RegisteredCustomerManagedKey struct {
	KeyARN *string `json:"keyARN,omitempty"`
}

// Information about the dashboard you want to embed.
type RegisteredUserDashboardEmbeddingConfiguration struct {
	InitialDashboardID *string `json:"initialDashboardID,omitempty"`
}

// A physical table type for relational data sources.
type RelationalTable struct {
	DataSourceARN *string `json:"dataSourceARN,omitempty"`
}

// A RelativeDatesFilter filters relative dates values.
type RelativeDatesFilter struct {
	FilterID *string `json:"filterID,omitempty"`
}

// Permission for the resource.
type ResourcePermission struct {
	Actions   []*string `json:"actions,omitempty"`
	Principal *string   `json:"principal,omitempty"`
}

// Information about a dataset that contains permissions for row-level security
// (RLS). The permissions dataset maps fields to users or groups. For more information,
// see Using Row-Level Security (RLS) to Restrict Access to a Dataset (https://docs.aws.amazon.com/quicksight/latest/user/restrict-access-to-a-data-set-using-row-level-security.html)
// in the Quick Sight User Guide.
//
// The option to deny permissions by setting PermissionPolicy to DENY_ACCESS
// is not supported for new RLS datasets.
type RowLevelPermissionDataSet struct {
	ARN *string `json:"arn,omitempty"`
}

// A set of rules associated with a tag.
type RowLevelPermissionTagRule struct {
	ColumnName *string `json:"columnName,omitempty"`
}

// The parameters that are required to connect to a S3 Knowledge Base data source.
type S3KnowledgeBaseParameters struct {
	RoleARN *string `json:"roleARN,omitempty"`
}

// The parameters for S3.
type S3Parameters struct {
	RoleARN *string `json:"roleARN,omitempty"`
}

// A physical table type for an S3 data source.
type S3Source struct {
	DataSourceARN *string `json:"dataSourceARN,omitempty"`
}

// A table from a Software-as-a-Service (SaaS) data source, including connection
// details and column definitions.
type SaaSTable struct {
	DataSourceARN *string `json:"dataSourceARN,omitempty"`
}

// A sankey diagram.
//
// For more information, see Using Sankey diagrams (https://docs.aws.amazon.com/quicksight/latest/user/sankey-diagram.html)
// in the Amazon Quick Suite User Guide.
type SankeyDiagramVisual struct {
	VisualID *string `json:"visualID,omitempty"`
}

// A scatter plot.
//
// For more information, see Using scatter plots (https://docs.aws.amazon.com/quicksight/latest/user/scatter-plot.html)
// in the Amazon Quick Suite User Guide.
type ScatterPlotVisual struct {
	VisualID *string `json:"visualID,omitempty"`
}

// A structure that contains the filter information when searching flows.
type SearchFlowsFilter struct {
	Value *string `json:"value,omitempty"`
}

// A sheet, which is an object that contains a set of visuals that are viewed
// together on one page in Quick Sight. Every analysis and dashboard contains
// at least one sheet. Each sheet contains at least one visualization widget,
// for example a chart, pivot table, or narrative insight. Sheets can be associated
// with other components, such as controls, filters, and so on.
type Sheet struct {
	SheetID *string `json:"sheetID,omitempty"`
}

// The background configuration for sheets.
type SheetBackgroundStyle struct {
	Gradient *string `json:"gradient,omitempty"`
}

// A sheet is an object that contains a set of visuals that are viewed together
// on one page in a paginated report. Every analysis and dashboard must contain
// at least one sheet.
type SheetDefinition struct {
	SheetID *string `json:"sheetID,omitempty"`
}

// An image that is located on a sheet.
type SheetImage struct {
	SheetImageID *string `json:"sheetImageID,omitempty"`
}

// The source of the static file that contains the image.
type SheetImageStaticFileSource struct {
	StaticFileID *string `json:"staticFileID,omitempty"`
}

// A text box.
type SheetTextBox struct {
	SheetTextBoxID *string `json:"sheetTextBoxID,omitempty"`
}

// The filter that is applied to the options.
type SheetVisualScopingConfiguration struct {
	SheetID *string `json:"sheetID,omitempty"`
}

// A SignupResponse object that contains a summary of a newly created account.
type SignupResponse struct {
	AccountName   *string `json:"accountName,omitempty"`
	DirectoryType *string `json:"directoryType,omitempty"`
	UserLoginName *string `json:"userLoginName,omitempty"`
}

// The simple cluster marker of the cluster marker.
type SimpleClusterMarker struct {
	Color *string `json:"color,omitempty"`
}

// A structure that contains information that identifies the snapshot that needs
// to be generated.
type SnapshotFileSheetSelection struct {
	SheetID *string `json:"sheetID,omitempty"`
}

// An object that contains information on the error that caused the snapshot
// job to fail.
type SnapshotJobErrorInfo struct {
	ErrorMessage *string `json:"errorMessage,omitempty"`
	ErrorType    *string `json:"errorType,omitempty"`
}

// Information on the error that caused the snapshot job to fail.
type SnapshotJobResultErrorInfo struct {
	ErrorMessage *string `json:"errorMessage,omitempty"`
	ErrorType    *string `json:"errorType,omitempty"`
}

// A static file that contains the geospatial data.
type SpatialStaticFile struct {
	StaticFileID *string `json:"staticFileID,omitempty"`
}

// The structure that contains the Amazon S3 location to download the static
// file from.
type StaticFileS3SourceOptions struct {
	BucketName *string `json:"bucketName,omitempty"`
	ObjectKey  *string `json:"objectKey,omitempty"`
	Region     *string `json:"region,omitempty"`
}

// The structure that contains the URL to download the static file from.
type StaticFileURLSourceOptions struct {
	URL *string `json:"url,omitempty"`
}

// The subtotal options.
type SubtotalOptions struct {
	CustomLabel *string `json:"customLabel,omitempty"`
}

// A success entry that occurs when a KeyRegistration job is successfully applied
// to the Quick Sight account.
type SuccessfulKeyRegistrationEntry struct {
	KeyARN     *string `json:"keyARN,omitempty"`
	StatusCode *int64  `json:"statusCode,omitempty"`
}

// The border options for a table border.
type TableBorderOptions struct {
	Color *string `json:"color,omitempty"`
}

// The table cell style for a cell in pivot table or table visual.
type TableCellStyle struct {
	BackgroundColor *string `json:"backgroundColor,omitempty"`
}

// The custom text content (value, font configuration) for the table link content
// configuration.
type TableFieldCustomTextContent struct {
	Value *string `json:"value,omitempty"`
}

// A table visual.
//
// For more information, see Using tables as visuals (https://docs.aws.amazon.com/quicksight/latest/user/tabular.html)
// in the Amazon Quick Suite User Guide.
type TableVisual struct {
	VisualID *string `json:"visualID,omitempty"`
}

// The key or keys of the key-value pairs for the resource tag or tags assigned
// to the resource.
type Tag struct {
	Key   *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}

// A template object. A template is an entity in Quick Sight that encapsulates
// the metadata required to create an analysis and that you can use to create
// a dashboard. A template adds a layer of abstraction by using placeholders
// to replace the dataset associated with an analysis. You can use templates
// to create dashboards by replacing dataset placeholders with datasets that
// follow the same schema that was used to create the source analysis and template.
//
// You can share templates across Amazon Web Services accounts by allowing users
// in other Amazon Web Services accounts to create a template or a dashboard
// from an existing template.
type Template struct {
	ARN             *string      `json:"arn,omitempty"`
	CreatedTime     *metav1.Time `json:"createdTime,omitempty"`
	LastUpdatedTime *metav1.Time `json:"lastUpdatedTime,omitempty"`
	TemplateID      *string      `json:"templateID,omitempty"`
}

// The template alias.
type TemplateAlias struct {
	ARN *string `json:"arn,omitempty"`
}

// The source analysis of the template.
type TemplateSourceAnalysis struct {
	ARN *string `json:"arn,omitempty"`
}

// The source template of the template.
type TemplateSourceTemplate struct {
	ARN *string `json:"arn,omitempty"`
}

// The template summary.
type TemplateSummary struct {
	ARN             *string      `json:"arn,omitempty"`
	CreatedTime     *metav1.Time `json:"createdTime,omitempty"`
	LastUpdatedTime *metav1.Time `json:"lastUpdatedTime,omitempty"`
	TemplateID      *string      `json:"templateID,omitempty"`
}

// A version of a template.
type TemplateVersion struct {
	CreatedTime     *metav1.Time `json:"createdTime,omitempty"`
	SourceEntityARN *string      `json:"sourceEntityARN,omitempty"`
	Status          *string      `json:"status,omitempty"`
	ThemeARN        *string      `json:"themeARN,omitempty"`
}

// The template version.
type TemplateVersionSummary struct {
	ARN         *string      `json:"arn,omitempty"`
	CreatedTime *metav1.Time `json:"createdTime,omitempty"`
	Status      *string      `json:"status,omitempty"`
}

// Summary information about a theme.
type Theme struct {
	ARN             *string      `json:"arn,omitempty"`
	CreatedTime     *metav1.Time `json:"createdTime,omitempty"`
	LastUpdatedTime *metav1.Time `json:"lastUpdatedTime,omitempty"`
	ThemeID         *string      `json:"themeID,omitempty"`
}

// An alias for a theme.
type ThemeAlias struct {
	ARN *string `json:"arn,omitempty"`
}

// The theme summary.
type ThemeSummary struct {
	ARN             *string      `json:"arn,omitempty"`
	CreatedTime     *metav1.Time `json:"createdTime,omitempty"`
	LastUpdatedTime *metav1.Time `json:"lastUpdatedTime,omitempty"`
	ThemeID         *string      `json:"themeID,omitempty"`
}

// A version of a theme.
type ThemeVersion struct {
	ARN         *string      `json:"arn,omitempty"`
	BaseThemeID *string      `json:"baseThemeID,omitempty"`
	CreatedTime *metav1.Time `json:"createdTime,omitempty"`
	Status      *string      `json:"status,omitempty"`
}

// The theme version.
type ThemeVersionSummary struct {
	ARN         *string      `json:"arn,omitempty"`
	CreatedTime *metav1.Time `json:"createdTime,omitempty"`
	Status      *string      `json:"status,omitempty"`
}

// A TimeEqualityFilter filters values that are equal to a given value.
type TimeEqualityFilter struct {
	FilterID *string      `json:"filterID,omitempty"`
	Value    *metav1.Time `json:"value,omitempty"`
}

// The time range drill down filter.
type TimeRangeDrillDownFilter struct {
	RangeMaximum *metav1.Time `json:"rangeMaximum,omitempty"`
	RangeMinimum *metav1.Time `json:"rangeMinimum,omitempty"`
}

// A TimeRangeFilter filters values that are between two specified values.
type TimeRangeFilter struct {
	FilterID *string `json:"filterID,omitempty"`
}

// The value of a time range filter.
//
// This is a union type structure. For this structure to be valid, only one
// of the attributes can be defined.
type TimeRangeFilterValue struct {
	StaticValue *metav1.Time `json:"staticValue,omitempty"`
}

// A TopBottomFilter filters values that are at the top or the bottom.
type TopBottomFilter struct {
	FilterID *string `json:"filterID,omitempty"`
}

// The top movers and bottom movers computation setup.
type TopBottomMoversComputation struct {
	ComputationID *string `json:"computationID,omitempty"`
	Name          *string `json:"name,omitempty"`
}

// The top ranked and bottom ranked computation configuration.
type TopBottomRankedComputation struct {
	ComputationID *string `json:"computationID,omitempty"`
	Name          *string `json:"name,omitempty"`
}

// The details about the refresh of a topic.
type TopicRefreshDetails struct {
	RefreshARN *string `json:"refreshARN,omitempty"`
}

// A structure that represents a topic refresh schedule.
type TopicRefreshSchedule struct {
	StartingAt *metav1.Time `json:"startingAt,omitempty"`
}

// A summary of the refresh schedule details for a dataset.
type TopicRefreshScheduleSummary struct {
	DatasetARN *string `json:"datasetARN,omitempty"`
}

// The deinition for a TopicReviewedAnswer.
type TopicReviewedAnswer struct {
	ARN        *string `json:"arn,omitempty"`
	DatasetARN *string `json:"datasetARN,omitempty"`
}

// The filter that is used to search for a topic.
type TopicSearchFilter struct {
	Value *string `json:"value,omitempty"`
}

// A topic summary.
type TopicSummary struct {
	ARN *string `json:"arn,omitempty"`
}

// The total aggregation computation configuration.
type TotalAggregationComputation struct {
	ComputationID *string `json:"computationID,omitempty"`
	Name          *string `json:"name,omitempty"`
}

// The total options for a table visual.
type TotalOptions struct {
	CustomLabel *string `json:"customLabel,omitempty"`
}

// A tree map.
//
// For more information, see Using tree maps (https://docs.aws.amazon.com/quicksight/latest/user/tree-map.html)
// in the Amazon Quick Suite User Guide.
type TreeMapVisual struct {
	VisualID *string `json:"visualID,omitempty"`
}

// The theme colors that apply to UI and to charts, excluding data colors. The
// colors description is a hexadecimal color code that consists of six alphanumerical
// characters, prefixed with #, for example #37BFF5. For more information, see
// Using Themes in Quick Sight (https://docs.aws.amazon.com/quicksight/latest/user/themes-in-quicksight.html)
// in the Quick Sight User Guide.
type UIColorPalette struct {
	Accent              *string `json:"accent,omitempty"`
	AccentForeground    *string `json:"accentForeground,omitempty"`
	Danger              *string `json:"danger,omitempty"`
	DangerForeground    *string `json:"dangerForeground,omitempty"`
	Dimension           *string `json:"dimension,omitempty"`
	DimensionForeground *string `json:"dimensionForeground,omitempty"`
	Measure             *string `json:"measure,omitempty"`
	MeasureForeground   *string `json:"measureForeground,omitempty"`
	PrimaryBackground   *string `json:"primaryBackground,omitempty"`
	PrimaryForeground   *string `json:"primaryForeground,omitempty"`
	SecondaryBackground *string `json:"secondaryBackground,omitempty"`
	SecondaryForeground *string `json:"secondaryForeground,omitempty"`
	Success             *string `json:"success,omitempty"`
	SuccessForeground   *string `json:"successForeground,omitempty"`
	Warning             *string `json:"warning,omitempty"`
	WarningForeground   *string `json:"warningForeground,omitempty"`
}

// The unique values computation configuration.
type UniqueValuesComputation struct {
	ComputationID *string `json:"computationID,omitempty"`
	Name          *string `json:"name,omitempty"`
}

// Information about the format for a source file or files.
type UploadSettings struct {
	CustomCellAddressRange *string `json:"customCellAddressRange,omitempty"`
}

// A registered user of Quick Sight.
type User struct {
	ARN                                 *string `json:"arn,omitempty"`
	Email                               *string `json:"email,omitempty"`
	ExternalLoginFederationProviderType *string `json:"externalLoginFederationProviderType,omitempty"`
	ExternalLoginFederationProviderURL  *string `json:"externalLoginFederationProviderURL,omitempty"`
	ExternalLoginID                     *string `json:"externalLoginID,omitempty"`
	PrincipalID                         *string `json:"principalID,omitempty"`
}

// The structure of a VPC connection.
type VPCConnection struct {
	ARN             *string      `json:"arn,omitempty"`
	CreatedTime     *metav1.Time `json:"createdTime,omitempty"`
	LastUpdatedTime *metav1.Time `json:"lastUpdatedTime,omitempty"`
	RoleARN         *string      `json:"roleARN,omitempty"`
	VPCID           *string      `json:"vpcID,omitempty"`
}

// VPC connection properties.
type VPCConnectionProperties struct {
	VPCConnectionARN *string `json:"vpcConnectionARN,omitempty"`
}

// The summary metadata that describes a VPC connection.
type VPCConnectionSummary struct {
	ARN             *string      `json:"arn,omitempty"`
	CreatedTime     *metav1.Time `json:"createdTime,omitempty"`
	LastUpdatedTime *metav1.Time `json:"lastUpdatedTime,omitempty"`
	RoleARN         *string      `json:"roleARN,omitempty"`
	VPCID           *string      `json:"vpcID,omitempty"`
}

// A custom action defined on a visual.
type VisualCustomAction struct {
	CustomActionID *string `json:"customActionID,omitempty"`
}

// The visual display options for the visual palette.
type VisualPalette struct {
	ChartColor *string `json:"chartColor,omitempty"`
}

// The color configuration for individual groups within a waterfall visual.
type WaterfallChartGroupColorConfiguration struct {
	NegativeBarColor *string `json:"negativeBarColor,omitempty"`
	PositiveBarColor *string `json:"positiveBarColor,omitempty"`
	TotalBarColor    *string `json:"totalBarColor,omitempty"`
}

// The options that determine the presentation of a waterfall visual.
type WaterfallChartOptions struct {
	TotalBarLabel *string `json:"totalBarLabel,omitempty"`
}

// A waterfall chart.
//
// For more information, see Using waterfall charts (https://docs.aws.amazon.com/quicksight/latest/user/waterfall-chart.html)
// in the Amazon Quick Suite User Guide.
type WaterfallVisual struct {
	VisualID *string `json:"visualID,omitempty"`
}

// Provides the forecast to meet the target for a particular date.
type WhatIfPointScenario struct {
	Date *metav1.Time `json:"date,omitempty"`
}

// Provides the forecast to meet the target for a particular date range.
type WhatIfRangeScenario struct {
	EndDate   *metav1.Time `json:"endDate,omitempty"`
	StartDate *metav1.Time `json:"startDate,omitempty"`
}

// A word cloud.
//
// For more information, see Using word clouds (https://docs.aws.amazon.com/quicksight/latest/user/word-cloud.html)
// in the Amazon Quick Suite User Guide.
type WordCloudVisual struct {
	VisualID *string `json:"visualID,omitempty"`
}
