//go:build !ignore_autogenerated

// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.


// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
corev1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSet) DeepCopyInto(out *DataSet) {
*out = *in
out.TypeMeta = in.TypeMeta
in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
in.Spec.DeepCopyInto(&out.Spec)
in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSet.
func (in *DataSet) DeepCopy() *DataSet {
	if in == nil { return nil }
	out := new(DataSet)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSetList) DeepCopyInto(out *DataSetList) {
*out = *in
out.TypeMeta = in.TypeMeta
in.ListMeta.DeepCopyInto(&out.ListMeta)
if in.Items != nil {
in, out := &in.Items, &out.Items
*out = make([]DataSet, len(*in))
for i := range *in {
(*in)[i].DeepCopyInto(&(*out)[i])
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSetList.
func (in *DataSetList) DeepCopy() *DataSetList {
	if in == nil { return nil }
	out := new(DataSetList)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSetSpec) DeepCopyInto(out *DataSetSpec) {
*out = *in
if in.AWSAccountID != nil {
in, out := &in.AWSAccountID, &out.AWSAccountID
*out = new(string)
**out = **in
}
if in.ColumnGroups != nil {
in, out := &in.ColumnGroups, &out.ColumnGroups
*out = make([]invalid type, len(*in))
for i := range *in {
}
}
if in.ColumnLevelPermissionRules != nil {
in, out := &in.ColumnLevelPermissionRules, &out.ColumnLevelPermissionRules
*out = make([]invalid type, len(*in))
for i := range *in {
}
}
if in.DataSetID != nil {
in, out := &in.DataSetID, &out.DataSetID
*out = new(string)
**out = **in
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSetSpec.
func (in *DataSetSpec) DeepCopy() *DataSetSpec {
	if in == nil { return nil }
	out := new(DataSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSetStatus) DeepCopyInto(out *DataSetStatus) {
*out = *in
if in.ACKResourceMetadata != nil {
in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
*out = new(corev1alpha1.ResourceMetadata)
(*in).DeepCopyInto(*out)
}
if in.Conditions != nil {
in, out := &in.Conditions, &out.Conditions
*out = make([]*corev1alpha1.Condition, len(*in))
for i := range *in {
if (*in)[i] != nil {
in, out := &(*in)[i], &(*out)[i]
*out = new(corev1alpha1.Condition)
(*in).DeepCopyInto(*out)
}
}
}
if in.IngestionARN != nil {
in, out := &in.IngestionARN, &out.IngestionARN
*out = new(string)
**out = **in
}
if in.IngestionID != nil {
in, out := &in.IngestionID, &out.IngestionID
*out = new(string)
**out = **in
}
if in.RequestID != nil {
in, out := &in.RequestID, &out.RequestID
*out = new(string)
**out = **in
}
if in.Status != nil {
in, out := &in.Status, &out.Status
*out = new(int64)
**out = **in
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSetStatus.
func (in *DataSetStatus) DeepCopy() *DataSetStatus {
	if in == nil { return nil }
	out := new(DataSetStatus)
	in.DeepCopyInto(out)
	return out
}

