// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package data_set

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.AWSAccountID, b.ko.Spec.AWSAccountID) {
		delta.Add("Spec.AWSAccountID", a.ko.Spec.AWSAccountID, b.ko.Spec.AWSAccountID)
	} else if a.ko.Spec.AWSAccountID != nil && b.ko.Spec.AWSAccountID != nil {
		if *a.ko.Spec.AWSAccountID != *b.ko.Spec.AWSAccountID {
			delta.Add("Spec.AWSAccountID", a.ko.Spec.AWSAccountID, b.ko.Spec.AWSAccountID)
		}
	}
	if len(a.ko.Spec.ColumnGroups) != len(b.ko.Spec.ColumnGroups) {
		delta.Add("Spec.ColumnGroups", a.ko.Spec.ColumnGroups, b.ko.Spec.ColumnGroups)
	} else if len(a.ko.Spec.ColumnGroups) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.ColumnGroups, b.ko.Spec.ColumnGroups) {
			delta.Add("Spec.ColumnGroups", a.ko.Spec.ColumnGroups, b.ko.Spec.ColumnGroups)
		}
	}
	if len(a.ko.Spec.ColumnLevelPermissionRules) != len(b.ko.Spec.ColumnLevelPermissionRules) {
		delta.Add("Spec.ColumnLevelPermissionRules", a.ko.Spec.ColumnLevelPermissionRules, b.ko.Spec.ColumnLevelPermissionRules)
	} else if len(a.ko.Spec.ColumnLevelPermissionRules) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.ColumnLevelPermissionRules, b.ko.Spec.ColumnLevelPermissionRules) {
			delta.Add("Spec.ColumnLevelPermissionRules", a.ko.Spec.ColumnLevelPermissionRules, b.ko.Spec.ColumnLevelPermissionRules)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.DataPrepConfiguration, b.ko.Spec.DataPrepConfiguration) {
		delta.Add("Spec.DataPrepConfiguration", a.ko.Spec.DataPrepConfiguration, b.ko.Spec.DataPrepConfiguration)
	} else if a.ko.Spec.DataPrepConfiguration != nil && b.ko.Spec.DataPrepConfiguration != nil {
		if len(a.ko.Spec.DataPrepConfiguration.DestinationTableMap) != len(b.ko.Spec.DataPrepConfiguration.DestinationTableMap) {
			delta.Add("Spec.DataPrepConfiguration.DestinationTableMap", a.ko.Spec.DataPrepConfiguration.DestinationTableMap, b.ko.Spec.DataPrepConfiguration.DestinationTableMap)
		} else if len(a.ko.Spec.DataPrepConfiguration.DestinationTableMap) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.DataPrepConfiguration.DestinationTableMap, b.ko.Spec.DataPrepConfiguration.DestinationTableMap) {
				delta.Add("Spec.DataPrepConfiguration.DestinationTableMap", a.ko.Spec.DataPrepConfiguration.DestinationTableMap, b.ko.Spec.DataPrepConfiguration.DestinationTableMap)
			}
		}
		if len(a.ko.Spec.DataPrepConfiguration.SourceTableMap) != len(b.ko.Spec.DataPrepConfiguration.SourceTableMap) {
			delta.Add("Spec.DataPrepConfiguration.SourceTableMap", a.ko.Spec.DataPrepConfiguration.SourceTableMap, b.ko.Spec.DataPrepConfiguration.SourceTableMap)
		} else if len(a.ko.Spec.DataPrepConfiguration.SourceTableMap) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.DataPrepConfiguration.SourceTableMap, b.ko.Spec.DataPrepConfiguration.SourceTableMap) {
				delta.Add("Spec.DataPrepConfiguration.SourceTableMap", a.ko.Spec.DataPrepConfiguration.SourceTableMap, b.ko.Spec.DataPrepConfiguration.SourceTableMap)
			}
		}
		if len(a.ko.Spec.DataPrepConfiguration.TransformStepMap) != len(b.ko.Spec.DataPrepConfiguration.TransformStepMap) {
			delta.Add("Spec.DataPrepConfiguration.TransformStepMap", a.ko.Spec.DataPrepConfiguration.TransformStepMap, b.ko.Spec.DataPrepConfiguration.TransformStepMap)
		} else if len(a.ko.Spec.DataPrepConfiguration.TransformStepMap) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.DataPrepConfiguration.TransformStepMap, b.ko.Spec.DataPrepConfiguration.TransformStepMap) {
				delta.Add("Spec.DataPrepConfiguration.TransformStepMap", a.ko.Spec.DataPrepConfiguration.TransformStepMap, b.ko.Spec.DataPrepConfiguration.TransformStepMap)
			}
		}
	}
	if len(a.ko.Spec.FieldFolders) != len(b.ko.Spec.FieldFolders) {
		delta.Add("Spec.FieldFolders", a.ko.Spec.FieldFolders, b.ko.Spec.FieldFolders)
	} else if len(a.ko.Spec.FieldFolders) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.FieldFolders, b.ko.Spec.FieldFolders) {
			delta.Add("Spec.FieldFolders", a.ko.Spec.FieldFolders, b.ko.Spec.FieldFolders)
		}
	}
	if len(a.ko.Spec.FolderARNs) != len(b.ko.Spec.FolderARNs) {
		delta.Add("Spec.FolderARNs", a.ko.Spec.FolderARNs, b.ko.Spec.FolderARNs)
	} else if len(a.ko.Spec.FolderARNs) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.FolderARNs, b.ko.Spec.FolderARNs) {
			delta.Add("Spec.FolderARNs", a.ko.Spec.FolderARNs, b.ko.Spec.FolderARNs)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ID, b.ko.Spec.ID) {
		delta.Add("Spec.ID", a.ko.Spec.ID, b.ko.Spec.ID)
	} else if a.ko.Spec.ID != nil && b.ko.Spec.ID != nil {
		if *a.ko.Spec.ID != *b.ko.Spec.ID {
			delta.Add("Spec.ID", a.ko.Spec.ID, b.ko.Spec.ID)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ImportMode, b.ko.Spec.ImportMode) {
		delta.Add("Spec.ImportMode", a.ko.Spec.ImportMode, b.ko.Spec.ImportMode)
	} else if a.ko.Spec.ImportMode != nil && b.ko.Spec.ImportMode != nil {
		if *a.ko.Spec.ImportMode != *b.ko.Spec.ImportMode {
			delta.Add("Spec.ImportMode", a.ko.Spec.ImportMode, b.ko.Spec.ImportMode)
		}
	}
	if len(a.ko.Spec.LogicalTableMap) != len(b.ko.Spec.LogicalTableMap) {
		delta.Add("Spec.LogicalTableMap", a.ko.Spec.LogicalTableMap, b.ko.Spec.LogicalTableMap)
	} else if len(a.ko.Spec.LogicalTableMap) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.LogicalTableMap, b.ko.Spec.LogicalTableMap) {
			delta.Add("Spec.LogicalTableMap", a.ko.Spec.LogicalTableMap, b.ko.Spec.LogicalTableMap)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if len(a.ko.Spec.Parameters) != len(b.ko.Spec.Parameters) {
		delta.Add("Spec.Parameters", a.ko.Spec.Parameters, b.ko.Spec.Parameters)
	} else if len(a.ko.Spec.Parameters) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Parameters, b.ko.Spec.Parameters) {
			delta.Add("Spec.Parameters", a.ko.Spec.Parameters, b.ko.Spec.Parameters)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.PerformanceConfiguration, b.ko.Spec.PerformanceConfiguration) {
		delta.Add("Spec.PerformanceConfiguration", a.ko.Spec.PerformanceConfiguration, b.ko.Spec.PerformanceConfiguration)
	} else if a.ko.Spec.PerformanceConfiguration != nil && b.ko.Spec.PerformanceConfiguration != nil {
		if len(a.ko.Spec.PerformanceConfiguration.UniqueKeys) != len(b.ko.Spec.PerformanceConfiguration.UniqueKeys) {
			delta.Add("Spec.PerformanceConfiguration.UniqueKeys", a.ko.Spec.PerformanceConfiguration.UniqueKeys, b.ko.Spec.PerformanceConfiguration.UniqueKeys)
		} else if len(a.ko.Spec.PerformanceConfiguration.UniqueKeys) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.PerformanceConfiguration.UniqueKeys, b.ko.Spec.PerformanceConfiguration.UniqueKeys) {
				delta.Add("Spec.PerformanceConfiguration.UniqueKeys", a.ko.Spec.PerformanceConfiguration.UniqueKeys, b.ko.Spec.PerformanceConfiguration.UniqueKeys)
			}
		}
	}
	if len(a.ko.Spec.Permissions) != len(b.ko.Spec.Permissions) {
		delta.Add("Spec.Permissions", a.ko.Spec.Permissions, b.ko.Spec.Permissions)
	} else if len(a.ko.Spec.Permissions) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Permissions, b.ko.Spec.Permissions) {
			delta.Add("Spec.Permissions", a.ko.Spec.Permissions, b.ko.Spec.Permissions)
		}
	}
	if len(a.ko.Spec.PhysicalTableMap) != len(b.ko.Spec.PhysicalTableMap) {
		delta.Add("Spec.PhysicalTableMap", a.ko.Spec.PhysicalTableMap, b.ko.Spec.PhysicalTableMap)
	} else if len(a.ko.Spec.PhysicalTableMap) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.PhysicalTableMap, b.ko.Spec.PhysicalTableMap) {
			delta.Add("Spec.PhysicalTableMap", a.ko.Spec.PhysicalTableMap, b.ko.Spec.PhysicalTableMap)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.RowLevelPermissionDataSet, b.ko.Spec.RowLevelPermissionDataSet) {
		delta.Add("Spec.RowLevelPermissionDataSet", a.ko.Spec.RowLevelPermissionDataSet, b.ko.Spec.RowLevelPermissionDataSet)
	} else if a.ko.Spec.RowLevelPermissionDataSet != nil && b.ko.Spec.RowLevelPermissionDataSet != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.RowLevelPermissionDataSet.ARN, b.ko.Spec.RowLevelPermissionDataSet.ARN) {
			delta.Add("Spec.RowLevelPermissionDataSet.ARN", a.ko.Spec.RowLevelPermissionDataSet.ARN, b.ko.Spec.RowLevelPermissionDataSet.ARN)
		} else if a.ko.Spec.RowLevelPermissionDataSet.ARN != nil && b.ko.Spec.RowLevelPermissionDataSet.ARN != nil {
			if *a.ko.Spec.RowLevelPermissionDataSet.ARN != *b.ko.Spec.RowLevelPermissionDataSet.ARN {
				delta.Add("Spec.RowLevelPermissionDataSet.ARN", a.ko.Spec.RowLevelPermissionDataSet.ARN, b.ko.Spec.RowLevelPermissionDataSet.ARN)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.RowLevelPermissionDataSet.FormatVersion, b.ko.Spec.RowLevelPermissionDataSet.FormatVersion) {
			delta.Add("Spec.RowLevelPermissionDataSet.FormatVersion", a.ko.Spec.RowLevelPermissionDataSet.FormatVersion, b.ko.Spec.RowLevelPermissionDataSet.FormatVersion)
		} else if a.ko.Spec.RowLevelPermissionDataSet.FormatVersion != nil && b.ko.Spec.RowLevelPermissionDataSet.FormatVersion != nil {
			if *a.ko.Spec.RowLevelPermissionDataSet.FormatVersion != *b.ko.Spec.RowLevelPermissionDataSet.FormatVersion {
				delta.Add("Spec.RowLevelPermissionDataSet.FormatVersion", a.ko.Spec.RowLevelPermissionDataSet.FormatVersion, b.ko.Spec.RowLevelPermissionDataSet.FormatVersion)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.RowLevelPermissionDataSet.Namespace, b.ko.Spec.RowLevelPermissionDataSet.Namespace) {
			delta.Add("Spec.RowLevelPermissionDataSet.Namespace", a.ko.Spec.RowLevelPermissionDataSet.Namespace, b.ko.Spec.RowLevelPermissionDataSet.Namespace)
		} else if a.ko.Spec.RowLevelPermissionDataSet.Namespace != nil && b.ko.Spec.RowLevelPermissionDataSet.Namespace != nil {
			if *a.ko.Spec.RowLevelPermissionDataSet.Namespace != *b.ko.Spec.RowLevelPermissionDataSet.Namespace {
				delta.Add("Spec.RowLevelPermissionDataSet.Namespace", a.ko.Spec.RowLevelPermissionDataSet.Namespace, b.ko.Spec.RowLevelPermissionDataSet.Namespace)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.RowLevelPermissionDataSet.PermissionPolicy, b.ko.Spec.RowLevelPermissionDataSet.PermissionPolicy) {
			delta.Add("Spec.RowLevelPermissionDataSet.PermissionPolicy", a.ko.Spec.RowLevelPermissionDataSet.PermissionPolicy, b.ko.Spec.RowLevelPermissionDataSet.PermissionPolicy)
		} else if a.ko.Spec.RowLevelPermissionDataSet.PermissionPolicy != nil && b.ko.Spec.RowLevelPermissionDataSet.PermissionPolicy != nil {
			if *a.ko.Spec.RowLevelPermissionDataSet.PermissionPolicy != *b.ko.Spec.RowLevelPermissionDataSet.PermissionPolicy {
				delta.Add("Spec.RowLevelPermissionDataSet.PermissionPolicy", a.ko.Spec.RowLevelPermissionDataSet.PermissionPolicy, b.ko.Spec.RowLevelPermissionDataSet.PermissionPolicy)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.RowLevelPermissionDataSet.Status, b.ko.Spec.RowLevelPermissionDataSet.Status) {
			delta.Add("Spec.RowLevelPermissionDataSet.Status", a.ko.Spec.RowLevelPermissionDataSet.Status, b.ko.Spec.RowLevelPermissionDataSet.Status)
		} else if a.ko.Spec.RowLevelPermissionDataSet.Status != nil && b.ko.Spec.RowLevelPermissionDataSet.Status != nil {
			if *a.ko.Spec.RowLevelPermissionDataSet.Status != *b.ko.Spec.RowLevelPermissionDataSet.Status {
				delta.Add("Spec.RowLevelPermissionDataSet.Status", a.ko.Spec.RowLevelPermissionDataSet.Status, b.ko.Spec.RowLevelPermissionDataSet.Status)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.RowLevelPermissionTagConfiguration, b.ko.Spec.RowLevelPermissionTagConfiguration) {
		delta.Add("Spec.RowLevelPermissionTagConfiguration", a.ko.Spec.RowLevelPermissionTagConfiguration, b.ko.Spec.RowLevelPermissionTagConfiguration)
	} else if a.ko.Spec.RowLevelPermissionTagConfiguration != nil && b.ko.Spec.RowLevelPermissionTagConfiguration != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.RowLevelPermissionTagConfiguration.Status, b.ko.Spec.RowLevelPermissionTagConfiguration.Status) {
			delta.Add("Spec.RowLevelPermissionTagConfiguration.Status", a.ko.Spec.RowLevelPermissionTagConfiguration.Status, b.ko.Spec.RowLevelPermissionTagConfiguration.Status)
		} else if a.ko.Spec.RowLevelPermissionTagConfiguration.Status != nil && b.ko.Spec.RowLevelPermissionTagConfiguration.Status != nil {
			if *a.ko.Spec.RowLevelPermissionTagConfiguration.Status != *b.ko.Spec.RowLevelPermissionTagConfiguration.Status {
				delta.Add("Spec.RowLevelPermissionTagConfiguration.Status", a.ko.Spec.RowLevelPermissionTagConfiguration.Status, b.ko.Spec.RowLevelPermissionTagConfiguration.Status)
			}
		}
		if len(a.ko.Spec.RowLevelPermissionTagConfiguration.TagRuleConfigurations) != len(b.ko.Spec.RowLevelPermissionTagConfiguration.TagRuleConfigurations) {
			delta.Add("Spec.RowLevelPermissionTagConfiguration.TagRuleConfigurations", a.ko.Spec.RowLevelPermissionTagConfiguration.TagRuleConfigurations, b.ko.Spec.RowLevelPermissionTagConfiguration.TagRuleConfigurations)
		} else if len(a.ko.Spec.RowLevelPermissionTagConfiguration.TagRuleConfigurations) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.RowLevelPermissionTagConfiguration.TagRuleConfigurations, b.ko.Spec.RowLevelPermissionTagConfiguration.TagRuleConfigurations) {
				delta.Add("Spec.RowLevelPermissionTagConfiguration.TagRuleConfigurations", a.ko.Spec.RowLevelPermissionTagConfiguration.TagRuleConfigurations, b.ko.Spec.RowLevelPermissionTagConfiguration.TagRuleConfigurations)
			}
		}
		if len(a.ko.Spec.RowLevelPermissionTagConfiguration.TagRules) != len(b.ko.Spec.RowLevelPermissionTagConfiguration.TagRules) {
			delta.Add("Spec.RowLevelPermissionTagConfiguration.TagRules", a.ko.Spec.RowLevelPermissionTagConfiguration.TagRules, b.ko.Spec.RowLevelPermissionTagConfiguration.TagRules)
		} else if len(a.ko.Spec.RowLevelPermissionTagConfiguration.TagRules) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.RowLevelPermissionTagConfiguration.TagRules, b.ko.Spec.RowLevelPermissionTagConfiguration.TagRules) {
				delta.Add("Spec.RowLevelPermissionTagConfiguration.TagRules", a.ko.Spec.RowLevelPermissionTagConfiguration.TagRules, b.ko.Spec.RowLevelPermissionTagConfiguration.TagRules)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.SemanticModelConfiguration, b.ko.Spec.SemanticModelConfiguration) {
		delta.Add("Spec.SemanticModelConfiguration", a.ko.Spec.SemanticModelConfiguration, b.ko.Spec.SemanticModelConfiguration)
	} else if a.ko.Spec.SemanticModelConfiguration != nil && b.ko.Spec.SemanticModelConfiguration != nil {
		if len(a.ko.Spec.SemanticModelConfiguration.TableMap) != len(b.ko.Spec.SemanticModelConfiguration.TableMap) {
			delta.Add("Spec.SemanticModelConfiguration.TableMap", a.ko.Spec.SemanticModelConfiguration.TableMap, b.ko.Spec.SemanticModelConfiguration.TableMap)
		} else if len(a.ko.Spec.SemanticModelConfiguration.TableMap) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.SemanticModelConfiguration.TableMap, b.ko.Spec.SemanticModelConfiguration.TableMap) {
				delta.Add("Spec.SemanticModelConfiguration.TableMap", a.ko.Spec.SemanticModelConfiguration.TableMap, b.ko.Spec.SemanticModelConfiguration.TableMap)
			}
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.UsageConfiguration, b.ko.Spec.UsageConfiguration) {
		delta.Add("Spec.UsageConfiguration", a.ko.Spec.UsageConfiguration, b.ko.Spec.UsageConfiguration)
	} else if a.ko.Spec.UsageConfiguration != nil && b.ko.Spec.UsageConfiguration != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.UsageConfiguration.DisableUseAsDirectQuerySource, b.ko.Spec.UsageConfiguration.DisableUseAsDirectQuerySource) {
			delta.Add("Spec.UsageConfiguration.DisableUseAsDirectQuerySource", a.ko.Spec.UsageConfiguration.DisableUseAsDirectQuerySource, b.ko.Spec.UsageConfiguration.DisableUseAsDirectQuerySource)
		} else if a.ko.Spec.UsageConfiguration.DisableUseAsDirectQuerySource != nil && b.ko.Spec.UsageConfiguration.DisableUseAsDirectQuerySource != nil {
			if *a.ko.Spec.UsageConfiguration.DisableUseAsDirectQuerySource != *b.ko.Spec.UsageConfiguration.DisableUseAsDirectQuerySource {
				delta.Add("Spec.UsageConfiguration.DisableUseAsDirectQuerySource", a.ko.Spec.UsageConfiguration.DisableUseAsDirectQuerySource, b.ko.Spec.UsageConfiguration.DisableUseAsDirectQuerySource)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.UsageConfiguration.DisableUseAsImportedSource, b.ko.Spec.UsageConfiguration.DisableUseAsImportedSource) {
			delta.Add("Spec.UsageConfiguration.DisableUseAsImportedSource", a.ko.Spec.UsageConfiguration.DisableUseAsImportedSource, b.ko.Spec.UsageConfiguration.DisableUseAsImportedSource)
		} else if a.ko.Spec.UsageConfiguration.DisableUseAsImportedSource != nil && b.ko.Spec.UsageConfiguration.DisableUseAsImportedSource != nil {
			if *a.ko.Spec.UsageConfiguration.DisableUseAsImportedSource != *b.ko.Spec.UsageConfiguration.DisableUseAsImportedSource {
				delta.Add("Spec.UsageConfiguration.DisableUseAsImportedSource", a.ko.Spec.UsageConfiguration.DisableUseAsImportedSource, b.ko.Spec.UsageConfiguration.DisableUseAsImportedSource)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.UseAs, b.ko.Spec.UseAs) {
		delta.Add("Spec.UseAs", a.ko.Spec.UseAs, b.ko.Spec.UseAs)
	} else if a.ko.Spec.UseAs != nil && b.ko.Spec.UseAs != nil {
		if *a.ko.Spec.UseAs != *b.ko.Spec.UseAs {
			delta.Add("Spec.UseAs", a.ko.Spec.UseAs, b.ko.Spec.UseAs)
		}
	}

	return delta
}
